module.exports = {
  "BLACKLISTED_SOCS": "Please note that some of the selected socs are black listed, no longer eligible and will not be part of the order.",
  "CART_TYPE-MA_CHANGE_SUB_NAME_ADD": "Attendee management",
  "CART_TYPE-MA_MAINTAIN_SOC": "Manage tariff options",
  "INACTIVE_SOCS": "Please note that some of the selected socs are inactive, no longer eligible and will not be part of the order.",
  "OrderType.MA_CHANGE_SUB_NAME_ADD": "SUBMGT",
  "OrderType.MA_MAINTAIN_SOC": "MSOC",
  "PSC_ALL_INVALID_SUBS": "All selected subscribers are invalid.",
  "PSC_INVALID_SUBS": "Please note that some of the selected subscribers are no longer eligible and will not be part of the order.",
  "REMOVE_SOCS_MISSING_SUBSCRIBERS": "Please note that some of the removed socs are not associated to any sbuscribers, no longer eligible and will not be part of the order.",
  "SHOPPING_CART_COUNT_DETAILS": "There are {{count}} pre-filled shopping carts available",
  "SHOPPING_CART_COUNT_MULTIPLE": "There are {{count}} prefilled shopping carts available.",
  "SHOPPING_CART_COUNT_ONE": "There is 1 prefilled shopping carts available.",
  "SHOPPING_CART_DATE": "Modify Date",
  "SHOPPING_CART_DELETE_MSG_BOTTOM": "Are sure you want to delete the shopping cart \"{{shoppingCartName}}\"?",
  "SHOPPING_CART_DELETE_MSG_TOP": "Delete prefilled shopping cart",
  "SHOPPING_CART_DESCRIPTION": "Please note that opening a shopping cart locks it for {{lockingPeriod}} minutes for other applications. Make sure that you save your changes or send the order within this time.",
  "SHOPPING_CART_EXCEPTION": "This shopping cart is no longer available.",
  "SHOPPING_CART_HEADER": "Customer",
  "SHOPPING_CART_INTERNAL_ID": "Customer order information",
  "SHOPPING_CART_LOCKED": "Unfortunately, you can not open the shopping cart because another user is currently editing it. Please try again later.",
  "SHOPPING_CART_MSISDN": "In-house order number",
  "SHOPPING_CART_NAME": "Shopping cart name",
  "SHOPPING_CART_NOT_EXISTS": "This shopping cart is no longer available.",
  "SHOPPING_CART_ORDER_TYPE": "Order type",
  "SHOPPING_CART_POPUP_CANCEL": "Cancel",
  "SHOPPING_CART_POPUP_DELETE": "Delete",
  "SHOPPING_CART_QUANTITY": "Num. of the participants",
  "SOCS_NOT_IN_SHOP": "Please note that some of the selected socs are not in the shop, no longer eligible and will not be part of the order.",
  "SOC_PRICE_INVALID": "Please note that some of the selected socs price is invalid, hence the updated price will be considered for the order.",
  "TARIFF_SOCS_WITH_RELATION_N": "Please note that some of the selected socs are associated to tariff with relation type N, no longer eligible and will not be part of the order."
};