module.exports = {
  "SHIPMENT-COL-PACKET": "Paket",
  "SHIPMENT-COL-SERVICE": "Logistikpartner",
  "SHIPMENT-COL-TRACKING": "Sendungsnummer",
  "SHIPMENT-COL-TRACKING-INFO": "You can track your deliveries with our logistics partner by clicking on the consignment number. Note that it may take up to 1 day for the data to be available at the logistics partner.",
  "APPROVER_PAGE-TITLE": "APPROVER DETAILS",
  "OVER_VIEW-TITLE": "Order overview",
  "BACK_BUTTON-TITLE": "Back",
  "SAVE_BUTTON-TITLE": "Save Changes",
  "SELECT_ACTION_LABLE": "Select action",
  "ORDER_DETAILS-CHOOSE": "Choose",
  "ORDER_DETAILS-TITLE": "Order Details",
  "ORDER_NUMBER-TITLE": "Order Number",
  "ORDER_TYPE-TITLE": "Job Type",
  "ORDER_DATE-TITLE": "Order Date",
  "ORDER_STATUS-TITLE": "Order Status",
  "CUSTOMER_NUMBER-TITLE": "Customer Number",
  "GENERAL_AGREEMENT-TITLE": "General Agreement",
  "CUSTOMER-TITLE": "Customer",
  "INPUT_CHANNEL-TITLE": "Input channel",
  "DELIVERY_DATE-TITLE": "Delivery Date",
  "VO_ID-TITLE": "VO-ID",
  "CUSTOMER_INTERNAL_ORDER-NUMBER": "Customer internal order number",
  "CUSTOMER_ORDER-INFORMATION": "Customer order information",
  "BILLING-INFORMATION": "Billing information",
  "CUSTOMER-NUMBER": "Customer number",
  "BILLING_ADESS-TITLE": "Billing address",
  "SHIPPING_ADESS-TITLE": "Shipping address",
  "DELIVERY-TITLE": "Delivery",
  "ADMIN_COMMENTS-TITLE": "Admin comments",
  "ORDER_HISTORY-TITLE": "Order history",
  "ORDER_HEADER-TITLE": "Order Details",
  "APPROVED_DROPDOWN-TEXT": "Approved",
  "DECLINED_DROPDOWN-TEXT": "Declined",
  "PENDING_APPROVAL_DROPDOWN-TEXT": "Pending approval"

};