module.exports = {
  'PLANNED_CHANGES-DESCRIPTION_MSG': 'Please select the desired changes before you check the order.',
  'SOC_MANDATORY_ERROR_MSG': '<b>Sorry,there was an error</b><p>Please choose one of the mandatory options.</p>',
  'SOC_SELECTION-ACTIVATION_DATE': 'Activation Date: ',
  'SOC_SELECTION-BUNDLE_TYPE': 'Base Price (mtl.)¹',
  'SOC_SELECTION-CATEGORIES': 'Categories',
  'SOC_SELECTION-FILTER_TARIFF_OPTIONS': 'Filter tariff options',
  'SOC_SELECTION-FREE_OF_CHARGE': 'Free of charge',
  'SOC_SELECTION-HIDE_DESCRIPTION': 'Hide description',
  'SOC_SELECTION-MASTER_DESCRIPTION': 'Please select one of the following tariff options for the numbers that do not yet have a tariff option.',
  'SOC_SELECTION-MASTER_LABEL': ' Activation of this tariff option requires the booking of another additional option for {{length}} subscriber.',
  'SOC_SELECTION-MONTHS': 'Month(s)',
  'SOC_SELECTION-MULTI_SUBSCRIBERS_ELIGIBLE': '{{length}} of {{totalLength}} Participants already have this setting',
  'SOC_SELECTION-NEXT_BUTTON': 'Continue to the customer',
  'SOC_SELECTION-NONE_SELECTED': 'No tariff option selected',
  'SOC_SELECTION-NOTE': '<b>Please note:</b>',
  'SOC_SELECTION-NO_AVAILABLE_SOCS': 'Socs are not available for the selected Subscribers. It could also be possible that there are no SOCs available in your shop, Please contact Administrator.',
  'SOC_SELECTION-NO_SOCS': 'Socs not available for selected subscribers',
  'SOC_SELECTION-PLANNED_CHANGES': 'Planned changes',
  'SOC_SELECTION-SEARCH': 'Search',
  'SOC_SELECTION-SETUP_FEE': 'Setup Fee¹',
  'SOC_SELECTION-SHOW_DESCRIPTION': 'Show description',
  'SOC_SELECTION-SINGLE_SUBSCRIBER_ELIGIBLE': '{{length}} von {{totalLength}} Participant already have this setting',
  'SOC_SELECTION-STANDARD_BASE_PRICE_MSG': '¹Standard base price; the final price may vary per participant and will be displayed in the "Order overview" step.',
  'SOC_SELECTION-SUBTITLE_MSG': 'Please change the tariff options of the selected participants according to your wishes.<br/>Basic prices may vary depending on the participant and the framework contract.',
  'SOC_SELECTION-SUB_TITLE_MSG': 'Please choose tariff options. Please note that the combination of tariff and terminal may result in certain pre-set mandatory tariff options. Optional fare options can be booked.',
  'SOC_SELECTION-SUMMARY_TEXT': 'Selected Tarif options:',
  'SOC_SELECTION-TARIFF_BOOKED_POST_MSG': ' subscriber.',
  'SOC_SELECTION-TARIFF_BOOKED_PRE_MSG': 'You booked this tariff option for',
  'SOC_SELECTION-TERMINATION_DATE': 'Expiration Date: ',
  'SOC_SELECTION-TITLE': 'Select tariff options',
  'SOC_SELECTION-WIFI_NOTE_MSG': "WiFi calling must be supported by your smartphone.<br/>Here's a <b> <a href={{url}} target='_blank'> list of supported smartphones. </a> </b> <br/>This fare option is not bookable for participants with an UltraCard."
};
