module.exports = {
 'REVIEW-ARTICLE_NUMBER': 'item number : {{articleNumber}}',
'REVIEW-COL_MONTHLY': 'Per month',
'REVIEW-COL_ONE_TIME': 'unique',
'REVIEW-COL_QUANTITY': 'amount',
'REVIEW-COST_TITLE': 'Cost overview',
'REVIEW-COST_TOTAL': 'total amount',
'REVIEW-COST_TOTAL_INC_VAT': 'Total amount (incl. VAT.)',
'REVIEW-COST_VAT':	'Taxes (19%)',
'REVIEW-DEP':	'Device Enrollment Program(DEP)',
'REVIEW-DEP-KUNDEN-ID':	'DEP-Customer-ID:',
'REVIEW-DEP-LIEFERANT':	'DEP-Supplier:',
'REVIEW-HARDWARE_TITLE':	'Hardware',
'REVIEW-POPOVER_CUSTOMER_INITIAL_NUMBER': 'Here you can enter an additional order reference for internal purposes.constructor.',
'REVIEW-POPOVER_CUSTOMER_ORDER_NUMBER': 'Here you can enter your own order reference. This will be printed under "Your order number" on the invoice.',
'REVIEW-POPOVER_CUSTOMER_VOID': 'You can save up to 5 VO-IDs for future orders.',
'REVIEW-SAVE_CART':	'Save shopping cart',
'REVIEW-SOC_TITLE': 'Tarif options',
'REVIEW-SUBMIT_YOUR_REQUEST': 'Submit your request',
'REVIEW-SUB_TITLE_MSG':	'Please check your changes in the last step. If everything is correct, please click on the button "send order".',
'REVIEW-TARIFF_TITLE': 'Tariff',
'REVIEW-TITLE':	'Order overview',
  'CT-REVIEW-TITLE':'Order Review',
  'CT-REVIEW-SUB_TITLE_MSG':'Please check the data below and then click on "Send order" to confirm the tariff change. Please note: A tariff change to a tariff with a lower monthly base price will be charged with a one-time fee of 39.95 € net. Your bill will show this tariff change as a downgrade. Tariff change downgrades are possible for the first time after 12 months of contract duration.',
  'CT-REVIEW-COL_QUANTITY':'Quantity',
  'CT-REVIEW-COL_MONTHLY':'Monthly',
  'CT-REVIEW-COL_ONE_TIME':'One time',
  'CT-REVIEW-SUBMIT_YOUR_REQUEST':'Submit Order',
  'CT-REVIEW-COST_TITLE':'Pricing Details',
  'CT-REVIEW-COST_TOTAL':'Total',
  'CT-REVIEW-COST_VAT':'VAT (19%)',
  'CT-REVIEW-COST_TOTAL_INC_VAT':'Total (Including VAT)',
  'CT-REVIEW-TARIFF_TITLE':'Tariff',
  'CT-REVIEW-SAVE_CART':'Shopping Cart'
};