module.exports = {
  "4_DISPLAY_NOTE": "Change of customer number data:",
  "5_DISPLAY_NOTE": "Change of payment information:",
  "BAN-CHANGES_FOUND": "planned changes found",
  "BAN-NO_CHANGES_FOUND": "No scheduled changes found",
  "BAN-ONE_CHANGE_FOUND": "Found a planned change",
  "BAN_UPDATE-CONFIRM-CHG_DATA": "Change of customer number data:",
  "BAN_UPDATE-CONFIRM-DESC": "Please note that the information will be updated until the following day. We kindly ask you to submit further orders for this customer number only after the completion of the update.",
  "MANAGE_DETAILS-ADDRESS-POBOX": "P.O. Box",
  "MANAGE_DETAILS-ADDRESS-STATE": "Street, House number",
  "MANAGE_DETAILS-ASYNC_PAYFIELDS_ERROR_MESSAGE": "Please wait for async validation to complete.",
  "MANAGE_DETAILS-BANS_WERE_CHANGED": "{{selectCount}} customer numbers have been changed",
  "MANAGE_DETAILS-BULK_EDIT_HEADER": "Here you can manage the selected participants uniformly. Uniform means that a value is applied to all selected participants.",
  "MANAGE_DETAILS-CHOOSE": "Choose",
  "MANAGE_DETAILS-CONTINUE_TO_ORDER_OVERVIEW": "Continue to the order overview",
  "MANAGE_DETAILS-EDIT_INFO_MESSAGE": "Here you can make changes to the customer numbers selected in the first step. Each line represents a customer number and you can change individual values in the corresponding fields.",
  "MANAGE_DETAILS-ERROR_DESCRIPTION": "Please check the marked errors and resubmit the form after correction.",
  "MANAGE_DETAILS-ERROR_TITLE": "Sorry, an error has occurred",
  "MANAGE_DETAILS-NAME_FORMAT-COMPANY": "Company",
  "MANAGE_DETAILS-NAME_FORMAT-PERSON": "Person",
  "MANAGE_DETAILS-NO_CHANGE_INFO": "No changes were made",
  "MANAGE_DETAILS-ONE_BAN_CHANGED": "One customer number has been changed",
  "MANAGE_DETAILS-PERSON_TITLES-DR": "Dr.",
  "MANAGE_DETAILS-PERSON_TITLES-PROF": "Prof.",
  "MANAGE_DETAILS-SALUTATION": "Salutation",
  "MANAGE_DETAILS-SALUTATIONS-COMPANY": "Company",
  "MANAGE_DETAILS-SALUTATIONS-MR": "Sir",
  "MANAGE_DETAILS-SALUTATIONS-MRS": "Mrs",
  "MANAGE_DETAILS-SALUTATIONS-NO_SALUTATION": "No salutation",
  "MANAGE_DETAILS-SINGLE_EDIT_HEADER": "Here you can manage the participants you have selected",
  "MANAGE_DETAILS-TITLE": "Manage customer numbers",
  "MANAGE_DETAILS_TABLE-NO_RESULT_FOUND": "No customer numbers found",
  "MANAGE_DETAILS_TABLE-ONE_RESULT_FOUND": "One  customer number found",
  "MANAGE_DETAILS_TABLE-RESULT_PER_PAGE": "Results per page",
  "MANAGE_DETAILS_TABLE-TOTAL_RESULT_FOUND": "{{selectCount}} customer numbers found",
  "ORDER_CONFIRM-DESCRIPTION": "Please note that the information will be updated until the following day. We would like to ask you to submit further orders for this number (s) only after the completion of the update.",
  "ORDER_CONFIRMATION": "Order confirmation",
  "ORDER_CONSISTS": "Your order consists of the following parts:",
  "PAGE_TITLE": "Manage customer numbers",
  "RECEVIED_SUCESS_MSG": "Your order has been successfully received and is currently being processed.",
  "REVIEW-BULK_EDIT_INFO_MESSAGE": "<h3> For Your Information </ h3> The changes listed below are for {{selectCount}} customer numbers. Details about the participants affected by the changes can be found in the first step \"Selecting a customer number\".",
  "REVIEW-COLUMN_BAN_NUMBER": "Customer number",
  "REVIEW-COLUMN_FIELD": "Changed field",
  "REVIEW-COLUMN_OLD_VALUE": "New value",
  "REVIEW-COLUMN_PREVIOUS_VALUE": "Previous value",
  "REVIEW-READ_ONLY_ERROR_MESSAGE": "Readonly user can not submit the order",
  "REVIEW-SUBMIT_YOUR_REQUEST": "Submit your order",
  "REVIEW-TITLE": "Order overview",
  "REVIEW_TABLE-NO_RESULT_FOUND": "No scheduled changes found",
  "REVIEW_TABLE-ONE_RESULT_FOUND": "One scheduled change found",
  "REVIEW_TABLE-RESULT_PER_PAGE": "Results per page",
  "REVIEW_TABLE-TOTAL_RESULT_FOUND": "Submit your order",
  "SELECTION-BANS_WERE_SELECTED": "{{selectCount}} customer numbers have been selected",
  "SELECTION-CONTINUE_TO_NEXT": "Manage customer number",
  "SELECTION-DOWNLOAD_BUTTON": "Download file",
  "SELECTION-DOWNLOAD_FAIL_ERROR_MESSAGE": "<p> <b> Sorry, an error occurred </ b> </ p>",
  "SELECTION-NO_PARTICIPANTS_SELECTED": "No subscribers were selected",
  "SELECTION-ONE_BAN_SELECTED": "One customer number has been selected",
  "SELECTION-SELECTION_MESSAGE": "Please select the customer numbers whose data you would like to manage. You may also like to upload an Excel spreadsheet for the selection.",
  "SELECTION-TITLE": "Select customer number",
  "SELECTION_TABLE-ALL_DATA_SELECTED": "All customer number selected",
  "SELECTION_TABLE-NONE_SELECTED": "No customer number selected",
  "SELECTION_TABLE-NO_RESULT_FOUND": "No customer number found",
  "SELECTION_TABLE-ONE_DATA_SELECTED": "One customer number selected",
  "SELECTION_TABLE-ONE_RESULT_FOUND": "One customer number found",
  "SELECTION_TABLE-RESULT_PER_PAGE": "Results per page",
  "SELECTION_TABLE-SELECTED_DATA_COUNT": "{{selectCount}} customer numbers selected",
  "SELECTION_TABLE-TOTAL_RESULT_FOUND": "{{selectCount}} customer numbers found",
  "THANK_YOU_FOR_YOUR_ORDER": "Thank you for your order."
};
