module.exports = {
  "2_DISPLAY_NOTE": "Change of subscriber data:",
  "3_DISPLAY_NOTE": "Change of internal code and / or password:",
  "COMMON-CHANGE-LINK": "Change To",
  "DD_SELECT_COMPANY": "Company",
  "DD_SELECT_MRS": "Mrs",
  "DD_SELECT_NO_SALUTATION": "No salutation",
  "DD_SELECT_SIR": "Sir",
  "ERROR_TECHNICAL-ERR": "<b> Temporary technical malfunction </ b> <p> </ p> Due to a system malfunction, the desired website is currently not available. Please try again later. <P> </ p> Best regards, Your Vodafone Team",
  "MANAGE_DETAILS-ADDRESS-POBOX": "P.O. Box",
  "MANAGE_DETAILS-ADDRESS-STATE": "Street, House number",
  "MANAGE_DETAILS-BULK_EDIT_HEADER": "Here you can manage the selected subscribers uniformly. Uniform means that a value is applied to all selected subscribers.",
  "MANAGE_DETAILS-CHOOSE": "Select",
  "MANAGE_DETAILS-CONTINUE_TO_ORDER_OVERVIEW": "Continue to order overview",
  "MANAGE_DETAILS-EDIT_INFO_MESSAGE": "Here you can make<p> changes for the subscribers selected in the first step. Each line represents a subscriber and you can change </p>individual <i>values</i> in the corresponding fields.",
  "MANAGE_DETAILS-ERROR_DESCRIPTION": "Please check the marked errors and resubmit the form after correction.",
  "MANAGE_DETAILS-ERROR_TITLE": "Sorry, an error has occurred",
  "MANAGE_DETAILS-NAME_FORMAT-COMPANY": "Company",
  "MANAGE_DETAILS-NAME_FORMAT-PERSON": "Person",
  "MANAGE_DETAILS-NO_CHANGE_INFO": "No changes were made",
  "MANAGE_DETAILS-ONE_SUB_CHANGED": "One subscriber has been changed",
  "ACTIVATION_DETAILS-NO-SUBS-CHANGED": "No participants were changed",
  "MANAGE_DETAILS-PERSON_TITLES-DR": "Dr.",
  "MANAGE_DETAILS-PERSON_TITLES-PROF": "Prof.",
  "MANAGE_DETAILS-SALUTATION": "Salutation",
  "MANAGE_DETAILS-SALUTATIONS-COMPANY": "Company",
  "MANAGE_DETAILS-SALUTATIONS-MR": "Sir",
  "MANAGE_DETAILS-SALUTATIONS-MRS": "Mrs",
  "MANAGE_DETAILS-SALUTATIONS-NO_SALUTATION": "No salutation",
  "MANAGE_DETAILS-SINGLE_EDIT_HEADER": "Here you can manage the selected subscribers",
  "MANAGE_DETAILS-SUBSCRIBERS_WERE_CHANGED": "{{selectCount}} subscribers have been changed",
  "MANAGE_DETAILS-TITLE": "Manage subscribers",
  "ORDER_CONFIRM-DESCRIPTION": "Please note that the information will be updated until the following day. We kindly ask you to submit further orders for this customer number only after the completion of the update.",
  "ORDER_CONFIRMATION": "Order confirmation",
  "ORDER_CONSISTS": "Your order consists of the following parts:",
  "PAGE_TITLE": "Subscriber management",
  "RECEVIED_SUCESS_MSG": "Your order has been successfully received and is currently being processed.",
  "REVIEW-BULK_EDIT_INFO_MESSAGE": "<h3> For Your Information </ h3> The changes listed below affect {{selectCount}} subscribers. Details about the subscribers affected by the changes can be found in the first step \"Selecting subscribers\".",
  "REVIEW-COLUMN_BAN_NUMBER": "Customer Number",
  "REVIEW-COLUMN_FIELD": "Changed Field",
  "REVIEW-COLUMN_OLD_VALUE": "New Value",
  "REVIEW-COLUMN_PREVIOUS_VALUE": "Previous Value",
  "REVIEW-COLUMN_SUBS_NUMBER": "Telephone Number",
  "REVIEW-DELETE_CART": "Clear cart",
  "REVIEW-EMPTY_MSG": "No data was found",
  "REVIEW-NO_PERMISSION_TO_SAVE_CART": "No permission to save the cart",
  "REVIEW-READ_ONLY_ERROR_MESSAGE": "Readonly user can not submit the order",
  "REVIEW-SAVE_CART": "Save shopping cart",
  "REVIEW-SUBMIT_YOUR_REQUEST": "Submit your order",
  "REVIEW-TITLE": "Order overview",
  "SELECTION-CONTINUE_TO_NEXT": "Manage subscribers",
  "SELECTION-DOWNLOAD_BUTTON": "Download file",
  "SELECTION-DOWNLOAD_FAIL_ERROR_MESSAGE": "<p> <b> Sorry, an error occurred </ b> </ p>",
  "SELECTION-MANAGE_UPLOAD": "Upload change selected",
  "SELECTION-NO_PARTICIPANTS_SELECTED": "No subscribers were selected",
  "SELECTION-ONE_SUBS_SELECTED": "One subscriber was selected",
  "SELECTION-SELECTION_MESSAGE": "Please select the subscribers whose tariff options you would like to manage. You may also like to upload an Excel spreadsheet for the selection.",
  "SELECTION-SUBSCRIBERS_WERE_SELECTED": "{{selectCount}} subscribers were selected",
  "SELECTION-TITLE": "Select subscriber",
  "SELECTION-UPLOAD_BUTTON": "Upload changes",
  "SUB-CHANGES_FOUND": "Planned changes found",
  "SUB-NO_CHANGES_FOUND": "No scheduled changes found",
  "SUB-ONE_CHANGE_FOUND": "One planned change found",
  "SUBS_UPDATE-CONFIRM-CHG_DATA": "Change of subscriber data:",
  "SubscriberUpdateInfoBundle.SaveError": "Due to an internal error, your changes could not be saved.",
  "THANK_YOU_FOR_YOUR_ORDER": "Thank you for your order.",
  "UPLOAD_CHANGES-CANCEL_UPLOAD_BUTTON": "Cancel and upload new file",
  "UPLOAD_CHANGES-DESCRIPTION": "Uploaded file contains some ivalid records. How to proceed Download the excel file with those invalid records, below \"To order overview\" to proceed with the order or cancel the icon to upload a new file.",
  "UPLOAD_CHANGES-DOWNLOAD_BUTTON": "Download invalid records as Excel file",
  "UPLOAD_CHANGES-DRAG_DROP_DESC_1": "Drag and drop your data file into this area",
  "UPLOAD_CHANGES-DRAG_DROP_DESC_1_NON_DATA": "Drag and drop your file into this area",
  "UPLOAD_CHANGES-DRAG_DROP_DESC_12": "or click ",
  "UPLOAD_CHANGES-DRAG_DROP_DESC_2": "here",
  "UPLOAD_CHANGES-DRAG_DROP_DESC_3": "to select a file",
  "UPLOAD_CHANGES-DRAG_DROP_REUPLOAD_DESC": "<b> Drag and drop your corrected file into this area </ b> <br/> or click",
  "UPLOAD_CHANGES-ERROR_INAVLIDFILE": "File type or format is not supported. Please use the file offered for download on the previous page.",
  "UPLOAD_CHANGES-ERROR_INFO": "<p> <b> Sorry, an error occurred </ b> </ p>",
  "UPLOAD_CHANGES-FORMAT_DESC": "SUPPORTED FORMAT",
  "UPLOAD_CHANGES-FORMAT_DESC1": "XLSX",
  "UPLOAD_CHANGES-INVALID_RECORD": "Uploaded subscriber is invalid.",
  "UPLOAD_CHANGES-INVALID_RECORDS": "<p> <b> {{invalidRecords}} Uploaded subscribers are invalid </ b> </ p>",
  "UPLOAD_CHANGES-PARTIAL_VALID_RECORDS": "<p> <b> {{validRecords}} Subscribers uploaded successfully </ b> </ p>",
  "UPLOAD_CHANGES-VALID_RECORDS": "<p> <b> You have successfully uploaded {{validRecords}} subscribers </ b> </ p>",
  "SUB-ONE-NEW-SIM": "Order a new SIM card",
  "SUB-MULTI-NEW-SIM": "Order new SIM cards",
  "SUB-ONE-EXISTING-SIM": "Activate the existing SIM card number",
  "SUB-MULTI-EXISTING-SIM": "Activate existing SIM card numbers"
};
