module.exports = {
  "DATATABLE-FILTER-PLACEHOLDER": "filter",
  "DATATABLE-ADVANCED-FILTER-PLACEHOLDER": "Extended filter",
  "DATATABLE-COLUMN_SELECT-NOT_HIDDEN": "Editable field can not be hidden",
  "DATATABLE-COLUMN_SELECT-PLACEHOLDER": "Search",
  "DATATABLE-COLUMN_SELECT-TITLE": "View Options",
  "DATATABLE-CSV_DOWNLOAD": "Export as CSV",
  "DATATABLE-CUST_ORDER_INFO": "Customer Order Information",
  "DATATABLE-EMPTY_MESSAGE": "No results found",
  "DATATABLE-FILTER-BUTTON-FILTER": "Set Filter",
  "DATATABLE-FILTER-BUTTON-RESET": "Reset to Default",
  "DATATABLE-FILTER-COMPARATOR-AND": "and",
  "DATATABLE-FILTER-COMPARATOR-CONTAINS": "contains",
  "DATATABLE-FILTER-COMPARATOR-EMPTY": "empty",
  "DATATABLE-FILTER-COMPARATOR-EQUAL": "equal",
  "DATATABLE-FILTER-COMPARATOR-GT": "bigger than",
  "DATATABLE-FILTER-COMPARATOR-GTE": "greater than or equal",
  "DATATABLE-FILTER-COMPARATOR-LT": "less than",
  "DATATABLE-FILTER-COMPARATOR-LTE": "less than or equal",
  "DATATABLE-FILTER-COMPARATOR-NOT_CONTAINS": "does not contain",
  "DATATABLE-FILTER-COMPARATOR-NOT_EMPTY": "not empty",
  "DATATABLE-FILTER-COMPARATOR-NOT_EQUAL": "not equal",
  "DATATABLE-FILTER-COMPARATOR-OR": "or",
  "DATATABLE-FILTER-PLACEHOLDER-DATE": "dd.mm.yyyy",
  "DATATABLE-FILTER-PLACEHOLDER-KEYWORD": "Keyword",
  "DATATABLE-FILTER-TITLE": "Filter by {{title}}:",
  "DATATABLE-INTERNAL_ORDER_NO": "Internal Order Number",
  "DATATABLE-MAX-SELECT-COUNT-MSG":"You can select maximum up to {{maxCount}} rows. Please uncheck some records to select another.",
  "DATATABLE-NO_FIELDS": "No available field selected",
  "DATATABLE-PAGINATOR-RESULTS": "Results per page:",
  "DATATABLE-POPUP-CANCEL": "Cancel",
  "DATATABLE-POPUP-DELETE": "Clear",
  "DATATABLE-RESULT_COUNT-NONE": "No results found",
  "DATATABLE-RESULT_COUNT-ONE": "One result found",
  "DATATABLE-RESULT_COUNT-OTHER": "{{resultCount}} results found",
  "DATATABLE-SELECTION_COUNT-ALL": "All results selected",
  "DATATABLE-SELECTION_COUNT-NONE": "No results selected",
  "DATATABLE-SELECTION_COUNT-ONE": "One result selected",
  "DATATABLE-SELECTION_COUNT-OTHER": "{{selectCount}} results selected",
  "DATATABLE-SELECTION_TITLE": "Select",
  "DATATABLE-VO_ID": "VO-ID",
  "DEBITOR-DATATABLE-EMPTY_MESSAGE": "There are no debtors available. Please enter a new customer.",
  "ED-ORDER-DETAILS-DATATABLE-EMPTY_MESSAGE": "No documents currently attached to order",
  "ORDER_CONFIRMATION": "Order confirmation",
  "SELECTION-TOOLTIP-INTERNAL_CODE": "Internal code (customer reference; Ident for Customer)",
  "SHIPMENT-DATATABLE-EMPTY_MESSAGE": "There are no delivery addresses available. Please create a new delivery address.",
  "THANK_YOU_FOR_YOUR_ORDER": "Thank you for your order."
};
