module.exports = {
  'DATA': 'Data Tariffs',
  'SIM_ONLY_DATA': 'Data tariffs SIM Only',
  'SIM_ONLY_VOICE': 'Sprachtarife SIM Only',
  'TARIFF_CATEGORY': 'Category',
  'TARIFF_FAMILY': 'Family',
  'TARIFF_NOT_AVAILABLE': 'Tariffs not available for selected subscribers',
  'TARIFF_SELECTION-BILL_NEXTCYCLE': 'To the next billing period',
  'TARIFF_SELECTION-BILL_TODAY': 'Immediately',
  'TARIFF_SELECTION-COLUMN_NAME_PRICE': 'Price',
  'TARIFF_SELECTION-COLUMN_NAME_TARIFF': 'Tariff',
  'TARIFF_SELECTION-CONTINUE_WITH_SAME': 'I want to keep my existing tariff',
  'TARIFF_SELECTION-ELIGIBLE_SUBS': '{{count}} Participants are eligible for this tariff',
  'TARIFF_SELECTION-IN_ELIGIBLE_SUBS_TEXT1': 'A change to this tariff is not possible for {{count}} subscribers. Click ',
  'TARIFF_SELECTION-IN_ELIGIBLE_SUBS_TEXT2': 'here',
  'TARIFF_SELECTION-IN_ELIGIBLE_SUBS_TEXT3': ' to download these as XLSX',
  'TARIFF_SELECTION-NEXT_BUTTON': 'Next to the hardware',
  'TARIFF_SELECTION-NO_ELIGIBLE_SUBS': 'No participant is eligible for this tariff',
  'TARIFF_SELECTION-PER_MONTH': 'Per month',
  'TARIFF_SELECTION-RESULTS_FOUND': '{{count}} Result found',
  'TARIFF_SELECTION-SELECT_NEW': 'I would like to choose a new tariff',
  'TARIFF_SELECTION-SELECT_NEW_TARIFF_MSG': 'Here you will see your framework contract specific rates. Please choose your desired tariff.',
  'TARIFF_SELECTION-SELECT_OPTION_WARNING': 'Please select an option',
  'TARIFF_SELECTION-SELECT_TARIFF': 'Choose',
  'TARIFF_SELECTION-SELECT_TARIFF_ERR_MSG': 'No selected Subscribers are eligible for the selected Tariff. Please choose a different Tariff where at least 1 Subscriber is indicated as eligible to proceed.',
  'TARIFF_SELECTION-SELECT_WARNING': 'Please choose a tariff.',
  'TARIFF_SELECTION-SHOW_ALL_TARIFFS': 'Show all rates',
  'TARIFF_SELECTION-SUB_TITLE_MSG': 'Please select an option',
  'TARIFF_SELECTION-SUMMARY_INFO_TEXT': '{{subsQuantity}} subscribers have already this tariff AND will not require a tariff change',
  'TARIFF_SELECTION-SUMMARY_NO_CHANGE_TEXT': 'keep existing tariff',
  'TARIFF_SELECTION-SUMMARY_TEXT': 'Selected tariff:',
  'TARIFF_SELECTION-TARIFF_DETAILS': 'Tariffdetails',
  'TARIFF_SELECTION-TARIFF_SELECTED': 'Selected fare',
  'TARIFF_SELECTION-TITLE': 'Select tariff',
  'TARIFF_SELECTION-WITHOUT_SMARTPHONE':'Without a Smartphone',
  'VOICE': 'Voice Tariffs',
  'CT-TARIFF_SELECTION-TITLE':'Tariff Selection',
  'CT-TARIFF_SELECTION-CONTINUE_TO_ORDER_REVIEW':'Continue to order overview',
  'CT-TARIFF_SELECTION-SUMMARY_TEXT':'Selected Tariff:',
  'CT-TARIFF_SELECTION-SUB_TITLE_MSG':'Please select the tariff you would like to change to',
  'CT-TARIFF_SELECTION-SELECT_NEW_TARIFF_MSG':'Please select the tariff you would like to change to',
  'CT-TARIFF_NOT_AVAILABLE':"<p class=\"alertTitle\">Error, issue identified.!</p><p class=\"messageText\">At the moment no tariffs are available for a tariff change. Please contact your shop administrator.</p>",
  'CT-TARIFF_SELECTION-ELIGIBLE_SUBS':"{{count}} Subscribers are available for this tariff",
  'CT-TARIFF_SELECTION-IN_ELIGIBLE_SUBS_TEXT1': 'A change to this tariff is not possible for {{count}} subscribers. Click ',
  'CT-TARIFF_SELECTION-IN_ELIGIBLE_SUBS_TEXT2': 'here',
  'CT-TARIFF_SELECTION-IN_ELIGIBLE_SUBS_TEXT3': ' to download these as XLSX',
  'CT-TARIFF_SELECTION-NO_ELIGIBLE_SUBS':'No Subscriber is available for this tariff',
  'CT-TARIFF_SELECTION-RESULTS_FOUND':"{{count}} Records found",
  'CT-TARIFF_SELECTION-TARIFF_DETAILS':'Tariff details',
  'CT-TARIFF_SELECTION-TARIFF_SELECTED':'Selected Tariff',
  'CT-TARIFF_SELECTION-SELECT_TARIFF':'Select',
  'CT-TARIFF_SELECTION-SELECT_WARNING':"<p class=\"alertTitle\">Error, issue identified!</p><p class=\"messageText\">No Tariff selected.</p>"

};
