module.exports = [
    {
        "addressId": "05002159-c0a8-4dba-437f-9d473cd81bba",
        "name1": "new techfund debitor",
        "name2": "k2",
        "name3": "k3",
        "name4": "k4",
        "country": "Deutschland",
        "city": "Berlin",
        "houseNumber": "545435",
        "postalCode": "5434534",
        "streetName": "street",
        "debitorNumber": "250915",
        "debitorType": "T",
        "debitorId": "20942112-7739-0687-e053-424c070adfa8",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "addressId": "410e9b6a-c0a8-4dba-5239-3809314b7904",
        "name1": "Standard Debitor A",
        "name2": "Standard Debitor B",
        "name3": "Standard Debitor C",
        "name4": "Standard Debitor 5",
        "country": "Slowakische Republik",
        "poBox": "34345234",
        "city": "Standard Debitor Town",
        "postalCode": "6987987",
        "debitorNumber": "995577",
        "debitorType": "D",
        "debitorId": "294ebe2e-6b9f-2099-e053-424c070a9081",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "country": "Deutschland",
        "debitorNumber": "881112",
        "debitorType": "T",
        "debitorId": "2a2a3ef1-6795-52a3-e053-424c070a9924",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "country": "Deutschland",
        "debitorNumber": "220416",
        "debitorType": "D",
        "debitorId": "3113dd53-0034-096d-e053-404c070a0330",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "addressId": "1844b7fd-c0a8-4dba-437f-9d47462e53e5",
        "name1": "techfund debitor 1",
        "name2": "TECHFUND DEBITOR 2",
        "country": "Deutschland",
        "city": "Berlin",
        "houseNumber": "543",
        "postalCode": "6436436",
        "streetName": "techfund debitor street",
        "debitorNumber": "000003",
        "debitorType": "T",
        "debitorId": "20dfd743-49e1-2d26-e053-404c070ad1d0",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
      "country": "Deutschland",
      "debitorNumber": "987868",
      "debitorType": "T",
      "debitorId": "3640b7fa-0da1-3730-e053-404c070af7cf",
      "vodafoneUser": true,
      "modified": false,
      "associated": true,
      "badDebitorInformation": false,
      "default": false,
      "readOnly": false
    },
    {
        "addressId": "0beae407-c0a8-4da9-6e94-bd5f5c6ee1a3",
        "name1": "sdcsdc",
        "country": "Deutschland",
        "city": "vfdvfdfd",
        "houseNumber": "sdfvvd",
        "postalCode": "434343",
        "streetName": "43344",
        "debitorNumber": "444333",
        "debitorType": "D",
        "debitorId": "5f2f9595-bf7c-12c8-e053-424c070a1b45",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "addressId": "9afc17ee-c0a8-4dba-772d-e6bc86834e62",
        "name1": "Standnmae1",
        "name2": "Standnmae2",
        "name3": "Standnmae3",
        "name4": "Standnmae4",
        "country": "Belgien",
        "city": "city",
        "houseNumber": "432",
        "postalCode": "43211",
        "streetName": "street",
        "debitorNumber": "554332",
        "debitorType": "D",
        "debitorId": "9afc17ed-c0a8-4dba-772d-e6bc605c09ae",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "addressId": "50ac5caf-c0a8-4da3-1860-3b7c1a62b318",
        "name1": "Kundenname1",
        "name2": "Kundenname2",
        "country": "Deutschland",
        "city": "City",
        "houseNumber": "55",
        "postalCode": "12387",
        "streetName": "Street",
        "debitorNumber": "567899",
        "debitorType": "D",
        "debitorId": "f0dc9bf2-0a00-4b01-2725-c3c6a2ef776a",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "addressId": "ce82e635-c0a8-4dba-71d9-e2fe484716d4",
        "name1": "k1",
        "name2": "k2",
        "name3": "k3",
        "country": "Deutschland",
        "city": "berlin",
        "houseNumber": "4343",
        "postalCode": "4324324",
        "streetName": "streer",
        "debitorNumber": "150116",
        "debitorType": "T",
        "debitorId": "296255bb-bce9-3f32-e053-404c070a545f",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "country": "Deutschland",
        "debitorNumber": "362514",
        "debitorType": "T",
        "debitorId": "2a50f8de-3df6-2603-e053-404c070a6175",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "country": "Deutschland",
        "debitorNumber": "432432",
        "debitorType": "T",
        "debitorId": "4d85acfa-c2c3-5a2c-e053-404c070aac95",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "addressId": "50ac5caf-c0a8-4da3-1860-3b7c1a62b318",
        "name1": "Kundenname1",
        "name2": "Kundenname2",
        "country": "Deutschland",
        "city": "City",
        "houseNumber": "55",
        "postalCode": "12387",
        "streetName": "Street",
        "debitorNumber": "789765",
        "debitorType": "D",
        "debitorId": "f0c74076-0a00-4b01-2725-c3c61a5d8101",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "addressId": "80a39264-c0a8-4da8-7e82-8f0cc450395f",
        "name1": "testt",
        "name2": "tt",
        "country": "Deutschland",
        "city": "fdsf",
        "houseNumber": "34",
        "postalCode": "32222",
        "streetName": "ttttt",
        "debitorNumber": "145678",
        "debitorType": "T",
        "debitorId": "80a39263-c0a8-4da8-7e82-8f0c441bde6f",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "addressId": "0bf5405e-c0a8-4da9-6e94-bd5f71c066b5",
        "name1": "dcdscdc",
        "country": "Deutschland",
        "city": "cdcdcs",
        "houseNumber": "cdscds",
        "postalCode": "323232",
        "streetName": "232332",
        "debitorNumber": "222333",
        "debitorType": "D",
        "debitorId": "5f2f732d-07e0-0f00-e053-424c070aeef8",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "addressId": "5579db0b-0a00-4b01-4f55-8c7911eb2e7d",
        "name1": "Sunitha",
        "name2": "H",
        "name3": "Srinivas",
        "name4": "naveen",
        "country": "Deutschland",
        "city": "street1",
        "houseNumber": "5653",
        "postalCode": "44433",
        "streetName": "Perfecttesta",
        "debitorNumber": "123456",
        "debitorType": "D",
        "debitorId": "eb6a4df9-0a00-4b01-637b-a766a11c32ba",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "addressId": "50ac5caf-c0a8-4da3-1860-3b7c1a62b318",
        "name1": "Kundenname1",
        "name2": "Kundenname2",
        "country": "Deutschland",
        "city": "City",
        "houseNumber": "55",
        "postalCode": "12387",
        "streetName": "Street",
        "debitorNumber": "555556",
        "debitorType": "D",
        "debitorId": "f0e6155a-0a00-4b01-2725-c3c643814d5f",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "addressId": "3fb906f6-c0a8-4dba-5239-3809c549084f",
        "name1": "New Techfund Debitor k1",
        "name2": "New Techfund Debitor k2",
        "name3": "New Techfund Debitor k3",
        "name4": "New Techfund Debitor k4",
        "country": "Deutschland",
        "poBox": "1478520369",
        "city": "Berlin",
        "postalCode": "45345345",
        "debitorNumber": "140116",
        "debitorType": "T",
        "debitorId": "294a6d34-eea8-430a-e053-424c070ab208",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "addressId": "44fe44ad-c0a8-4dba-5239-38090373ab25",
        "name1": "bob new free org",
        "country": "Deutschland",
        "city": "bob stadt",
        "houseNumber": "23",
        "postalCode": "12345",
        "streetName": "bob new free org dbtr",
        "debitorNumber": "112244",
        "debitorType": "D",
        "debitorId": "295e9464-0523-141b-e053-404c070a691b",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "addressId": "401d79eb-c0a8-4dba-5239-380994f12729",
        "name1": "TF New 1",
        "name2": "TF New 2",
        "name3": "TF New 3",
        "name4": "TF New 4",
        "country": "Deutschland",
        "city": "TF New Town",
        "houseNumber": "54654654",
        "postalCode": "54654654",
        "streetName": "TF New Street",
        "debitorNumber": "850602",
        "debitorType": "T",
        "debitorId": "294bb642-c5cf-4ed5-e053-424c070a70a4",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "country": "Deutschland",
        "debitorNumber": "160607",
        "debitorType": "D",
        "debitorId": "34b1f820-ccfa-1a42-e053-404c070ae628",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "country": "Deutschland",
        "debitorNumber": "030498",
        "debitorType": "T",
        "debitorId": "3d64ba4c-b892-2feb-e053-404c070af9d2",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "country": "Deutschland",
        "debitorNumber": "789023",
        "debitorType": "T",
        "debitorId": "3d664891-15f0-1cdc-e053-424c070addbf",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "addressId": "50ac5caf-c0a8-4da3-1860-3b7c1a62b318",
        "name1": "Kundenname1",
        "name2": "Kundenname2",
        "country": "Deutschland",
        "city": "City",
        "houseNumber": "55",
        "postalCode": "12387",
        "streetName": "Street",
        "debitorNumber": "567891",
        "debitorType": "D",
        "debitorId": "f0de4663-0a00-4b01-2725-c3c62b9dc276",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "addressId": "50ac5caf-c0a8-4da3-1860-3b7c1a62b318",
        "name1": "Kundenname1",
        "name2": "Kundenname2",
        "country": "Deutschland",
        "city": "City",
        "houseNumber": "55",
        "postalCode": "12387",
        "streetName": "Street",
        "debitorNumber": "11223344",
        "debitorType": "D",
        "debitorId": "1dd4303f-b014-5450-e053-404c070a5a19",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "addressId": "14aaf042-c0a8-4dba-437f-9d471be0090c",
        "name1": "techfund debitor",
        "name2": "TECHFUND DEBITOR 2",
        "name3": "k3",
        "name4": "k4",
        "country": "Deutschland",
        "city": "Bonn",
        "houseNumber": "465",
        "postalCode": "6436436",
        "streetName": "techfund debitor",
        "debitorNumber": "000002",
        "debitorType": "T",
        "debitorId": "20df6705-8d93-3986-e053-404c070a52dd",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "addressId": "28709a15-c0a8-4dba-6387-c7b9da65cfdb",
        "name1": "techfund k1",
        "name2": "k2",
        "name3": "k3",
        "name4": "k4",
        "country": "Deutschland",
        "city": "berlin",
        "houseNumber": "55345",
        "postalCode": "54354353",
        "streetName": "street",
        "debitorNumber": "151002",
        "debitorType": "T",
        "debitorId": "211f025c-d15f-6c88-e053-424c070a28ec",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "country": "Deutschland",
        "debitorNumber": "255885",
        "debitorType": "T",
        "debitorId": "2af0e985-549d-21bb-e053-404c070a3ef5",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "addressId": "5579db0b-0a00-4b01-4f55-8c7911eb2e7d",
        "name1": "Sunitha",
        "name2": "H",
        "name3": "Srinivas",
        "name4": "naveen",
        "country": "Deutschland",
        "city": "street1",
        "houseNumber": "5653",
        "postalCode": "44433",
        "streetName": "Perfecttesta",
        "debitorNumber": "123456",
        "debitorType": "D",
        "debitorId": "eb7518b2-0a00-4b01-637b-a766a394571d",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "addressId": "f9f6ac1b-c0a8-4dba-0016-a0bd07443dfd",
        "name1": "Techfund Debitor",
        "name2": "k2",
        "name3": "k3",
        "name4": "k4",
        "country": "Irland",
        "city": "Galway",
        "houseNumber": "3232",
        "postalCode": "43232432",
        "streetName": "Street",
        "debitorNumber": "000005",
        "debitorType": "T",
        "debitorId": "20696b80-a2c7-0b07-e053-424c070a2c92",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "addressId": "003a35d8-c0a8-4da8-3d91-00df389e1b67",
        "name1": "TFKund 1",
        "country": "Deutschland",
        "city": "TF City",
        "houseNumber": "77",
        "postalCode": "65487",
        "streetName": "TF Street",
        "debitorNumber": "444555",
        "debitorType": "T",
        "debitorId": "2469fac3-d10e-5a0f-e053-404c070a68c1",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "addressId": "1ff1b658-c0a8-4da8-5600-e6ffaa2dc86c",
        "name1": "techfund",
        "name2": "k2",
        "name3": "k3",
        "country": "Deutschland",
        "city": "Galway",
        "houseNumber": "43433",
        "postalCode": "434343",
        "streetName": "street",
        "debitorNumber": "151119",
        "debitorType": "T",
        "debitorId": "24e5f4bf-901a-3b04-e053-424c070a666a",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "addressId": "402f09b0-c0a8-4dba-5239-3809020cd0bd",
        "name1": "TF New One 1",
        "name2": "TF New One 2",
        "name3": "TF New One 3",
        "name4": "TF New One 4",
        "country": "Deutschland",
        "city": "TF New One Town",
        "houseNumber": "5646546",
        "postalCode": "2135454",
        "streetName": "TF New One Street",
        "debitorNumber": "580912",
        "debitorType": "T",
        "debitorId": "294bc659-41f0-7ffd-e053-424c070aa756",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "addressId": "3bcc6772-c0a8-4dba-5239-380942f620f9",
        "name1": "new techfund debitor",
        "country": "Deutschland",
        "city": "city",
        "houseNumber": "54435345",
        "postalCode": "45456",
        "streetName": "street",
        "debitorNumber": "160113",
        "debitorType": "T",
        "debitorId": "295fa553-175c-0c9b-e053-404c070a3662",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "addressId": "a6c08b36-c0a8-4dba-18b3-437041939ecd",
        "name1": "qqq",
        "name2": "qqq",
        "name3": "qqq",
        "country": "Deutschland",
        "city": "cvdvdsvds",
        "houseNumber": "11",
        "postalCode": "11111",
        "streetName": "fdsdsfds",
        "debitorNumber": "123456",
        "debitorType": "T",
        "debitorId": "a6c08b36-c0a8-4dba-18b3-43703bf8eead",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "addressId": "58aee9fb-c0a8-4dba-0191-851df0eb1a32",
        "name1": "test",
        "country": "Deutschland",
        "city": "test",
        "houseNumber": "1",
        "postalCode": "12345",
        "streetName": "street",
        "debitorNumber": "345690",
        "debitorType": "T",
        "debitorId": "77cb5b6a-dbd0-5bda-e053-974c070ad0b9",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "addressId": "f4baf4ff-c0a8-4dba-3280-73f0719c170e",
        "name1": "New Debitor",
        "name2": "Kundenname 2",
        "name3": "kundenname 3",
        "name4": "kundenname 4",
        "country": "Großbritannien",
        "city": "sLONDON",
        "houseNumber": "434",
        "postalCode": "432432423",
        "streetName": "sTREEET",
        "debitorNumber": "150922",
        "debitorType": "D",
        "debitorId": "2054fa50-5058-42c7-e053-424c070ae8fa",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "addressId": "f93b29f8-c0a8-4dba-4070-9312a397f99f",
        "name1": "dfdf",
        "name2": "fd",
        "name3": "fdfd",
        "name4": "dffd",
        "country": "Deutschland",
        "city": "fdfd",
        "houseNumber": "443",
        "postalCode": "4344343",
        "streetName": "fdfd",
        "debitorNumber": "999071",
        "debitorType": "T",
        "debitorId": "210c0d98-bfac-35f9-e053-424c070a7219",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "addressId": "38fe4c79-c0a8-4da8-1f04-9b5376ce3dc7",
        "name1": "sds",
        "name2": "sd",
        "country": "Deutschland",
        "city": "rdrfedr",
        "houseNumber": "34",
        "postalCode": "434343",
        "streetName": "sdsd",
        "debitorNumber": "546576",
        "debitorType": "T",
        "debitorId": "2547ab44-ecbb-131b-e053-424c070ad72b",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "addressId": "49a0fc13-c0a8-4da8-0340-c05cd1cc6171",
        "name1": "techfund",
        "name2": "k1",
        "country": "Frankreich",
        "poBox": "545435435",
        "city": "galeay",
        "postalCode": "34567",
        "debitorNumber": "000007",
        "debitorType": "T",
        "debitorId": "25889938-f362-4c68-e053-404c070a1682",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "addressId": "a6ba0aad-c0a8-4dba-18b3-4370cdc15d1c",
        "name1": "2",
        "name2": "3",
        "name3": "4",
        "name4": "5",
        "country": "Deutschland",
        "city": "ddfsadada",
        "houseNumber": "1",
        "postalCode": "11223",
        "streetName": "qqqqq",
        "debitorNumber": "1234567",
        "debitorType": "D",
        "debitorId": "a6ba0aac-c0a8-4dba-18b3-43705d5ac7ca",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "addressId": "0cb5bc0b-c0a8-4da9-6e94-bd5ff972d06d",
        "name1": "sw1",
        "name2": "sw2",
        "country": "Deutschland",
        "city": "stadt",
        "houseNumber": "34",
        "postalCode": "12345",
        "streetName": "street",
        "debitorNumber": "123678",
        "debitorType": "D",
        "debitorId": "60396955-50c5-1cf5-e053-404c070af820",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "addressId": "50ac5caf-c0a8-4da3-1860-3b7c1a62b318",
        "name1": "Kundenname1",
        "name2": "Kundenname2",
        "country": "Deutschland",
        "city": "City",
        "houseNumber": "55",
        "postalCode": "12387",
        "streetName": "Street",
        "debitorNumber": "567899",
        "debitorType": "D",
        "debitorId": "f0dce0fe-0a00-4b01-2725-c3c6731a7460",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "addressId": "5579db0b-0a00-4b01-4f55-8c7911eb2e7d",
        "name1": "Sunitha",
        "name2": "H",
        "name3": "Srinivas",
        "name4": "naveen",
        "country": "Deutschland",
        "city": "street1",
        "houseNumber": "5653",
        "postalCode": "44433",
        "streetName": "Perfecttesta",
        "debitorNumber": "345672",
        "debitorType": "D",
        "debitorId": "eb7b419b-0a00-4b01-637b-a7667f5a9051",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "addressId": "fa17aaf1-c0a8-4dba-7e3c-462d6d1141c6",
        "name1": "Standard Debitor",
        "country": "Belgien",
        "city": "Brussels",
        "houseNumber": "5435",
        "postalCode": "32432",
        "streetName": "Street",
        "debitorNumber": "230915",
        "debitorType": "D",
        "debitorId": "2069bd85-77a4-5959-e053-424c070aad0f",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "country": "Deutschland",
        "debitorNumber": "146443",
        "debitorType": "D",
        "debitorId": "5483a489-d117-0bf5-e053-424c070aa05f",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "addressId": "1af23e8e-c0a8-4da8-5600-e6ff9b3a2a0f",
        "name1": "Deb 1",
        "country": "Deutschland",
        "city": "Deb City",
        "houseNumber": "77",
        "postalCode": "32154",
        "streetName": "Deb Street",
        "debitorNumber": "777999",
        "debitorType": "T",
        "debitorId": "24d24a70-edda-6038-e053-404c070a7610",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "addressId": "91b0f5de-c0a8-4dba-78b1-8d42faf94a4c",
        "name1": "techfund",
        "name2": "debitor",
        "country": "Deutschland",
        "city": "Berlin",
        "houseNumber": "25a",
        "postalCode": "212345",
        "streetName": "Straße",
        "debitorNumber": "111215",
        "debitorType": "T",
        "debitorId": "26a229ab-dc6d-584f-e053-424c070a8c25",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "addressId": "f02bf69f-c0a8-4dba-4070-9312b52da72b",
        "name1": "techfund debitor",
        "country": "Deutschland",
        "city": "aber",
        "houseNumber": "54543",
        "postalCode": "6436436",
        "streetName": "techfund debitor",
        "debitorNumber": "100000",
        "debitorType": "T",
        "debitorId": "20440a3e-8506-7db2-e053-404c070a91f2",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "addressId": "2b05112a-c0a8-4da8-20ad-8b5d8cb44133",
        "name1": "techfund debitor",
        "name2": "same as cpd no.",
        "country": "Deutschland",
        "city": "Berlin",
        "houseNumber": "456465",
        "postalCode": "5443543",
        "streetName": "strret",
        "debitorNumber": "070616",
        "debitorType": "T",
        "debitorId": "2b051129-c0a8-4da8-20ad-8b5d43f7b684",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "addressId": "28606ed0-c0a8-4dba-20e4-2cb58d0b643f",
        "name1": "Chunyang",
        "country": "Deutschland",
        "city": "qwert",
        "houseNumber": "1",
        "postalCode": "12365",
        "streetName": "Elms",
        "debitorNumber": "021015",
        "debitorType": "T",
        "debitorId": "28606ed0-c0a8-4dba-20e4-2cb573b822e9",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "addressId": "7c65988c-c0a8-4dba-65b6-bc348b2cdc13",
        "name1": "k1",
        "country": "Deutschland",
        "city": "Berlin",
        "houseNumber": "54545",
        "postalCode": "545435",
        "streetName": "street",
        "debitorNumber": "071215",
        "debitorType": "T",
        "debitorId": "264eface-676f-197e-e053-424c070a72f5",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": true,
        "default": false,
        "readOnly": true
    },
    {
        "addressId": "f993f961-c0a8-4dba-4070-9312cd3642dc",
        "name1": "Verified Techfund Debitor",
        "name2": "k2",
        "name3": "k3",
        "country": "Deutschland",
        "poBox": "7879456464",
        "city": "Berlin",
        "postalCode": "1025478",
        "debitorNumber": "000004",
        "debitorType": "T",
        "debitorId": "20668fda-563b-6326-e053-404c070a2110",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "addressId": "0033fd88-c0a8-4da8-693b-3cc788877cfc",
        "name1": "techfund debitor",
        "country": "Deutschland",
        "city": "Bonn",
        "houseNumber": "465",
        "postalCode": "6436436",
        "streetName": "techfund debitor",
        "debitorNumber": "000002",
        "debitorType": "T",
        "debitorId": "0033fd88-c0a8-4da8-693b-3cc7984836b9",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "country": "Deutschland",
        "debitorNumber": "160422",
        "debitorType": "D",
        "debitorId": "3114eaba-617d-11e7-e053-404c070ae132",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "addressId": "28d580ea-c0a8-4dba-6387-c7b9ab52022b",
        "name1": "chunyang",
        "country": "Deutschland",
        "city": "qwert",
        "houseNumber": "1",
        "postalCode": "12365",
        "streetName": "elms",
        "debitorNumber": "147852",
        "debitorType": "D",
        "debitorId": "2120fb4a-2326-5300-e053-424c070a2a20",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "addressId": "50ac5caf-c0a8-4da3-1860-3b7c1a62b318",
        "name1": "Kundenname1",
        "name2": "Kundenname2",
        "country": "Deutschland",
        "city": "City",
        "houseNumber": "55",
        "postalCode": "12387",
        "streetName": "Street",
        "debitorNumber": "555577",
        "debitorType": "D",
        "debitorId": "f0e6c696-0a00-4b01-2725-c3c6143fe4c4",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "addressId": "2e2e9f73-0a00-4b01-793e-03152d55c9f9",
        "name1": "s",
        "name2": "e",
        "country": "Deutschland",
        "city": "hyyyy",
        "houseNumber": "111111111",
        "postalCode": "11156",
        "streetName": "a",
        "debitorNumber": "122222222222222",
        "debitorType": "D",
        "debitorId": "2e2ea28c-0a00-4b01-793e-031524de0fd5",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "addressId": "66737ce9-c0a8-4dba-753a-79f54bcfd2f9",
        "name1": "new debitor",
        "name2": "k2",
        "name3": "k3",
        "name4": "k4",
        "country": "Deutschland",
        "poBox": "1478452",
        "city": "Berlin",
        "postalCode": "187452",
        "debitorNumber": "141015",
        "debitorType": "D",
        "debitorId": "22113313-d7ab-73cd-e053-424c070af50a",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "addressId": "1aaac772-c0a8-4da8-5600-e6ffc350a58f",
        "name1": "TF Konto namme 1",
        "country": "Dänemark",
        "city": "Stadt in Danemark",
        "houseNumber": "23",
        "postalCode": "12345",
        "streetName": "TF Street",
        "debitorNumber": "888888",
        "debitorType": "T",
        "debitorId": "24e78dd0-f536-6632-e053-424c070a77f2",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "addressId": "49848068-c0a8-4da8-0340-c05cfde2e38d",
        "name1": "techfund",
        "name2": "approve",
        "country": "Deutschland",
        "city": "Bonn",
        "houseNumber": "323423",
        "postalCode": "987456",
        "streetName": "Straße",
        "debitorNumber": "151127",
        "debitorType": "T",
        "debitorId": "258793ea-f915-6062-e053-404c070aa7be",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "addressId": "41085274-c0a8-4dba-5239-380949d1383c",
        "name1": "Standard Debitor 1",
        "name2": "Standard Debitor 2",
        "name3": "Standard Debitor 3",
        "name4": "Standard Debitor 4",
        "country": "Deutschland",
        "poBox": "579687651",
        "city": "Standard Debitor Town",
        "postalCode": "3215465",
        "debitorNumber": "881100",
        "debitorType": "D",
        "debitorId": "294f299f-2842-0133-e053-424c070a55c9",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "addressId": "00320d7d-c0a8-4da8-693b-3cc7e69791ee",
        "name1": "invalid techfund debitor",
        "country": "Deutschland",
        "city": "Berlin",
        "houseNumber": "4646",
        "postalCode": "7410256",
        "streetName": "street",
        "debitorNumber": "000001",
        "debitorType": "T",
        "debitorId": "00320d7c-c0a8-4da8-693b-3cc7ba40914e",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": true,
        "default": false,
        "readOnly": true
    },
    {
        "addressId": "14512dfb-c0a8-4dba-437f-9d47d0f3dfeb",
        "name1": "verified techfund debitor",
        "name2": "k2",
        "name3": "k3",
        "name4": "k4",
        "country": "Deutschland",
        "poBox": "7897987979",
        "city": "Berlin",
        "postalCode": "145236",
        "debitorNumber": "150928",
        "debitorType": "T",
        "debitorId": "20d06e80-b327-31f8-e053-404c070a5559",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "addressId": "0cb58c6d-c0a8-4da9-6e94-bd5f3b35d15f",
        "name1": "swathitest",
        "name2": "swathitest2",
        "name3": "swathitest4",
        "name4": "swathitest5",
        "country": "Deutschland",
        "city": "gfgfgg",
        "houseNumber": "54545",
        "postalCode": "545454",
        "streetName": "asdsad",
        "debitorNumber": "6565465",
        "debitorType": "D",
        "debitorId": "60393afa-3a36-3750-e053-404c070a14ed",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "addressId": "1fa7ad6a-c0a8-4da8-5600-e6ff58c01763",
        "name1": "techfund",
        "name2": "k2",
        "country": "Deutschland",
        "city": "Berlin",
        "houseNumber": "43434",
        "postalCode": "5348593457",
        "streetName": "street",
        "debitorNumber": "191115",
        "debitorType": "T",
        "debitorId": "24e4bb4f-f59c-78b7-e053-424c070a6e91",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "addressId": "0c989ca1-c0a8-4da9-6e94-bd5f521cc12d",
        "name1": "dfvdvd",
        "country": "Deutschland",
        "city": "fdvfdvfv",
        "houseNumber": "vvfdvfddf",
        "postalCode": "34444",
        "streetName": "34434d",
        "debitorNumber": "555666",
        "debitorType": "D",
        "debitorId": "5f323f8d-b588-5fa1-e053-424c070a7198",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": true,
        "default": false,
        "readOnly": true
    },
    {
        "addressId": "81f79a67-c0a8-4dba-219b-1c151c4d3ae1",
        "name1": "name1",
        "name2": "name2",
        "name3": "name3",
        "country": "Estland",
        "city": "city",
        "houseNumber": "111",
        "postalCode": "76765",
        "streetName": "street",
        "debitorNumber": "9111112",
        "debitorType": "D",
        "debitorId": "81f79a67-c0a8-4dba-219b-1c153600ef32",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "addressId": "f4e12c08-c0a8-4dba-4070-9312f9bb81ac",
        "name1": "eer",
        "name2": "rerer",
        "name3": "erer",
        "name4": "rere",
        "country": "Deutschland",
        "city": "rere",
        "houseNumber": "43",
        "postalCode": "34434334",
        "streetName": "erer",
        "debitorNumber": "333333",
        "debitorType": "T",
        "debitorId": "20553487-ca7a-1366-e053-404c070a08bd",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "country": "Deutschland",
        "debitorNumber": "260916",
        "debitorType": "T",
        "debitorId": "3d689644-e223-21e4-e053-404c070af2d2",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "addressId": "e0a3eb8a-c0a8-4dba-4ae5-8a65ea692aa3",
        "name1": "Techfund Debitor",
        "name2": "Kundenname 2",
        "name3": "Kundenname 3",
        "name4": "kundenname 4",
        "country": "Deutschland",
        "city": "Berlin",
        "houseNumber": "554",
        "postalCode": "4323423",
        "streetName": "Street",
        "debitorNumber": "180915",
        "debitorType": "T",
        "debitorId": "e0a3eb8a-c0a8-4dba-4ae5-8a65bbeed95d",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "addressId": "191a629f-c0a8-4dba-437f-9d47f1fbf235",
        "name1": "techfund debitor",
        "name2": "TECHFUND DEBITOR",
        "country": "Deutschland",
        "city": "aber",
        "houseNumber": "567576",
        "postalCode": "6436436",
        "streetName": "techfund debitor",
        "debitorNumber": "000006",
        "debitorType": "T",
        "debitorId": "20e53016-d500-33d8-e053-404c070a9e09",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "country": "Deutschland",
        "debitorNumber": "765766",
        "debitorType": "T",
        "debitorId": "4d6ebad0-e2b7-0a58-e053-424c070a1f46",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "addressId": "17dde026-c0a8-4dba-437f-9d47dd0c77bb",
        "name1": "gdfds",
        "name2": "ss",
        "country": "Deutschland",
        "city": "gdfg",
        "houseNumber": "22",
        "postalCode": "333333",
        "streetName": "asd",
        "debitorNumber": "297100",
        "debitorType": "T",
        "debitorId": "20e16adf-98f0-0cf1-e053-404c070a1ba3",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "addressId": "3910298d-c0a8-4da8-1f04-9b5381b1206f",
        "name1": "fdf",
        "name2": "fd",
        "country": "Deutschland",
        "city": "fdfdfddf",
        "houseNumber": "43",
        "postalCode": "4444343",
        "streetName": "dffd",
        "debitorNumber": "890976",
        "debitorType": "T",
        "debitorId": "254801eb-056d-4ae1-e053-424c070ad965",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "country": "Deutschland",
        "debitorNumber": "160114",
        "debitorType": "T",
        "debitorId": "294adee3-c040-1870-e053-424c070a300f",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "country": "Deutschland",
        "debitorNumber": "097898",
        "debitorType": "T",
        "debitorId": "3d664891-15f2-1cdc-e053-424c070addbf",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "addressId": "50ac5caf-c0a8-4da3-1860-3b7c1a62b318",
        "name1": "Kundenname1",
        "name2": "Kundenname2",
        "country": "Deutschland",
        "city": "City",
        "houseNumber": "55",
        "postalCode": "12387",
        "streetName": "Street",
        "debitorNumber": "567893",
        "debitorType": "D",
        "debitorId": "f0dea920-0a00-4b01-2725-c3c614fc653e",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "addressId": "efa708c2-c0a8-4dba-3280-73f0ce49af69",
        "name1": "K1- TECHFUND",
        "name2": "K2",
        "country": "Deutschland",
        "city": "gALWAY",
        "houseNumber": "49823",
        "postalCode": "453543",
        "streetName": "STREET",
        "debitorNumber": "112233",
        "debitorType": "T",
        "debitorId": "efa708c1-c0a8-4dba-3280-73f035055bf9",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": true,
        "default": false,
        "readOnly": true
    },
    {
        "addressId": "1f1dcd18-c0a8-4da8-5600-e6ff418ed69a",
        "name1": "Tech Deb 1",
        "country": "Deutschland",
        "city": "Tech City",
        "houseNumber": "55",
        "postalCode": "76545",
        "streetName": "Tech Street",
        "debitorNumber": "778899",
        "debitorType": "T",
        "debitorId": "24e79738-8fb6-1f0f-e053-424c070a4777",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "country": "Deutschland",
        "debitorNumber": "160115",
        "debitorType": "T",
        "debitorId": "29627854-af08-43c3-e053-404c070a02e0",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "addressId": "d294fe4e-c0a8-4dba-4237-f6048fea0593",
        "country": "Deutschland",
        "city": "Lorch",
        "houseNumber": "128",
        "postalCode": "73547",
        "streetName": "Bülling Straße",
        "debitorNumber": "234567",
        "debitorType": "D",
        "debitorId": "42f76b0f-581f-3791-e053-424c070ac844",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "addressId": "22893397-c0a8-4dba-437f-9d4778d99a28",
        "name1": "techfund debitor 1",
        "name2": "TECHFUND DEBITOR 2",
        "name3": "k3",
        "name4": "k4",
        "country": "Deutschland",
        "city": "Berlin",
        "houseNumber": "125b",
        "postalCode": "6436436",
        "streetName": "techfund debitor city",
        "debitorNumber": "011015",
        "debitorType": "T",
        "debitorId": "210a9009-7756-765f-e053-424c070aa43a",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "country": "Deutschland",
        "debitorNumber": "889977",
        "debitorType": "T",
        "debitorId": "2af0d277-3f22-0f45-e053-404c070a20bb",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "country": "Deutschland",
        "debitorNumber": "423333",
        "debitorType": "T",
        "debitorId": "4d828dbf-8304-3b5f-e053-404c070a6ba7",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "addressId": "9a95c931-c0a8-4dba-772d-e6bc98f41ff5",
        "name1": "nnn1",
        "name2": "nnn2",
        "name3": "nnn3",
        "name4": "nnn4",
        "country": "Estland",
        "city": "city",
        "houseNumber": "123",
        "postalCode": "22311",
        "streetName": "street",
        "debitorNumber": "776601",
        "debitorType": "T",
        "debitorId": "9a95c931-c0a8-4dba-772d-e6bc42d46058",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "addressId": "5579db0b-0a00-4b01-4f55-8c7911eb2e7d",
        "name1": "Sunitha",
        "name2": "H",
        "name3": "Srinivas",
        "name4": "naveen",
        "country": "Deutschland",
        "city": "street1",
        "houseNumber": "5653",
        "postalCode": "44433",
        "streetName": "Perfecttesta",
        "debitorNumber": "123456",
        "debitorType": "D",
        "debitorId": "eb3c55b5-0a00-4b01-637b-a7669fe4faa1",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "addressId": "fa8082f5-c0a8-4dba-7e3c-462d2d107bdc",
        "name1": "Blacklisted Debitor",
        "name2": "k2",
        "country": "Deutschland",
        "city": "Berlin",
        "houseNumber": "43432",
        "postalCode": "43232",
        "streetName": "street",
        "debitorNumber": "999999",
        "debitorType": "T",
        "debitorId": "fa8082f5-c0a8-4dba-7e3c-462dab2a21e0",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": true,
        "default": false,
        "readOnly": true
    },
    {
        "addressId": "37e2fde1-c0a8-4dba-0622-884d1b653fd8",
        "name1": "Techfund k1",
        "name2": "k2",
        "name3": "k3",
        "name4": "k4",
        "country": "Deutschland",
        "poBox": "34322342",
        "city": "Berlin",
        "postalCode": "424342",
        "debitorNumber": "051015",
        "debitorType": "T",
        "debitorId": "215b54e8-2552-35c7-e053-404c070add21",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "addressId": "496a3623-c0a8-4da8-0340-c05c65750db0",
        "name1": "k1",
        "name2": "k2",
        "name3": "k3",
        "name4": "k4",
        "country": "Deutschland",
        "city": "Berlin",
        "houseNumber": "354543",
        "postalCode": "123456",
        "streetName": "street",
        "debitorNumber": "271115",
        "debitorType": "T",
        "debitorId": "2587cc0e-9fd2-605a-e053-404c070afca6",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "addressId": "4497faf8-c0a8-4dba-5239-3809b4939201",
        "name1": "Standard Debitor Test 1",
        "name2": "Standard Debitor Test 2",
        "name3": "Standard Debitor Test 3",
        "name4": "Standard Debitor Test 4",
        "country": "Deutschland",
        "city": "Standard Debitor Test Town",
        "houseNumber": "741741",
        "postalCode": "258369147",
        "streetName": "Standard Debitor Test Street",
        "debitorNumber": "506030",
        "debitorType": "D",
        "debitorId": "295d2544-5efe-08d5-e053-424c070a5266",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "addressId": "3fa5df11-c0a8-4dba-5239-3809cca6f04c",
        "name1": "New TF Debitor",
        "name2": "New TF Debitor 2",
        "name3": "New TF Debitor 3",
        "name4": "New TF Debitor 4",
        "country": "Portugal",
        "city": "New TF Debitor Town",
        "houseNumber": "5465465",
        "postalCode": "852825",
        "streetName": "New TF Debitor Street",
        "debitorNumber": "875595",
        "debitorType": "T",
        "debitorId": "294a97be-31c8-3f28-e053-424c070a8a46",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "country": "Deutschland",
        "debitorNumber": "0102161",
        "debitorType": "D",
        "debitorId": "2ab655fa-e422-6e93-e053-404c070a9835",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "addressId": "1f727c66-c0a8-4da8-20ad-8b5d2e298e20",
        "name1": "Debitor Name 1",
        "name2": "Debitor Name 2",
        "name3": "Debitor Name 3",
        "name4": "Debitor Name 4",
        "country": "Deutschland",
        "city": "Stadt",
        "houseNumber": "12345",
        "postalCode": "667788",
        "streetName": "Street",
        "debitorNumber": "445566",
        "debitorType": "D",
        "debitorId": "1f727c66-c0a8-4da8-20ad-8b5dfd27d8e1",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "addressId": "66d36603-c0a8-4da8-4d01-c7cf88673c09",
        "name1": "test",
        "country": "Deutschland",
        "city": "fdsf",
        "houseNumber": "44",
        "postalCode": "44444",
        "streetName": "ttt",
        "debitorNumber": "478910",
        "debitorType": "T",
        "debitorId": "66d36603-c0a8-4da8-4d01-c7cfd6d136a1",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "addressId": "5579db0b-0a00-4b01-4f55-8c7911eb2e7d",
        "name1": "Sunitha",
        "name2": "H",
        "name3": "Srinivas",
        "name4": "naveen",
        "country": "Deutschland",
        "city": "street1",
        "houseNumber": "5653",
        "postalCode": "44433",
        "streetName": "Perfecttesta",
        "debitorNumber": "12344566",
        "debitorType": "D",
        "debitorId": "eb3874f2-0a00-4b01-637b-a766a6e7a0f5",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "addressId": "3bc3ac1a-c0a8-4dba-5239-380901252c00",
        "name1": "grainne",
        "name2": "hackett",
        "name3": "synchronoss technologies",
        "country": "Irland",
        "city": "Unit 8",
        "houseNumber": "1",
        "postalCode": "78989789",
        "streetName": "level",
        "debitorNumber": "130116",
        "debitorType": "T",
        "debitorId": "295f88f5-4ba9-53ca-e053-424c070a95e9",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "country": "Deutschland",
        "debitorNumber": "312141",
        "debitorType": "D",
        "debitorId": "36408ac5-be60-67a8-e053-404c070ac82f",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "country": "Deutschland",
        "debitorNumber": "789023",
        "debitorType": "T",
        "debitorId": "3d664891-15f1-1cdc-e053-424c070addbf",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "addressId": "18d40e56-c0a8-4dba-437f-9d4751af253e",
        "name1": "invalid techfund debitor",
        "name2": "4564j",
        "country": "Deutschland",
        "city": "Berlin",
        "houseNumber": "4646",
        "postalCode": "7410256",
        "streetName": "street",
        "debitorNumber": "000001",
        "debitorType": "T",
        "debitorId": "20e2730c-2669-6e40-e053-404c070a0109",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": true,
        "default": false,
        "readOnly": true
    },
    {
        "addressId": "70698afe-c0a8-4dba-7b4b-02d97a8ecaf2",
        "name1": "techfund k1",
        "name2": "k2",
        "name3": "k3",
        "name4": "k4- edit",
        "country": "Deutschland",
        "city": "berlin",
        "houseNumber": "55345",
        "postalCode": "54354353",
        "streetName": "street",
        "debitorNumber": "151002",
        "debitorType": "T",
        "debitorId": "70698afd-c0a8-4dba-7b4b-02d91a64891e",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "country": "Deutschland",
        "debitorNumber": "081024",
        "debitorType": "T",
        "debitorId": "295f88f5-4bae-53ca-e053-424c070a95e9",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "addressId": "0bd70f3c-c0a8-4da9-6e94-bd5f6fd8cfc3",
        "name1": "dscds",
        "name2": "dcsdc",
        "country": "Deutschland",
        "city": "rererer",
        "houseNumber": "dfsvvffvd",
        "postalCode": "434343",
        "streetName": "34434",
        "debitorNumber": "333444",
        "debitorType": "D",
        "debitorId": "5f2f53b0-4f3e-7376-e053-424c070aaef9",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "addressId": "f4d314bd-c0a8-4dba-4070-9312a7b60517",
        "name1": "AAAA",
        "name2": "AAAA",
        "name3": "AAAA",
        "name4": "AAAA",
        "country": "Deutschland",
        "city": "AAAA",
        "houseNumber": "43",
        "postalCode": "433434",
        "streetName": "AAAA",
        "debitorNumber": "434343",
        "debitorType": "T",
        "debitorId": "20553487-ca74-1366-e053-404c070a08bd",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "country": "Deutschland",
        "debitorNumber": "555799",
        "debitorType": "T",
        "debitorId": "289586c3-8064-1ffc-e053-424c070a5124",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "addressId": "0cb602d0-c0a8-4da9-6e94-bd5f350b964d",
        "name1": "mahendratest1",
        "name2": "mahendratest2",
        "name3": "mahendratest3",
        "name4": "mahendratest4",
        "country": "Deutschland",
        "city": "gfdgfdgg",
        "houseNumber": "43433",
        "postalCode": "54354",
        "streetName": "dsfdsf",
        "debitorNumber": "4343455",
        "debitorType": "D",
        "debitorId": "604f3666-1377-6ffc-e053-404c070acb59",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "addressId": "0cb637d5-c0a8-4da9-6e94-bd5f012e70e5",
        "name1": "swath1",
        "country": "Deutschland",
        "city": "stadt",
        "houseNumber": "34",
        "postalCode": "12345",
        "streetName": "street",
        "debitorNumber": "345667",
        "debitorType": "D",
        "debitorId": "605e4832-9097-100a-e053-424c070a5461",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "addressId": "242aff76-0a00-4b01-0353-d252c1dd4d61",
        "name1": "Sunitha",
        "name2": "h",
        "name3": "h",
        "country": "Deutschland",
        "city": "12333",
        "houseNumber": "12345",
        "postalCode": "12345",
        "streetName": "12345",
        "debitorNumber": "1234555",
        "debitorType": "T",
        "debitorId": "242affb8-0a00-4b01-0353-d252465eafbc",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "addressId": "fa87f17c-c0a8-4dba-7e3c-462ddbc417d4",
        "name1": "Blacklisted",
        "name2": "TECHFUND DEBITOR",
        "name3": "k3",
        "name4": "k4",
        "country": "Deutschland",
        "city": "aber",
        "houseNumber": "5343",
        "postalCode": "6436436",
        "streetName": "street",
        "debitorNumber": "666666",
        "debitorType": "T",
        "debitorId": "fa87f17b-c0a8-4dba-7e3c-462ddd6b3f35",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": true,
        "default": false,
        "readOnly": true
    },
    {
        "addressId": "4c4d0444-c0a8-4dba-22fc-94a1878ebd2a",
        "name1": "Standard1",
        "name2": "Standard2",
        "name3": "Standard3",
        "name4": "Standard",
        "country": "Deutschland",
        "city": "reere",
        "houseNumber": "32",
        "postalCode": "23232323",
        "streetName": "Standard1",
        "debitorNumber": "156987",
        "debitorType": "T",
        "debitorId": "21ab0ccf-5fd8-6a2f-e053-424c070a4c3d",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "addressId": "80a910a4-c0a8-4da8-7e82-8f0cb418dcad",
        "name1": "ttt",
        "country": "Deutschland",
        "city": "fdsfds",
        "houseNumber": "34",
        "postalCode": "33333",
        "streetName": "fdsfd",
        "debitorNumber": "123490",
        "debitorType": "T",
        "debitorId": "80a910a4-c0a8-4da8-7e82-8f0c7c652507",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "addressId": "80ac9ef9-c0a8-4da8-7e82-8f0c7c8fdbf2",
        "name1": "tet",
        "name2": "tt",
        "name3": "gfdg",
        "name4": "gfdgg",
        "country": "Deutschland",
        "city": "dsasd",
        "houseNumber": "45",
        "postalCode": "12222",
        "streetName": "gfdg",
        "debitorNumber": "345678",
        "debitorType": "T",
        "debitorId": "80ac9ef9-c0a8-4da8-7e82-8f0c30b371c3",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "addressId": "18f6cd5b-c0a8-4dba-437f-9d47fb209cdc",
        "name1": "fg",
        "name2": "fgffffffff",
        "country": "Finnland",
        "city": "eres",
        "houseNumber": "333",
        "postalCode": "43534",
        "streetName": "fg",
        "debitorNumber": "969696",
        "debitorType": "T",
        "debitorId": "21fb9814-ddb4-4701-e053-424c070a9df9",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "addressId": "f93b29f8-c0a8-4dba-4070-9312a397f99f",
        "name1": "dfdf",
        "name2": "fd",
        "name3": "fdfd",
        "name4": "dffd",
        "country": "Deutschland",
        "city": "fdfd",
        "houseNumber": "443",
        "postalCode": "4344343",
        "streetName": "fdfd",
        "debitorNumber": "999072",
        "debitorType": "D",
        "debitorId": "210c4e26-617e-5ca9-e053-424c070acba8",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": true,
        "default": false,
        "readOnly": true
    },
    {
        "addressId": "374ead04-c0a8-4dba-4496-5b287aab2f05",
        "name1": "Standard Debitor",
        "name2": "k2",
        "country": "Deutschland",
        "city": "Brussels",
        "houseNumber": "545n",
        "postalCode": "32432",
        "streetName": "street",
        "debitorNumber": "121212",
        "debitorType": "D",
        "debitorId": "21590b54-6f94-2728-e053-404c070a371a",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "addressId": "40ebb786-c0a8-4da9-5b3a-7d5a4150c307",
        "name1": "dererer",
        "country": "Deutschland",
        "city": "ererrr",
        "houseNumber": "11",
        "postalCode": "22233",
        "streetName": "errtttrtr",
        "debitorNumber": "222554",
        "debitorType": "T",
        "debitorId": "40ebb785-c0a8-4da9-5b3a-7d5a73300a67",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "addressId": "80f63bb1-c0a8-4dba-219b-1c159e52ed66",
        "name1": "testname1",
        "name2": "testname2",
        "name3": "testname3",
        "name4": "testname4",
        "country": "Estland",
        "city": "state",
        "houseNumber": "111",
        "postalCode": "43433",
        "streetName": "street",
        "debitorNumber": "777666",
        "debitorType": "T",
        "debitorId": "80f63bb1-c0a8-4dba-219b-1c15a15270d0",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    },
    {
        "addressId": "50ac5caf-c0a8-4da3-1860-3b7c1a62b318",
        "name1": "Kundenname1",
        "name2": "Kundenname2",
        "country": "Deutschland",
        "city": "City",
        "houseNumber": "55",
        "postalCode": "12387",
        "streetName": "Street",
        "debitorNumber": "3333333",
        "debitorType": "D",
        "debitorId": "f0df9de9-0a00-4b01-2725-c3c66baa16e5",
        "vodafoneUser": true,
        "modified": false,
        "associated": true,
        "badDebitorInformation": false,
        "default": false,
        "readOnly": false
    }
];