module.exports = {
  "DOC_INVALID_FORMAT_ERROR": "invalid document format",
  "ED-ADV_RESET": "Reset",
  "ED-ADV_SEARCH_BANDWIDTH": "Bandwidth",
  "ED-ADV_SEARCH_BARCODE": "Barcode",
  "ED-ADV_SEARCH_DURATION": "Select",
  "ED-ADV_SEARCH_DURATION_OPTION": "Last 30 days",
  "ED-ADV_SEARCH_FROM_DATE": "From",
  "ED-ADV_SEARCH_KFP_OCM_ORDER_NO": "FKP OCM Order No",
  "ED-ADV_SEARCH_LOCATION": "Location",
  "ED-ADV_SEARCH_MILESTONE": "Fulfillment milestone",
  "ED-ADV_SEARCH_ORDER_NO": "DB Order No",
  "ED-ADV_SEARCH_ORDER_NO_2": "DB2 Order No",
  "ED-ADV_SEARCH_ORDER_STATUS": "Order status",
  "ED-ADV_SEARCH_PRODUCT": "Product",
  "ED-ADV_SEARCH_RADIO_BETW": "Period",
  "ED-ADV_SEARCH_SAP_ORDER_NO": "SAP Order No",
  "ED-ADV_SEARCH_TOGGLE_BUTTON": "Advanced Search",
  "ED-ADV_SEARCH_TO_DATE": "To",
  "ED-CUSTOMER_MESSAGE": "Comment on the status change",
  "ED-DOC-DELETE-CONFIRM": "Do you really want to delete the document?",
  "ED-DOC-DELETE-FAILED": "File Delete failed",
  "ED-DOC-FILE-NAME": "File Name",
  "ED-DOC-FILE-SIZE": "File Size",
  "ED-DOC-FILE_SIZE_ERROR": "This file exceeds the maximum size of 20 MB",
  "ED-DOC-MAX_ERROR": "maximum 10 records combined 20MB can be uploaded per Order",
  "ED-DOC-MAX_FILE_ERROR": "It can max. 10 files with a maximum of 20 MB can be uploaded.",
  "ED-DOC-UPLOADED-BY": "UploadedBy",
  "ED-DOC-UPLOADED-TS": "Uploaded On",
  "ED-DOCUMENT-MGT": "Attachments to this order",
  "ED-DOWNLOAD_SYSTEM_HISTORY": "Download system history",
  "ED-DOWNLOAD_UOF": "download UOF",
  "ED-DROPDOWN-CHOOSE": "Choose",
  "ED-FORM_ERROR_MSG": "Please correct the highlighted errors",
  "ED-HEADER_TITLE": "Order Management",
  "ED-LANDING_SAVE": "SAVE",
  "ED-LANDING_SEARCH": "Search",
  "ED-MODAL_BTN_OK": "OK",
  "ED-OD-BACK": "Back",
  "ED-OD-COL_COMMENTS": "comment",
  "ED-OD-COL_TIME": "Date Time",
  "ED-OD-COL_USERNAME": "User name",
  "ED-OD-COMMENTS-TITLE": "Comments about this order",
  "ED-OD-DETAILS-ORDER-TITLE": "Details about order",
  "ED-OD-DETAILS-TITLE": "Order Management",
  "ED-OD-ERROR": "Sorry, an error has occurred",
  "ED-OD-HISTORY-TITLE": "System history",
  "ED-OD-ORDER_DETAILS_TITLE": "Order details",
  "ED-OD-SAP_NUMBER": "SAP Order Number",
  "ED-OD-UPLOAD-BUTTON": "Upload",
  "ED-OD_CANCEL": "Cancel",
  "ED-OD_MILESTONE_TITLE": "Technical milestones",
  "ED-OD_SAVE": "Save",
  "ED-ORDER-DETAILS-DRAG_DROP_DESC_1": "Drag and drop your file into this area",
  "ED-ORDER-DETAILS-DRAG_DROP_DESC_2": "or click ",
  "ED-ORDER-DETAILS-DRAG_DROP_DESC_3": "here",
  "ED-ORDER-DETAILS-DRAG_DROP_DESC_4": " to select a file",
  "ED-ORDER-DETAILS-SUPPORTED-FORMAT-1": "SUPPORTED FORMATS",
  "ED-ORDER-DETAILS-SUPPORTED-FORMAT-2": "DOC, DOCX, PDF, XLS, XLSX and JPG",
  "ED-ORDER_STATUS": "Change order status",
  "ED-OU-SUBMIT-COL-CUST-ORDER-NUMBER": "Customer Order Number",
  "ED-OU-SUBMIT-COL-ORDER-NUMBER": "Order Number",
  "ED-SYS-HISTORY-COMMENT": "Order Comment",
  "ED-SYS-HISTORY-DOC_NAME": "Filename",
  "ED-SYS-HISTORY-MILESTONE": "Milestone",
  "ED-SYS-HISTORY-MILESTONE_STATUS": "Milestone Status",
  "ED-SYS-HISTORY-SAP_NUMBER": "SAP Order Number",
  "ED-SYS-HISTORY-STATUS": "Order Status",
  "ED-SYS-HISTORY-TIME": "Date",
  "ED-SYS-HISTORY-USERNAME": "Changed by",
  "ED-SYS-HISTORY_ACTION": "Action",
  "ED_DRIVE_CANCEL": "Cancel",
  "ED_DRIVE_CONFIRM": "Confirm",
  "ED_DRIVE_CONFIRM_DELETE": "Confirm Delete",
  "ED_DRIVE_CREATE": "Create",
  "ED_DRIVE_CREATED_AT": "Created at",
  "ED_DRIVE_CREATED_BY": "Created By",
  "ED_DRIVE_DELETE": "Delete",
  "ED_DRIVE_DELETE_MSG_1": "Are you sure you want to delete the ",
  "ED_DRIVE_DELETE_MSG_2": " file or folder?",
  "ED_DRIVE_DELETE_MSG_3": "This operation can not be undone.",
  "ED_DRIVE_DOWNLOAD_FILE": "Download file",
  "ED_DRIVE_DUPLICATE_FOLDER_NAME": "There is already a folder with this name. Please enter a different name.",
  "ED_DRIVE_EMPTY_FOLDER": "There are no files or folders.",
  "ED_DRIVE_ERROR_INFO": "Sorry, there was an error",
  "ED_DRIVE_ERROR_INVALIDFILE": "Unsupported file format",
  "ED_DRIVE_ERROR_UPLOAD": "There was an error while uploading",
  "ED_DRIVE_FILENAME_REGEX": "([;/:*?\"<>|&\\\\])",
  "ED_DRIVE_INVALID_FOLDER_NAME_SC": "Your entry contains invalid characters",
  "ED_DRIVE_INVALID_MOVE_DESTINATION_FILE": "File with same name already exists in the destination folder",
  "ED_DRIVE_INVALID_MOVE_DESTINATION_FOLDER": "Folder with same name already exists in the destination folder",
  "ED_DRIVE_MOVE": "Move",
  "ED_DRIVE_MOVE_TO_ROOT": "Move to the main directory",
  "ED_DRIVE_NAME": "Name",
  "ED_DRIVE_NEW_FOLDER": "New Folder",
  "ED_DRIVE_NEW_FOLDER_TITLE": "Create new folder",
  "ED_DRIVE_NO_FOLDER": "No folders",
  "ED_DRIVE_PASTE": "Paste",
  "ED_DRIVE_RENAME": "Rename",
  "ED_DRIVE_SUCCESS_UPLOAD": "Successfully Uploaded",
  "ED_DRIVE_TITLE": "Files",
  "ED_DRIVE_UPLOAD_DESC-1": "Drag and drop your file into this area",
  "ED_DRIVE_UPLOAD_DESC-1 ": "Drag and drop your file into this area to upload it to the folder or click",
  "ED_DRIVE_UPLOAD_DESC-2": "or click ",
  "ED_DRIVE_UPLOAD_DESC-3": "here,",
  "ED_DRIVE_UPLOAD_DESC-4": " to select a file",
  "ED_DRIVE_UPLOAD_FORMAT_DESC_1": "SUPPORTED FORMATS",
  "ED_DRIVE_UPLOAD_FORMAT_DESC_2": "DOC, DOCX, TXT, PDF, XLS, XLSX, CSV, PPT, PPTX, JPG, JPEG, PNG, XML and MSG",
  "ED_OM_ELIGIBILITY_ERR_MSG": "Attention! The order status has been changed by the system. Unsaved changes will be lost.",
  "ED_OM_FAILURE_ERR_MSG": "Your request could not be processed",
  "ED_OM_LOCKED_ERR_MSG": "Illegal status change! Please check the selection.",
  "ED_OM_MODAL_BTN_OK": "OK",
  "ED_OM_SELECT_ORDER_NO_ERR_MSG": "Please select at least one order.",
  "ED_OM_STATUS_CHANGE_SUCCESS_MSG": "Status change successful!",
  "FILE_UPLOAD_ERROR": "file upload failure",
  "OM-MILESTONE-UPLOAD-HEADER_LABEL": "Upload technical milestones",
  "OM-SUBMIT-CONFIRMATION_MSG": "Your order is",
  "OM-SUBMIT-FORM_ERRORS": "Validations failed",
  "OM-SUBMIT-HEADER_LABEL": "Submit New Order",
  "OM-SUBMIT-PANEL_DATA_FAILURE": "Panel data retrival failed",
  "OM-SUBMIT-SUBMIT_FAILURE": "Order save is failed",
  "OM-SUBMIT-SUBMIT_SAVE": "Create order",
  "OM-SUBMIT-SUBMIT_SUCCESS": "Order save is successful",
  "OM-UPLOAD-BTN_SUBMIT": "Submit",
  "OM-UPLOAD-HEADER_LABEL": "Upload an order",
  "OM-UPLOAD-UPLOAD_FAILURE": "Upload for orders is failed",
  "OM-UPLOAD-UPLOAD_SUCCESS": "Upload for orders was successful",
  "ORDER_CONFIRMATION": "Order Confirmation",
  "THANK_YOU_FOR_YOUR_ORDER": "Thank you for your order.",
  "UPLOAD_CHANGES-DESCRIPTION": "Uploaded file contains some ivalid records. How to proceed Download the excel file with those invalid records, below \"To order overview\" to proceed with the order or cancel the icon to upload a new file.",
  "UPLOAD_CHANGES-DRAG_DROP_DESC_1": "Put your order file here",
  "UPLOAD_CHANGES-DRAG_DROP_DESC_12": "or click ",
  "UPLOAD_CHANGES-DRAG_DROP_DESC_1_NON_DATA": "Drag and drop your file into this area",
  "UPLOAD_CHANGES-DRAG_DROP_DESC_2": "here",
  "UPLOAD_CHANGES-DRAG_DROP_DESC_3": " to select a file.",
  "UPLOAD_CHANGES-DRAG_DROP_REUPLOAD_DESC": "<b>Put down your corrected order file here</b><br/>or click ",
  "UPLOAD_CHANGES-ERROR_INAVLIDFILE": "The file could not be read.",
  "UPLOAD_CHANGES-ERROR_INFO": "<p> <b> Sorry, an error occurred </ b> </ p>",
  "UPLOAD_CHANGES-FORMAT_DESC": "SUPPORTED FORMAT",
  "UPLOAD_CHANGES-FORMAT_DESC1": "XLSX",
  "UPLOAD_CHANGES-INVALID_RECORD": "<p><b>{{invalidRecords}} record is invalid.</b></p><br><p>invalid row is {{invalidRows}}.</p>",
  "UPLOAD_CHANGES-INVALID_RECORDS": "<p> <b> {{invalidRecords}} records are invalid.</ b> </ p><br><p>invalid rows are {{invalidRows}}.</p>",
  "UPLOAD_CHANGES-PARTIAL_VALID_RECORDS": "<p><b>Number of valid orders: {{validRecords}}. Please click Submit to transfer the orders.</b></p>",
  "UPLOAD_CHANGES-VALID_RECORDS": "<p><b>Number of valid orders: {{validRecords}}. Please click Submit to transfer the orders.</b></p>",
  "GENERIC_SUCCESS": "The changes were made.",
  "GENERIC_FAILURE": "Sorry, there was an error.",
  "SAP_SUCCESS": "The SAP order number has been added.",
  "STATUS_SUCCESS": "The order status was changed successfully.",
  "COMMENT_SUCCESS": "Your comment has been added.",
  "UPLOAD_CHANGES-MILESTONE-INVALID_RECORD": "<p><b>{{invalidRecords}} record is invalid.</b></p><br><p>invalid row is {{invalidRows}}.</p>",
  "UPLOAD_CHANGES-MILESTONE-INVALID_RECORDS": "<p> <b> {{invalidRecords}} records are invalid.</ b> </ p><br><p>invalid rows are {{invalidRows}}.</p>",
  "UPLOAD_CHANGES-MILESTONE-PARTIAL_VALID_RECORDS": "<p><b>Number of valid orders: {{validRecords}}. Please click Submit to transfer the orders.</b></p>",
  "UPLOAD_CHANGES-MILESTONE-VALID_RECORDS": "<p><b>Number of valid orders: {{validRecords}}. Please click Submit to transfer the orders.</b></p>",
  "ED_CUSTOMER_COUNT" : "Number of customer number",
  "ED_SHOP_NAME": "Name of the shop",
  "ED_ROOT_CUSTOMER_NO": "Top level customer",
  "REPORTING_SELECT_SHOP_TITLE": "Select shop for reporting",
  "ED_DRIVE_NAVIGATE_SHOP_SELECTION": "Change shop",
  "INVALID_CUSTOMER_HIERARCHY_NUMBER": "Top-level customer may only consist of numbers.",
  "INVALID_CUSTOMER_NUMBER": "The customer number may only consist of numbers.",
  "ED_UOF_ERROR_TABLE_TITLE": "In the uploaded Order document there are erroneous Information",
  "ED_UOF_ERROR_ROW": "Row",
  "ED_UOF_ERROR_CELL": "Column",
  "ED_UOF_ERROR_FIELD_NAME": "Field Name",
  "ED_UOF_ERROR_DESC": "Error Description",
  "ED-ORDER_BINDING_DATE":"Binding delivery date",
  "ED-ORDER_CURRENT_DATE":"Current delivery date",
  "ED-ACCESS_IDENTIFIER1":"Access Identifier",
  "ED-ACCESS_IDENTIFIER2":"Access Identifier 2",
  "ED-ORDER_NUMBER_LABEL":"Order Number",
  "ED-USER_NAME_LABEL":"Username",
  "ED-STATUS_LABEL":"Order Status",
  "ED-CREATED_TIME_LABEL":"Date",
  "ED-ADDITIONAL_CONTACT_1":"Contact person 1",
  "ED-ADDITIONAL_CONTACT_2":"Contact person 2",
  "ED-ARCHIVE_TITLE":"Order archive",
  "ED-ARCHIVE_FILENAME":"File Name",
  "ED-ARCHIVE_USERNAME":"Username",
  "ED-ARCHIVE_DATE":"Created date"
};
