module.exports = [
  {
    "readOnlyVodafoneUser": false,
    "value": "6217f018-c0a8-4dba-0191-851de58fa762",
    "text": "Black Business +",
    "description": "Der Black Business-Tarif ist die hochwertige Leistung für eine höchst anspruchsvolle Zielgruppe. Insbesondere ein neues Premium Smartphone alle 12 Monate sowie einen Footprint für Roaming und internationale Telefonie nicht nur in und nach Europa, sondern auch inklusive der Türkei, den USA und Kanada. National sowie innerhalb dieser Länder sind im Tarif standardmäßig 20 GB Highspeed Datenvolumen inklusive.",
    "type": "VOICE",
    "mandatory": false,
    "show": false,
    "disabled": false,
    "length": 0,
    "excluded": 0,
    "displayOrder": 0,
    "familyName": "Black",
    "amount": 169.95,
    "subsCount": 0,
    "tariffOption": "RB5BLY60"
  },
  {
    "readOnlyVodafoneUser": false,
    "value": "6217f087-c0a8-4dba-0191-851da9e7f80a",
    "text": "Business Active 1 s",
    "description": "Mit den Vodafone Business-Tarifen erhalten Sie als Geschäftskunde ein Tarifangebot, das speziell auf Ihre Anforderungen abgestimmt wurde.",
    "type": "VOICE",
    "mandatory": false,
    "show": false,
    "disabled": false,
    "length": 0,
    "excluded": 0,
    "displayOrder": 0,
    "familyName": "Business",
    "amount": 16,
    "subsCount": 0,
    "tariffOption": "BUACSE01"
  },
  {
    "readOnlyVodafoneUser": false,
    "value": "6217f04a-c0a8-4dba-0191-851d7f52acd8",
    "text": "Business Classic 10 s",
    "description": "Mit den Vodafone Business-Tarifen erhalten Sie als Geschäftskunde ein Tarifangebot, das speziell auf Ihre Anforderungen abgestimmt wurde.",
    "type": "VOICE",
    "mandatory": false,
    "show": false,
    "disabled": false,
    "length": 0,
    "excluded": 0,
    "displayOrder": 0,
    "familyName": "Business",
    "amount": 8.5,
    "subsCount": 0,
    "tariffOption": "PROCLSE10"
  },
  {
    "readOnlyVodafoneUser": false,
    "value": "317e806f-c0a8-4dba-36ba-1a831d5a14d3",
    "text": "Business Classic 60/1 s",
    "description": "Mit den Vodafone Business-Tarifen erhalten Sie als Geschäftskunde ein Tarifangebot, das speziell auf Ihre Anforderungen abgestimmt wurde.",
    "type": "VOICE",
    "mandatory": false,
    "show": false,
    "disabled": false,
    "length": 0,
    "excluded": 0,
    "displayOrder": 0,
    "familyName": "Business",
    "amount": 8,
    "subsCount": 0,
    "tariffOption": "PROCLSE60"
  },
  {
    "readOnlyVodafoneUser": false,
    "value": "6217f033-c0a8-4dba-0191-851d1c09827b",
    "text": "Bus Allnet 60/1 Sub",
    "description": "Optimale Kostensicherheit durch Flatrates.",
    "type": "VOICE",
    "mandatory": false,
    "show": false,
    "disabled": false,
    "length": 0,
    "excluded": 0,
    "displayOrder": 0,
    "familyName": "Business Allnet",
    "amount": 35.95,
    "subsCount": 0,
    "tariffOption": "BALLNTY60"
  },
  {
    "readOnlyVodafoneUser": false,
    "value": "c44a3e79-0a10-ed0e-0556-d1085a725da1",
    "text": "Bus Allnet 60/1 SIM only",
    "description": "Optimale Kostensicherheit durch Flatrates.",
    "type": "SIM_ONLY_VOICE",
    "mandatory": false,
    "show": false,
    "disabled": false,
    "length": 0,
    "excluded": 0,
    "displayOrder": 0,
    "familyName": "Business Allnet",
    "amount": 25.95,
    "subsCount": 0,
    "tariffOption": "BALNTN60"
  },
  {
    "readOnlyVodafoneUser": false,
    "value": "6217f039-c0a8-4dba-0191-851d3845581d",
    "text": "Bus Allnet Basic 60/1 SUB",
    "description": "Optimale Kostensicherheit durch Flatrates.",
    "type": "VOICE",
    "mandatory": false,
    "show": false,
    "disabled": false,
    "length": 0,
    "excluded": 0,
    "displayOrder": 0,
    "familyName": "Business Allnet",
    "amount": 32.95,
    "subsCount": 0,
    "tariffOption": "BABASY60"
  },
  {
    "readOnlyVodafoneUser": false,
    "value": "c44a3e40-0a10-ed0e-0556-d108a7417004",
    "text": "Bus Allnet Basic 60/1 SIM only",
    "description": "Optimale Kostensicherheit durch Flatrates.",
    "type": "SIM_ONLY_VOICE",
    "mandatory": false,
    "show": false,
    "disabled": false,
    "length": 0,
    "excluded": 0,
    "displayOrder": 0,
    "familyName": "Business Allnet",
    "amount": 22.95,
    "subsCount": 0,
    "tariffOption": "BABASN60"
  },
  {
    "readOnlyVodafoneUser": false,
    "value": "6217ee6b-c0a8-4dba-0191-851dab923231",
    "text": "Business Data Pro 6",
    "description": "Keine Beschreibung verfügbar.",
    "type": "DATA",
    "mandatory": false,
    "show": false,
    "disabled": false,
    "length": 0,
    "excluded": 0,
    "displayOrder": 0,
    "familyName": "Data Business",
    "amount": 6,
    "subsCount": 0,
    "tariffOption": "VFDAT_P6B"
  },
  {
    "readOnlyVodafoneUser": false,
    "value": "6217ef3f-c0a8-4dba-0191-851d2598d628",
    "text": "Business Data Einzel",
    "description": "Keine Beschreibung verfügbar.",
    "type": "SIM_ONLY_DATA",
    "mandatory": false,
    "show": false,
    "disabled": false,
    "length": 0,
    "excluded": 0,
    "displayOrder": 0,
    "familyName": "Data Business",
    "amount": 4,
    "subsCount": 0,
    "tariffOption": "VFDAT_BDE"
  },
  {
    "readOnlyVodafoneUser": false,
    "value": "c4430956-0a10-ed0e-0556-d108e19a7245",
    "text": "Mobile Internet Basic",
    "description": "Keine Beschreibung verfügbar.",
    "type": "SIM_ONLY_DATA",
    "mandatory": false,
    "show": false,
    "disabled": false,
    "length": 0,
    "excluded": 0,
    "displayOrder": 0,
    "familyName": "Data Business",
    "amount": 0,
    "subsCount": 0,
    "tariffOption": "DAT_NPAD"
  },
  {
    "readOnlyVodafoneUser": false,
    "value": "c44308bb-0a10-ed0e-0556-d10824b43ff4",
    "text": "Business Data Zusatz",
    "description": "Keine Beschreibung verfügbar.",
    "type": "SIM_ONLY_DATA",
    "mandatory": false,
    "show": false,
    "disabled": false,
    "length": 0,
    "excluded": 0,
    "displayOrder": 0,
    "familyName": "Data Business",
    "amount": 0,
    "subsCount": 0,
    "tariffOption": "VFDAT_BDZ"
  },
  {
    "readOnlyVodafoneUser": false,
    "value": "c443091c-0a10-ed0e-0556-d1087d4ffd72",
    "text": "Mobile Connect Flat 50,0 SIM only",
    "description": "Keine Beschreibung verfügbar.",
    "type": "SIM_ONLY_DATA",
    "mandatory": false,
    "show": false,
    "disabled": false,
    "length": 0,
    "excluded": 0,
    "displayOrder": 0,
    "familyName": "Data Business",
    "amount": 59.95,
    "subsCount": 0,
    "tariffOption": "DAT_NMF50"
  },
  {
    "readOnlyVodafoneUser": false,
    "value": "c4430965-0a10-ed0e-0556-d10801b7ab57",
    "text": "MobileInternet 14,4 SIM only",
    "description": "Keine Beschreibung verfügbar.",
    "type": "SIM_ONLY_DATA",
    "mandatory": false,
    "show": false,
    "disabled": false,
    "length": 0,
    "excluded": 0,
    "displayOrder": 0,
    "familyName": "Mobile Broadband 20",
    "amount": 33.6,
    "subsCount": 0,
    "tariffOption": "MBB3G14N"
  },
  {
    "readOnlyVodafoneUser": false,
    "value": "6217ef4a-c0a8-4dba-0191-851dc47255ec",
    "text": "Mobile Connect Flat SIM only",
    "description": "Wenn Sie ständig im Büro, zu Hause oder unterwegs mit Ihrem Notebook oder Smartphone schnell und günstig online gehen möchten, sind die Vodafone Mobile Connect-Datentarife ideal für Sie.",
    "type": "SIM_ONLY_DATA",
    "mandatory": false,
    "show": false,
    "disabled": false,
    "length": 0,
    "excluded": 0,
    "displayOrder": 0,
    "familyName": "Mobile Connect",
    "amount": 29.37,
    "subsCount": 0,
    "tariffOption": "DAT_NMF"
  },
  {
    "readOnlyVodafoneUser": false,
    "value": "c44486c5-0a10-ed0e-0556-d108e94f0287",
    "text": "Mobile Connect L SIM only",
    "description": "Wenn Sie ständig im Büro, zu Hause oder unterwegs mit Ihrem Notebook oder Smartphone schnell und günstig online gehen möchten, sind die Vodafone Mobile Connect-Datentarife ideal für Sie.",
    "type": "SIM_ONLY_DATA",
    "mandatory": false,
    "show": false,
    "disabled": false,
    "length": 0,
    "excluded": 0,
    "displayOrder": 0,
    "familyName": "Mobile Connect",
    "amount": 16.76,
    "subsCount": 0,
    "tariffOption": "DAT_NML"
  },
  {
    "readOnlyVodafoneUser": false,
    "value": "6217ef06-c0a8-4dba-0191-851dd82bc779",
    "text": "Mobile Connect Europe Large Sub",
    "description": "Wenn Sie ständig im Büro, zu Hause oder unterwegs mit Ihrem Notebook oder Smartphone schnell und günstig online gehen möchten, sind die Vodafone Mobile Connect-Datentarife ideal für Sie.",
    "type": "DATA",
    "mandatory": false,
    "show": false,
    "disabled": false,
    "length": 0,
    "excluded": 0,
    "displayOrder": 0,
    "familyName": "Mobile Connect",
    "amount": 40.97,
    "subsCount": 0,
    "tariffOption": "DAT_YMMLE"
  },
  {
    "readOnlyVodafoneUser": false,
    "value": "c44486e7-0a10-ed0e-0556-d10866abcba0",
    "text": "Mobile Connect World Large SIM Only",
    "description": "Wenn Sie ständig im Büro, zu Hause oder unterwegs mit Ihrem Notebook oder Smartphone schnell und günstig online gehen möchten, sind die Vodafone Mobile Connect-Datentarife ideal für Sie.",
    "type": "SIM_ONLY_DATA",
    "mandatory": false,
    "show": false,
    "disabled": false,
    "length": 0,
    "excluded": 0,
    "displayOrder": 0,
    "familyName": "Mobile Connect",
    "amount": 116.76,
    "subsCount": 0,
    "tariffOption": "DAT_NMMLW"
  },
  {
    "readOnlyVodafoneUser": false,
    "value": "c4430976-0a10-ed0e-0556-d108e5de6a04",
    "text": "Mobile Connect Europe Large SIM Only",
    "description": "Wenn Sie ständig im Büro, zu Hause oder unterwegs mit Ihrem Notebook oder Smartphone schnell und günstig online gehen möchten, sind die Vodafone Mobile Connect-Datentarife ideal für Sie.",
    "type": "SIM_ONLY_DATA",
    "mandatory": false,
    "show": false,
    "disabled": false,
    "length": 0,
    "excluded": 0,
    "displayOrder": 0,
    "familyName": "Mobile Connect",
    "amount": 36.76,
    "subsCount": 0,
    "tariffOption": "DAT_NMMLE"
  },
  {
    "readOnlyVodafoneUser": false,
    "value": "6217ef29-c0a8-4dba-0191-851da041f23e",
    "text": "Mobile Connect L Sub",
    "description": "Wenn Sie ständig im Büro, zu Hause oder unterwegs mit Ihrem Notebook oder Smartphone schnell und günstig online gehen möchten, sind die Vodafone Mobile Connect-Datentarife ideal für Sie.",
    "type": "DATA",
    "mandatory": false,
    "show": false,
    "disabled": false,
    "length": 0,
    "excluded": 0,
    "displayOrder": 0,
    "familyName": "Mobile Connect",
    "amount": 20.97,
    "subsCount": 0,
    "tariffOption": "DAT_YML"
  },
  {
    "readOnlyVodafoneUser": false,
    "value": "c4448684-0a10-ed0e-0556-d10884109d9e",
    "text": "Mobile Connect Flat Light SIM only",
    "description": "Keine Beschreibung verfügbar.",
    "type": "SIM_ONLY_DATA",
    "mandatory": false,
    "show": false,
    "disabled": false,
    "length": 0,
    "excluded": 0,
    "displayOrder": 0,
    "familyName": "Mobile Connect",
    "amount": 19.95,
    "subsCount": 0,
    "tariffOption": "DAT_NMFLG"
  },
  {
    "readOnlyVodafoneUser": false,
    "value": "6217ef22-c0a8-4dba-0191-851da8551043",
    "text": "Mobile Connect Flat Sub",
    "description": "Wenn Sie ständig im Büro, zu Hause oder unterwegs mit Ihrem Notebook oder Smartphone schnell und günstig online gehen möchten, sind die Vodafone Mobile Connect-Datentarife ideal für Sie.",
    "type": "DATA",
    "mandatory": false,
    "show": false,
    "disabled": false,
    "length": 0,
    "excluded": 0,
    "displayOrder": 0,
    "familyName": "Mobile Connect",
    "amount": 33.57,
    "subsCount": 0,
    "tariffOption": "DAT_YMF"
  },
  {
    "readOnlyVodafoneUser": false,
    "value": "c44486d4-0a10-ed0e-0556-d10805cb6f1d",
    "text": "Mobile Connect Large SIM only",
    "description": "Wenn Sie ständig im Büro, zu Hause oder unterwegs mit Ihrem Notebook oder Smartphone schnell und günstig online gehen möchten, sind die Vodafone Mobile Connect-Datentarife ideal für Sie.",
    "type": "SIM_ONLY_DATA",
    "mandatory": false,
    "show": false,
    "disabled": false,
    "length": 0,
    "excluded": 0,
    "displayOrder": 0,
    "familyName": "Mobile Connect",
    "amount": 16.76,
    "subsCount": 0,
    "tariffOption": "DAT_NMML"
  },
  {
    "readOnlyVodafoneUser": false,
    "value": "6217ef14-c0a8-4dba-0191-851d22a98613",
    "text": "Mobile Connect Flat Light Sub",
    "description": "Keine Beschreibung verfügbar.",
    "type": "DATA",
    "mandatory": false,
    "show": false,
    "disabled": false,
    "length": 0,
    "excluded": 0,
    "displayOrder": 0,
    "familyName": "Mobile Connect",
    "amount": 24.15,
    "subsCount": 0,
    "tariffOption": "DAT_YMFLG"
  },
  {
    "readOnlyVodafoneUser": false,
    "value": "6217ef55-c0a8-4dba-0191-851d71867851",
    "text": "Professional XL 1/1 SIM only",
    "description": "Ihnen als Geschäftskunde bieten die Vodafone Professional-Tarife günstige Konditionen und attraktive Vorteile.",
    "type": "SIM_ONLY_VOICE",
    "mandatory": false,
    "show": false,
    "disabled": false,
    "length": 0,
    "excluded": 0,
    "displayOrder": 0,
    "familyName": "Professional",
    "amount": 30,
    "subsCount": 0,
    "tariffOption": "PR_XLN01"
  },
  {
    "readOnlyVodafoneUser": false,
    "value": "c44a3e96-0a10-ed0e-0556-d1089e1af951",
    "text": "Professional L 10/10 SIM only",
    "description": "Ihnen als Geschäftskunde bieten die Vodafone Professional-Tarife günstige Konditionen und attraktive Vorteile.",
    "type": "SIM_ONLY_VOICE",
    "mandatory": false,
    "show": false,
    "disabled": false,
    "length": 0,
    "excluded": 0,
    "displayOrder": 0,
    "familyName": "Professional",
    "amount": 21,
    "subsCount": 0,
    "tariffOption": "PR_LN10"
  },
  {
    "readOnlyVodafoneUser": false,
    "value": "6217f05e-c0a8-4dba-0191-851df22edd62",
    "text": "Europe XL 60/1 Sub",
    "description": "Ihnen als Geschäftskunde bieten die Vodafone Professional-Tarife günstige Konditionen und attraktive Vorteile.",
    "type": "VOICE",
    "mandatory": false,
    "show": false,
    "disabled": false,
    "length": 0,
    "excluded": 0,
    "displayOrder": 0,
    "familyName": "Professional",
    "amount": 96.5,
    "subsCount": 0,
    "tariffOption": "PR_EXLY60"
  },
  {
    "readOnlyVodafoneUser": false,
    "value": "6217f07d-c0a8-4dba-0191-851d21302278",
    "text": "Europe L 60/1 Sub",
    "description": "Keine Beschreibung verfügbar.",
    "type": "VOICE",
    "mandatory": false,
    "show": false,
    "disabled": false,
    "length": 0,
    "excluded": 0,
    "displayOrder": 0,
    "familyName": "Professional",
    "amount": 84.5,
    "subsCount": 0,
    "tariffOption": "PR_ELY60"
  },
  {
    "readOnlyVodafoneUser": false,
    "value": "6217f068-c0a8-4dba-0191-851d395be420",
    "text": "Professional L 1/1 Sub",
    "description": "Ihnen als Geschäftskunde bieten die Vodafone Professional-Tarife günstige Konditionen und attraktive Vorteile.",
    "type": "VOICE",
    "mandatory": false,
    "show": false,
    "disabled": false,
    "length": 0,
    "excluded": 0,
    "displayOrder": 0,
    "familyName": "Professional",
    "amount": 30.5,
    "subsCount": 0,
    "tariffOption": "PR_LY01"
  },
  {
    "readOnlyVodafoneUser": false,
    "value": "c44a3eb6-0a10-ed0e-0556-d108ef951c44",
    "text": "Professional L 1/1 SIM only",
    "description": "Ihnen als Geschäftskunde bieten die Vodafone Professional-Tarife günstige Konditionen und attraktive Vorteile.",
    "type": "SIM_ONLY_VOICE",
    "mandatory": false,
    "show": false,
    "disabled": false,
    "length": 0,
    "excluded": 0,
    "displayOrder": 0,
    "familyName": "Professional",
    "amount": 23,
    "subsCount": 0,
    "tariffOption": "PR_LN01"
  },
  {
    "readOnlyVodafoneUser": false,
    "value": "9b91e65e-c0a8-4dba-2f34-fe3419549049",
    "text": "Professional Plus XL D1 60/1 Sub",
    "description": "Mit den Vodafone Professional Plus Tarifen stehen Ihnen verschiedene Flatrates zur Verfügung, die speziell auf die Nutzung mit einem Smartphone zugeschnitten sind.",
    "type": "VOICE",
    "mandatory": false,
    "show": false,
    "disabled": false,
    "length": 0,
    "excluded": 0,
    "displayOrder": 0,
    "familyName": "Professional Plus",
    "amount": 44.95,
    "subsCount": 0,
    "tariffOption": "PRPXL1Y60"
  },
  {
    "readOnlyVodafoneUser": false,
    "value": "6217f08c-c0a8-4dba-0191-851df1c5ee93",
    "text": "Red Business L 60/1 Sub",
    "description": "Entspannt telefonieren, SMS verschicken und mobil surfen. In Deutschland und Europa.",
    "type": "VOICE",
    "mandatory": false,
    "show": false,
    "disabled": false,
    "length": 0,
    "excluded": 0,
    "displayOrder": 0,
    "familyName": "RED Business",
    "amount": 109.95,
    "subsCount": 0,
    "tariffOption": "RBLY60"
  },
  {
    "readOnlyVodafoneUser": false,
    "value": "6217f09a-c0a8-4dba-0191-851de51d32d4",
    "text": "Red Bus XS 60/1 Sub",
    "description": "Entspannt telefonieren, SMS verschicken und mobil surfen. In Deutschland und Europa.",
    "type": "VOICE",
    "mandatory": false,
    "show": false,
    "disabled": false,
    "length": 0,
    "excluded": 0,
    "displayOrder": 0,
    "familyName": "RED Business",
    "amount": 39.95,
    "subsCount": 0,
    "tariffOption": "RBXSY60"
  },
  {
    "readOnlyVodafoneUser": false,
    "value": "6217f09f-c0a8-4dba-0191-851d12c99a6b",
    "text": "Vodafone Red Business M+",
    "description": "Entspannt telefonieren, SMS verschicken und mobil surfen. In Deutschland und Europa.",
    "type": "VOICE",
    "mandatory": false,
    "show": false,
    "disabled": false,
    "length": 0,
    "excluded": 0,
    "displayOrder": 0,
    "familyName": "RED Business",
    "amount": 69.95,
    "subsCount": 0,
    "tariffOption": "RB5MY60"
  },
  {
    "readOnlyVodafoneUser": false,
    "value": "c445d22b-0a10-ed0e-0556-d10804022614",
    "text": "Red Business Data Premium SIM only",
    "description": "Mit Vodafone Red Business Data finden Sie für Ihren Bedarf die richtige Lösung. Dank Flats können Sie jederzeit ohne Kostendruck mobil im Internet surfen oder Daten aus Ihrem Firmennetz abrufen. Optimal für mobiles Arbeiten mit Smartphone, Tablet oder Notebook.",
    "type": "SIM_ONLY_DATA",
    "mandatory": false,
    "show": false,
    "disabled": false,
    "length": 0,
    "excluded": 0,
    "displayOrder": 0,
    "familyName": "RED Business Data",
    "amount": 99.95,
    "subsCount": 0,
    "tariffOption": "RBD_NPREM"
  },
  {
    "readOnlyVodafoneUser": false,
    "value": "c445d0bb-0a10-ed0e-0556-d1089b3652ae",
    "text": "Red Business Data XL SIM only",
    "description": "Mit Vodafone Red Business Data finden Sie für Ihren Bedarf die richtige Lösung. Dank Flats können Sie jederzeit ohne Kostendruck mobil im Internet surfen oder Daten aus Ihrem Firmennetz abrufen. Optimal für mobiles Arbeiten mit Smartphone, Tablet oder Notebook.",
    "type": "SIM_ONLY_DATA",
    "mandatory": false,
    "show": false,
    "disabled": false,
    "length": 0,
    "excluded": 0,
    "displayOrder": 0,
    "familyName": "RED Business Data",
    "amount": 39.95,
    "subsCount": 0,
    "tariffOption": "RBD_NXL"
  },
  {
    "readOnlyVodafoneUser": false,
    "value": "c445d233-0a10-ed0e-0556-d1087493d380",
    "text": "Red Business Data M SIM only",
    "description": "Mit Vodafone Red Business Data finden Sie für Ihren Bedarf die richtige Lösung. Dank Flats können Sie jederzeit ohne Kostendruck mobil im Internet surfen oder Daten aus Ihrem Firmennetz abrufen. Optimal für mobiles Arbeiten mit Smartphone, Tablet oder Notebook.",
    "type": "SIM_ONLY_DATA",
    "mandatory": false,
    "show": false,
    "disabled": false,
    "length": 0,
    "excluded": 0,
    "displayOrder": 0,
    "familyName": "RED Business Data",
    "amount": 19.95,
    "subsCount": 0,
    "tariffOption": "RBD_NM"
  },
  {
    "readOnlyVodafoneUser": false,
    "value": "6217ef50-c0a8-4dba-0191-851d7b596ddd",
    "text": "Red Business Data S SIM only",
    "description": "Mit Vodafone Red Business Data finden Sie für Ihren Bedarf die richtige Lösung. Dank Flats können Sie jederzeit ohne Kostendruck mobil im Internet surfen oder Daten aus Ihrem Firmennetz abrufen. Optimal für mobiles Arbeiten mit Smartphone, Tablet oder Notebook.",
    "type": "SIM_ONLY_DATA",
    "mandatory": false,
    "show": false,
    "disabled": false,
    "length": 0,
    "excluded": 0,
    "displayOrder": 0,
    "familyName": "RED Business Data",
    "amount": 12.95,
    "subsCount": 0,
    "tariffOption": "RBD_NS"
  },
  {
    "readOnlyVodafoneUser": false,
    "value": "6217eefc-c0a8-4dba-0191-851df80c110b",
    "text": "Red Business Data XL Sub",
    "description": "Mit Vodafone Red Business Data finden Sie für Ihren Bedarf die richtige Lösung. Dank Flats können Sie jederzeit ohne Kostendruck mobil im Internet surfen oder Daten aus Ihrem Firmennetz abrufen. Optimal für mobiles Arbeiten mit Smartphone, Tablet oder Notebook.",
    "type": "DATA",
    "mandatory": false,
    "show": false,
    "disabled": false,
    "length": 0,
    "excluded": 0,
    "displayOrder": 0,
    "familyName": "RED Business Data",
    "amount": 49.95,
    "subsCount": 0,
    "tariffOption": "RBD_YXL"
  },
  {
    "readOnlyVodafoneUser": false,
    "value": "6217ef3a-c0a8-4dba-0191-851d37a790c2",
    "text": "Red Business Data S Sub",
    "description": "Mit Vodafone Red Business Data finden Sie für Ihren Bedarf die richtige Lösung. Dank Flats können Sie jederzeit ohne Kostendruck mobil im Internet surfen oder Daten aus Ihrem Firmennetz abrufen. Optimal für mobiles Arbeiten mit Smartphone, Tablet oder Notebook.",
    "type": "DATA",
    "mandatory": false,
    "show": false,
    "disabled": false,
    "length": 0,
    "excluded": 0,
    "displayOrder": 0,
    "familyName": "RED Business Data",
    "amount": 22.95,
    "subsCount": 0,
    "tariffOption": "RBD_YS"
  },
  {
    "readOnlyVodafoneUser": false,
    "value": "6217ef45-c0a8-4dba-0191-851d3286cee0",
    "text": "Red Business Data L SIM only",
    "description": "Mit Vodafone Red Business Data finden Sie für Ihren Bedarf die richtige Lösung. Dank Flats können Sie jederzeit ohne Kostendruck mobil im Internet surfen oder Daten aus Ihrem Firmennetz abrufen. Optimal für mobiles Arbeiten mit Smartphone, Tablet oder Notebook.",
    "type": "SIM_ONLY_DATA",
    "mandatory": false,
    "show": false,
    "disabled": false,
    "length": 0,
    "excluded": 0,
    "displayOrder": 0,
    "familyName": "RED Business Data",
    "amount": 24.95,
    "subsCount": 0,
    "tariffOption": "RBD_NL"
  },
  {
    "readOnlyVodafoneUser": false,
    "value": "6217f02e-c0a8-4dba-0191-851d23243c66",
    "text": "WirelessOffice 60/1 s",
    "description": "Keine Beschreibung verfügbar.",
    "type": "VOICE",
    "mandatory": false,
    "show": false,
    "disabled": false,
    "length": 0,
    "excluded": 0,
    "displayOrder": 0,
    "familyName": "WirelessOffice",
    "amount": 36,
    "subsCount": 0,
    "tariffOption": "VF_WOFF60"
  }
];