module.exports = {
  "hideDebitorDetails": "N",
  "hideNewDebitor": "Y",
  "debitors": [
    {
      "addressId": "f02bf69f-c0a8-4dba-4070-9312b52da72b",
      "country": "Deutschland",
      "city": "aber",
      "houseNumber": "54543",
      "postalCode": "6436436",
      "streetName": "techfund debitor",
      "street1": "techfund debitor",
      "billingAddress": false,
      "shippingAddress": false,
      "countryCode": "D",
      "debitorNumber": "100000",
      "debitorType": "T",
      "debitorId": "20440a3e-8506-7db2-e053-404c070a91f2",
      "associated": true,
      "badDebitorInformation": false,
      "vodafoneUser": true,
      "modified": false,
      "default": true,
      "readOnly": false
    },
    {
      "addressId": "50ac5caf-c0a8-4da3-1860-3b7c1a62b318",
      "country": "Deutschland",
      "city": "City",
      "houseNumber": "55",
      "postalCode": "12387",
      "streetName": "Street",
      "street1": "Kundenname1",
      "street2": "Kundenname2",
      "billingAddress": false,
      "shippingAddress": false,
      "countryCode": "D",
      "debitorNumber": "11223344",
      "debitorType": "D",
      "debitorId": "1dd4303f-b014-5450-e053-404c070a5a19",
      "associated": true,
      "badDebitorInformation": false,
      "vodafoneUser": true,
      "modified": false,
      "default": false,
      "readOnly": false
    },
    {
      "addressId": "efa708c2-c0a8-4dba-3280-73f0ce49af69",
      "country": "Deutschland",
      "city": "gALWAY",
      "houseNumber": "49823",
      "postalCode": "453543",
      "streetName": "STREET",
      "street1": "K1- TECHFUND",
      "street2": "K2",
      "billingAddress": false,
      "shippingAddress": false,
      "countryCode": "D",
      "debitorNumber": "112233",
      "debitorType": "T",
      "debitorId": "efa708c1-c0a8-4dba-3280-73f035055bf9",
      "associated": true,
      "badDebitorInformation": true,
      "vodafoneUser": true,
      "modified": false,
      "default": false,
      "readOnly": true
    },
    {
      "addressId": "14512dfb-c0a8-4dba-437f-9d47d0f3dfeb",
      "country": "Deutschland",
      "poBox": "7897987979",
      "city": "Berlin",
      "postalCode": "145236",
      "street1": "verified techfund debitor",
      "street2": "k2",
      "street3": "k3",
      "street4": "k4",
      "billingAddress": false,
      "shippingAddress": false,
      "countryCode": "D",
      "debitorNumber": "150928",
      "debitorType": "T",
      "debitorId": "20d06e80-b327-31f8-e053-404c070a5559",
      "associated": true,
      "badDebitorInformation": false,
      "vodafoneUser": true,
      "modified": false,
      "default": false,
      "readOnly": false
    },
    {
      "addressId": "fa87f17c-c0a8-4dba-7e3c-462ddbc417d4",
      "country": "Deutschland",
      "city": "aber",
      "houseNumber": "5343",
      "postalCode": "6436436",
      "streetName": "street",
      "street1": "Blacklisted",
      "street2": "TECHFUND DEBITOR",
      "street3": "k3",
      "street4": "k4",
      "billingAddress": false,
      "shippingAddress": false,
      "countryCode": "D",
      "debitorNumber": "666666",
      "debitorType": "T",
      "debitorId": "fa87f17b-c0a8-4dba-7e3c-462ddd6b3f35",
      "associated": true,
      "badDebitorInformation": true,
      "vodafoneUser": true,
      "modified": false,
      "default": false,
      "readOnly": true
    },
    {
      "addressId": "f4baf4ff-c0a8-4dba-3280-73f0719c170e",
      "country": "Großbritannien",
      "city": "sLONDON",
      "houseNumber": "434",
      "postalCode": "432432423",
      "streetName": "sTREEET",
      "street1": "New Debitor",
      "street2": "Kundenname 2",
      "street3": "kundenname 3",
      "street4": "kundenname 4",
      "billingAddress": false,
      "shippingAddress": false,
      "countryCode": "GB",
      "debitorNumber": "150922",
      "debitorType": "D",
      "debitorId": "2054fa50-5058-42c7-e053-424c070ae8fa",
      "associated": true,
      "badDebitorInformation": false,
      "vodafoneUser": true,
      "modified": false,
      "default": false,
      "readOnly": false
    },
    {
      "addressId": "fa17aaf1-c0a8-4dba-7e3c-462d6d1141c6",
      "country": "Belgien",
      "city": "Brussels",
      "houseNumber": "5435",
      "postalCode": "32432",
      "streetName": "Street",
      "street1": "Standard Debitor",
      "billingAddress": false,
      "shippingAddress": false,
      "countryCode": "B",
      "debitorNumber": "230915",
      "debitorType": "D",
      "debitorId": "2069bd85-77a4-5959-e053-424c070aad0f",
      "associated": true,
      "badDebitorInformation": true,
      "vodafoneUser": true,
      "modified": false,
      "default": false,
      "readOnly": true
    },
    {
      "addressId": "fa8082f5-c0a8-4dba-7e3c-462d2d107bdc",
      "country": "Deutschland",
      "city": "Berlin",
      "houseNumber": "43432",
      "postalCode": "43232",
      "streetName": "street",
      "street1": "Blacklisted Debitor",
      "street2": "k2",
      "billingAddress": false,
      "shippingAddress": false,
      "countryCode": "D",
      "debitorNumber": "999999",
      "debitorType": "T",
      "debitorId": "fa8082f5-c0a8-4dba-7e3c-462dab2a21e0",
      "associated": true,
      "badDebitorInformation": true,
      "vodafoneUser": true,
      "modified": false,
      "default": false,
      "readOnly": true
    },
    {
      "addressId": "05002159-c0a8-4dba-437f-9d473cd81bba",
      "country": "Deutschland",
      "city": "Berlin",
      "houseNumber": "545435",
      "postalCode": "5434534",
      "streetName": "street",
      "street1": "new techfund debitor",
      "street2": "k2",
      "street3": "k3",
      "street4": "k4",
      "billingAddress": false,
      "shippingAddress": false,
      "countryCode": "D",
      "debitorNumber": "250915",
      "debitorType": "T",
      "debitorId": "20942112-7739-0687-e053-424c070adfa8",
      "associated": true,
      "badDebitorInformation": false,
      "vodafoneUser": true,
      "modified": false,
      "default": false,
      "readOnly": false
    },
    {
      "addressId": "f4d314bd-c0a8-4dba-4070-9312a7b60517",
      "country": "Deutschland",
      "city": "AAAA",
      "houseNumber": "43",
      "postalCode": "433434",
      "streetName": "AAAA",
      "street1": "AAAA",
      "street2": "AAAA",
      "street3": "AAAA",
      "street4": "AAAA",
      "billingAddress": false,
      "shippingAddress": false,
      "countryCode": "D",
      "debitorNumber": "434343",
      "debitorType": "T",
      "debitorId": "20553487-ca74-1366-e053-404c070a08bd",
      "associated": true,
      "badDebitorInformation": false,
      "vodafoneUser": true,
      "modified": false,
      "default": false,
      "readOnly": false
    },
    {
      "addressId": "f4e12c08-c0a8-4dba-4070-9312f9bb81ac",
      "country": "Deutschland",
      "city": "rere",
      "houseNumber": "43",
      "postalCode": "34434334",
      "streetName": "erer",
      "street1": "eer",
      "street2": "rerer",
      "street3": "erer",
      "street4": "rere",
      "billingAddress": false,
      "shippingAddress": false,
      "countryCode": "D",
      "debitorNumber": "333333",
      "debitorType": "T",
      "debitorId": "20553487-ca7a-1366-e053-404c070a08bd",
      "associated": true,
      "badDebitorInformation": false,
      "vodafoneUser": true,
      "modified": false,
      "default": false,
      "readOnly": false
    },
    {
      "addressId": "f993f961-c0a8-4dba-4070-9312cd3642dc",
      "country": "Deutschland",
      "poBox": "7879456464",
      "city": "Berlin",
      "postalCode": "1025478",
      "street1": "Verified Techfund Debitor",
      "street2": "k2",
      "street3": "k3",
      "billingAddress": false,
      "shippingAddress": false,
      "countryCode": "D",
      "debitorNumber": "000004",
      "debitorType": "T",
      "debitorId": "20668fda-563b-6326-e053-404c070a2110",
      "associated": true,
      "badDebitorInformation": false,
      "vodafoneUser": true,
      "modified": false,
      "default": false,
      "readOnly": false
    },
    {
      "addressId": "f9f6ac1b-c0a8-4dba-0016-a0bd07443dfd",
      "country": "Irland",
      "city": "Galway",
      "houseNumber": "3232",
      "postalCode": "43232432",
      "streetName": "Street",
      "street1": "Techfund Debitor",
      "street2": "k2",
      "street3": "k3",
      "street4": "k4",
      "billingAddress": false,
      "shippingAddress": false,
      "countryCode": "IRL",
      "debitorNumber": "000005",
      "debitorType": "T",
      "debitorId": "20696b80-a2c7-0b07-e053-424c070a2c92",
      "associated": true,
      "badDebitorInformation": false,
      "vodafoneUser": true,
      "modified": false,
      "default": false,
      "readOnly": false
    },
    {
      "addressId": "22893397-c0a8-4dba-437f-9d4778d99a28",
      "country": "Deutschland",
      "city": "Berlin",
      "houseNumber": "125b",
      "postalCode": "6436436",
      "streetName": "techfund debitor city",
      "street1": "techfund debitor 1",
      "street2": "TECHFUND DEBITOR 2",
      "street3": "k3",
      "street4": "k4",
      "billingAddress": false,
      "shippingAddress": false,
      "countryCode": "D",
      "debitorNumber": "011015",
      "debitorType": "T",
      "debitorId": "210a9009-7756-765f-e053-424c070aa43a",
      "associated": true,
      "badDebitorInformation": false,
      "vodafoneUser": true,
      "modified": false,
      "default": false,
      "readOnly": false
    },
    {
      "addressId": "18f6cd5b-c0a8-4dba-437f-9d47fb209cdc",
      "country": "Finnland",
      "city": "eres",
      "houseNumber": "333",
      "postalCode": "43534",
      "streetName": "fg",
      "street1": "fg",
      "street2": "fgffffffff",
      "billingAddress": false,
      "shippingAddress": false,
      "countryCode": "SF",
      "debitorNumber": "969696",
      "debitorType": "T",
      "debitorId": "21fb9814-ddb4-4701-e053-424c070a9df9",
      "associated": true,
      "badDebitorInformation": false,
      "vodafoneUser": true,
      "modified": false,
      "default": false,
      "readOnly": false
    },
    {
      "addressId": "37e2fde1-c0a8-4dba-0622-884d1b653fd8",
      "country": "Deutschland",
      "poBox": "34322342",
      "city": "Berlin",
      "postalCode": "424342",
      "street1": "Techfund k1",
      "street2": "k2",
      "street3": "k3",
      "street4": "k4",
      "billingAddress": false,
      "shippingAddress": false,
      "countryCode": "D",
      "debitorNumber": "051015",
      "debitorType": "T",
      "debitorId": "215b54e8-2552-35c7-e053-404c070add21",
      "associated": true,
      "badDebitorInformation": false,
      "vodafoneUser": true,
      "modified": false,
      "default": false,
      "readOnly": false
    },
    {
      "addressId": "f93b29f8-c0a8-4dba-4070-9312a397f99f",
      "country": "Deutschland",
      "city": "fdfd",
      "houseNumber": "443",
      "postalCode": "4344343",
      "streetName": "fdfd",
      "street1": "dfdf",
      "street2": "fd",
      "street3": "fdfd",
      "street4": "dffd",
      "billingAddress": false,
      "shippingAddress": false,
      "countryCode": "D",
      "debitorNumber": "999072",
      "debitorType": "D",
      "debitorId": "210c4e26-617e-5ca9-e053-424c070acba8",
      "associated": true,
      "badDebitorInformation": false,
      "vodafoneUser": true,
      "modified": false,
      "default": false,
      "readOnly": false
    },
    {
      "addressId": "374ead04-c0a8-4dba-4496-5b287aab2f05",
      "country": "Deutschland",
      "city": "Brussels",
      "houseNumber": "545n",
      "postalCode": "32432",
      "streetName": "street",
      "street1": "Standard Debitor",
      "street2": "k2",
      "billingAddress": false,
      "shippingAddress": false,
      "countryCode": "D",
      "debitorNumber": "121212",
      "debitorType": "D",
      "debitorId": "21590b54-6f94-2728-e053-404c070a371a",
      "associated": true,
      "badDebitorInformation": false,
      "vodafoneUser": true,
      "modified": false,
      "default": false,
      "readOnly": false
    },
    {
      "addressId": "4c4d0444-c0a8-4dba-22fc-94a1878ebd2a",
      "country": "Deutschland",
      "city": "reere",
      "houseNumber": "32",
      "postalCode": "23232323",
      "streetName": "Standard1",
      "street1": "Standard1",
      "street2": "Standard2",
      "street3": "Standard3",
      "street4": "Standard",
      "billingAddress": false,
      "shippingAddress": false,
      "countryCode": "D",
      "debitorNumber": "156987",
      "debitorType": "T",
      "debitorId": "21ab0ccf-5fd8-6a2f-e053-424c070a4c3d",
      "associated": true,
      "badDebitorInformation": false,
      "vodafoneUser": true,
      "modified": false,
      "default": false,
      "readOnly": false
    },
    {
      "addressId": "66737ce9-c0a8-4dba-753a-79f54bcfd2f9",
      "country": "Deutschland",
      "poBox": "1478452",
      "city": "Berlin",
      "postalCode": "187452",
      "street1": "new debitor",
      "street2": "k2",
      "street3": "k3",
      "street4": "k4",
      "billingAddress": false,
      "shippingAddress": false,
      "countryCode": "D",
      "debitorNumber": "141015",
      "debitorType": "D",
      "debitorId": "22113313-d7ab-73cd-e053-424c070af50a",
      "associated": true,
      "badDebitorInformation": false,
      "vodafoneUser": true,
      "modified": false,
      "default": false,
      "readOnly": false
    },
    {
      "addressId": "1844b7fd-c0a8-4dba-437f-9d47462e53e5",
      "country": "Deutschland",
      "city": "Berlin",
      "houseNumber": "543",
      "postalCode": "6436436",
      "streetName": "techfund debitor street",
      "street1": "techfund debitor 1",
      "street2": "TECHFUND DEBITOR 2",
      "billingAddress": false,
      "shippingAddress": false,
      "countryCode": "D",
      "debitorNumber": "000003",
      "debitorType": "T",
      "debitorId": "20dfd743-49e1-2d26-e053-404c070ad1d0",
      "associated": true,
      "badDebitorInformation": false,
      "vodafoneUser": true,
      "modified": false,
      "default": false,
      "readOnly": false
    },
    {
      "addressId": "17dde026-c0a8-4dba-437f-9d47dd0c77bb",
      "country": "Deutschland",
      "city": "gdfg",
      "houseNumber": "22",
      "postalCode": "333333",
      "streetName": "asd",
      "street1": "gdfds",
      "street2": "ss",
      "billingAddress": false,
      "shippingAddress": false,
      "countryCode": "D",
      "debitorNumber": "297100",
      "debitorType": "T",
      "debitorId": "20e16adf-98f0-0cf1-e053-404c070a1ba3",
      "associated": true,
      "badDebitorInformation": false,
      "vodafoneUser": true,
      "modified": false,
      "default": false,
      "readOnly": false
    },
    {
      "addressId": "191a629f-c0a8-4dba-437f-9d47f1fbf235",
      "country": "Deutschland",
      "city": "aber",
      "houseNumber": "567576",
      "postalCode": "6436436",
      "streetName": "techfund debitor",
      "street1": "techfund debitor",
      "street2": "TECHFUND DEBITOR",
      "billingAddress": false,
      "shippingAddress": false,
      "countryCode": "D",
      "debitorNumber": "000006",
      "debitorType": "T",
      "debitorId": "20e53016-d500-33d8-e053-404c070a9e09",
      "associated": true,
      "badDebitorInformation": false,
      "vodafoneUser": true,
      "modified": false,
      "default": false,
      "readOnly": false
    },
    {
      "addressId": "f93b29f8-c0a8-4dba-4070-9312a397f99f",
      "country": "Deutschland",
      "city": "fdfd",
      "houseNumber": "443",
      "postalCode": "4344343",
      "streetName": "fdfd",
      "street1": "dfdf",
      "street2": "fd",
      "street3": "fdfd",
      "street4": "dffd",
      "billingAddress": false,
      "shippingAddress": false,
      "countryCode": "D",
      "debitorNumber": "999071",
      "debitorType": "T",
      "debitorId": "210c0d98-bfac-35f9-e053-424c070a7219",
      "associated": true,
      "badDebitorInformation": false,
      "vodafoneUser": true,
      "modified": false,
      "default": false,
      "readOnly": false
    },
    {
      "addressId": "28606ed0-c0a8-4dba-20e4-2cb58d0b643f",
      "country": "Deutschland",
      "city": "qwert",
      "houseNumber": "1",
      "postalCode": "12365",
      "streetName": "Elms",
      "street1": "Chunyang",
      "billingAddress": false,
      "shippingAddress": false,
      "countryCode": "D",
      "debitorNumber": "021015",
      "debitorType": "T",
      "debitorId": "28606ed0-c0a8-4dba-20e4-2cb573b822e9",
      "associated": true,
      "badDebitorInformation": false,
      "vodafoneUser": true,
      "modified": false,
      "default": false,
      "readOnly": false
    },
    {
      "addressId": "28d580ea-c0a8-4dba-6387-c7b9ab52022b",
      "country": "Deutschland",
      "city": "qwert",
      "houseNumber": "1",
      "postalCode": "12365",
      "streetName": "elms",
      "street1": "chunyang",
      "billingAddress": false,
      "shippingAddress": false,
      "countryCode": "D",
      "debitorNumber": "147852",
      "debitorType": "D",
      "debitorId": "2120fb4a-2326-5300-e053-424c070a2a20",
      "associated": true,
      "badDebitorInformation": false,
      "vodafoneUser": true,
      "modified": false,
      "default": false,
      "readOnly": false
    },
    {
      "addressId": "70698afe-c0a8-4dba-7b4b-02d97a8ecaf2",
      "country": "Deutschland",
      "city": "berlin",
      "houseNumber": "55345",
      "postalCode": "54354353",
      "streetName": "street",
      "street1": "techfund k1",
      "street2": "k2",
      "street3": "k3",
      "street4": "k4- edit",
      "billingAddress": false,
      "shippingAddress": false,
      "countryCode": "D",
      "debitorNumber": "151002",
      "debitorType": "T",
      "debitorId": "70698afd-c0a8-4dba-7b4b-02d91a64891e",
      "associated": true,
      "badDebitorInformation": false,
      "vodafoneUser": true,
      "modified": false,
      "default": false,
      "readOnly": false
    },
    {
      "addressId": "1aaac772-c0a8-4da8-5600-e6ffc350a58f",
      "country": "Dänemark",
      "city": "Stadt in Danemark",
      "houseNumber": "23",
      "postalCode": "12345",
      "streetName": "TF Street",
      "street1": "TF Konto namme 1",
      "billingAddress": false,
      "shippingAddress": false,
      "countryCode": "DK",
      "debitorNumber": "888888",
      "debitorType": "T",
      "debitorId": "24e78dd0-f536-6632-e053-424c070a77f2",
      "associated": true,
      "badDebitorInformation": false,
      "vodafoneUser": true,
      "modified": false,
      "default": false,
      "readOnly": false
    },
    {
      "addressId": "38fe4c79-c0a8-4da8-1f04-9b5376ce3dc7",
      "country": "Deutschland",
      "city": "rdrfedr",
      "houseNumber": "34",
      "postalCode": "434343",
      "streetName": "sdsd",
      "street1": "sds",
      "street2": "sd",
      "billingAddress": false,
      "shippingAddress": false,
      "countryCode": "D",
      "debitorNumber": "546576",
      "debitorType": "T",
      "debitorId": "2547ab44-ecbb-131b-e053-424c070ad72b",
      "associated": true,
      "badDebitorInformation": false,
      "vodafoneUser": true,
      "modified": false,
      "default": false,
      "readOnly": false
    },
    {
      "addressId": "1af23e8e-c0a8-4da8-5600-e6ff9b3a2a0f",
      "country": "Deutschland",
      "city": "Deb City",
      "houseNumber": "77",
      "postalCode": "32154",
      "streetName": "Deb Street",
      "street1": "Deb 1",
      "billingAddress": false,
      "shippingAddress": false,
      "countryCode": "D",
      "debitorNumber": "777999",
      "debitorType": "T",
      "debitorId": "24d24a70-edda-6038-e053-404c070a7610",
      "associated": true,
      "badDebitorInformation": false,
      "vodafoneUser": true,
      "modified": false,
      "default": false,
      "readOnly": false
    },
    {
      "addressId": "1f1dcd18-c0a8-4da8-5600-e6ff418ed69a",
      "country": "Deutschland",
      "city": "Tech City",
      "houseNumber": "55",
      "postalCode": "76545",
      "streetName": "Tech Street",
      "street1": "Tech Deb 1",
      "billingAddress": false,
      "shippingAddress": false,
      "countryCode": "D",
      "debitorNumber": "778899",
      "debitorType": "T",
      "debitorId": "24e79738-8fb6-1f0f-e053-424c070a4777",
      "associated": true,
      "badDebitorInformation": false,
      "vodafoneUser": true,
      "modified": false,
      "default": false,
      "readOnly": false
    },
    {
      "addressId": "3910298d-c0a8-4da8-1f04-9b5381b1206f",
      "country": "Deutschland",
      "city": "fdfdfddf",
      "houseNumber": "43",
      "postalCode": "4444343",
      "streetName": "dffd",
      "street1": "fdf",
      "street2": "fd",
      "billingAddress": false,
      "shippingAddress": false,
      "countryCode": "D",
      "debitorNumber": "890976",
      "debitorType": "T",
      "debitorId": "254801eb-056d-4ae1-e053-424c070ad965",
      "associated": true,
      "badDebitorInformation": false,
      "vodafoneUser": true,
      "modified": false,
      "default": false,
      "readOnly": false
    },
    {
      "addressId": "00320d7d-c0a8-4da8-693b-3cc7e69791ee",
      "country": "Deutschland",
      "city": "Berlin",
      "houseNumber": "4646",
      "postalCode": "7410256",
      "streetName": "street",
      "street1": "invalid techfund debitor",
      "billingAddress": false,
      "shippingAddress": false,
      "countryCode": "D",
      "debitorNumber": "000001",
      "debitorType": "T",
      "debitorId": "00320d7c-c0a8-4da8-693b-3cc7ba40914e",
      "associated": true,
      "badDebitorInformation": true,
      "vodafoneUser": true,
      "modified": false,
      "default": false,
      "readOnly": true
    },
    {
      "addressId": "0033fd88-c0a8-4da8-693b-3cc788877cfc",
      "country": "Deutschland",
      "city": "Bonn",
      "houseNumber": "465",
      "postalCode": "6436436",
      "streetName": "techfund debitor",
      "street1": "techfund debitor",
      "billingAddress": false,
      "shippingAddress": false,
      "countryCode": "D",
      "debitorNumber": "000002",
      "debitorType": "T",
      "debitorId": "0033fd88-c0a8-4da8-693b-3cc7984836b9",
      "associated": true,
      "badDebitorInformation": false,
      "vodafoneUser": true,
      "modified": false,
      "default": false,
      "readOnly": false
    },
    {
      "addressId": "003a35d8-c0a8-4da8-3d91-00df389e1b67",
      "country": "Deutschland",
      "city": "TF City",
      "houseNumber": "77",
      "postalCode": "65487",
      "streetName": "TF Street",
      "street1": "TFKund 1",
      "billingAddress": false,
      "shippingAddress": false,
      "countryCode": "D",
      "debitorNumber": "444555",
      "debitorType": "T",
      "debitorId": "2469fac3-d10e-5a0f-e053-404c070a68c1",
      "associated": true,
      "badDebitorInformation": false,
      "vodafoneUser": true,
      "modified": false,
      "default": false,
      "readOnly": false
    },
    {
      "addressId": "1fa7ad6a-c0a8-4da8-5600-e6ff58c01763",
      "country": "Deutschland",
      "city": "Berlin",
      "houseNumber": "43434",
      "postalCode": "5348593457",
      "streetName": "street",
      "street1": "techfund",
      "street2": "k2",
      "billingAddress": false,
      "shippingAddress": false,
      "countryCode": "D",
      "debitorNumber": "191115",
      "debitorType": "T",
      "debitorId": "24e4bb4f-f59c-78b7-e053-424c070a6e91",
      "associated": true,
      "badDebitorInformation": false,
      "vodafoneUser": true,
      "modified": false,
      "default": false,
      "readOnly": false
    },
    {
      "addressId": "1ff1b658-c0a8-4da8-5600-e6ffaa2dc86c",
      "country": "Deutschland",
      "city": "Galway",
      "houseNumber": "43433",
      "postalCode": "434343",
      "streetName": "street",
      "street1": "techfund",
      "street2": "k2",
      "street3": "k3",
      "billingAddress": false,
      "shippingAddress": false,
      "countryCode": "D",
      "debitorNumber": "151119",
      "debitorType": "T",
      "debitorId": "24e5f4bf-901a-3b04-e053-424c070a666a",
      "associated": true,
      "badDebitorInformation": false,
      "vodafoneUser": true,
      "modified": false,
      "default": false,
      "readOnly": false
    },
    {
      "addressId": "49848068-c0a8-4da8-0340-c05cfde2e38d",
      "country": "Deutschland",
      "city": "Bonn",
      "houseNumber": "323423",
      "postalCode": "987456",
      "streetName": "Straße",
      "street1": "techfund",
      "street2": "approve",
      "billingAddress": false,
      "shippingAddress": false,
      "countryCode": "D",
      "debitorNumber": "151127",
      "debitorType": "T",
      "debitorId": "258793ea-f915-6062-e053-404c070aa7be",
      "associated": true,
      "badDebitorInformation": false,
      "vodafoneUser": true,
      "modified": false,
      "default": false,
      "readOnly": false
    },
    {
      "addressId": "49a0fc13-c0a8-4da8-0340-c05cd1cc6171",
      "country": "Frankreich",
      "poBox": "545435435",
      "city": "galeay",
      "postalCode": "34567",
      "street1": "techfund",
      "street2": "k1",
      "billingAddress": false,
      "shippingAddress": false,
      "countryCode": "F",
      "debitorNumber": "000007",
      "debitorType": "T",
      "debitorId": "25889938-f362-4c68-e053-404c070a1682",
      "associated": true,
      "badDebitorInformation": false,
      "vodafoneUser": true,
      "modified": false,
      "default": false,
      "readOnly": false
    },
    {
      "addressId": "496a3623-c0a8-4da8-0340-c05c65750db0",
      "country": "Deutschland",
      "city": "Berlin",
      "houseNumber": "354543",
      "postalCode": "123456",
      "streetName": "street",
      "street1": "k1",
      "street2": "k2",
      "street3": "k3",
      "street4": "k4",
      "billingAddress": false,
      "shippingAddress": false,
      "countryCode": "D",
      "debitorNumber": "271115",
      "debitorType": "T",
      "debitorId": "2587cc0e-9fd2-605a-e053-404c070afca6",
      "associated": true,
      "badDebitorInformation": false,
      "vodafoneUser": true,
      "modified": false,
      "default": false,
      "readOnly": false
    },
    {
      "addressId": "a6ba0aad-c0a8-4dba-18b3-4370cdc15d1c",
      "country": "Deutschland",
      "city": "ddfsadada",
      "houseNumber": "1",
      "postalCode": "11223",
      "streetName": "qqqqq",
      "street1": "2",
      "street2": "3",
      "street3": "4",
      "street4": "5",
      "billingAddress": false,
      "shippingAddress": false,
      "countryCode": "D",
      "debitorNumber": "1234567",
      "debitorType": "D",
      "debitorId": "a6ba0aac-c0a8-4dba-18b3-43705d5ac7ca",
      "associated": true,
      "badDebitorInformation": false,
      "vodafoneUser": true,
      "modified": false,
      "default": false,
      "readOnly": false
    },
    {
      "addressId": "a6c08b36-c0a8-4dba-18b3-437041939ecd",
      "country": "Deutschland",
      "city": "cvdvdsvds",
      "houseNumber": "11",
      "postalCode": "11111",
      "streetName": "fdsdsfds",
      "street1": "qqq",
      "street2": "qqq",
      "street3": "qqq",
      "billingAddress": false,
      "shippingAddress": false,
      "countryCode": "D",
      "debitorNumber": "123456",
      "debitorType": "T",
      "debitorId": "a6c08b36-c0a8-4dba-18b3-43703bf8eead",
      "associated": true,
      "badDebitorInformation": false,
      "vodafoneUser": true,
      "modified": false,
      "default": false,
      "readOnly": false
    },
    {
      "addressId": "91b0f5de-c0a8-4dba-78b1-8d42faf94a4c",
      "country": "Deutschland",
      "city": "Berlin",
      "houseNumber": "25a",
      "postalCode": "212345",
      "streetName": "Straße",
      "street1": "techfund",
      "street2": "debitor",
      "billingAddress": false,
      "shippingAddress": false,
      "countryCode": "D",
      "debitorNumber": "111215",
      "debitorType": "T",
      "debitorId": "26a229ab-dc6d-584f-e053-424c070a8c25",
      "associated": true,
      "badDebitorInformation": false,
      "vodafoneUser": true,
      "modified": false,
      "default": false,
      "readOnly": false
    },
    {
      "country": "Deutschland",
      "billingAddress": false,
      "shippingAddress": false,
      "debitorNumber": "555799",
      "debitorType": "T",
      "debitorId": "289586c3-8064-1ffc-e053-424c070a5124",
      "associated": true,
      "badDebitorInformation": false,
      "vodafoneUser": true,
      "modified": false,
      "default": false,
      "readOnly": false
    },
    {
      "addressId": "410e9b6a-c0a8-4dba-5239-3809314b7904",
      "country": "Slowakische Republik",
      "poBox": "34345234",
      "city": "Standard Debitor Town",
      "postalCode": "6987987",
      "street1": "Standard Debitor A",
      "street2": "Standard Debitor B",
      "street3": "Standard Debitor C",
      "street4": "Standard Debitor 5",
      "billingAddress": false,
      "shippingAddress": false,
      "countryCode": "SK",
      "debitorNumber": "995577",
      "debitorType": "D",
      "debitorId": "294ebe2e-6b9f-2099-e053-424c070a9081",
      "associated": true,
      "badDebitorInformation": false,
      "vodafoneUser": true,
      "modified": false,
      "default": false,
      "readOnly": false
    },
    {
      "addressId": "ce82e635-c0a8-4dba-71d9-e2fe484716d4",
      "country": "Deutschland",
      "city": "berlin",
      "houseNumber": "4343",
      "postalCode": "4324324",
      "streetName": "streer",
      "street1": "k1",
      "street2": "k2",
      "street3": "k3",
      "billingAddress": false,
      "shippingAddress": false,
      "countryCode": "D",
      "debitorNumber": "150116",
      "debitorType": "T",
      "debitorId": "296255bb-bce9-3f32-e053-404c070a545f",
      "associated": true,
      "badDebitorInformation": false,
      "vodafoneUser": true,
      "modified": false,
      "default": false,
      "readOnly": false
    },
    {
      "addressId": "3fb906f6-c0a8-4dba-5239-3809c549084f",
      "country": "Deutschland",
      "poBox": "1478520369",
      "city": "Berlin",
      "postalCode": "45345345",
      "street1": "New Techfund Debitor k1",
      "street2": "New Techfund Debitor k2",
      "street3": "New Techfund Debitor k3",
      "street4": "New Techfund Debitor k4",
      "billingAddress": false,
      "shippingAddress": false,
      "countryCode": "D",
      "debitorNumber": "140116",
      "debitorType": "T",
      "debitorId": "294a6d34-eea8-430a-e053-424c070ab208",
      "associated": true,
      "badDebitorInformation": false,
      "vodafoneUser": true,
      "modified": false,
      "default": false,
      "readOnly": false
    },
    {
      "addressId": "402f09b0-c0a8-4dba-5239-3809020cd0bd",
      "country": "Deutschland",
      "city": "TF New One Town",
      "houseNumber": "5646546",
      "postalCode": "2135454",
      "streetName": "TF New One Street",
      "street1": "TF New One 1",
      "street2": "TF New One 2",
      "street3": "TF New One 3",
      "street4": "TF New One 4",
      "billingAddress": false,
      "shippingAddress": false,
      "countryCode": "D",
      "debitorNumber": "580912",
      "debitorType": "T",
      "debitorId": "294bc659-41f0-7ffd-e053-424c070aa756",
      "associated": true,
      "badDebitorInformation": false,
      "vodafoneUser": true,
      "modified": false,
      "default": false,
      "readOnly": false
    },
    {
      "addressId": "4497faf8-c0a8-4dba-5239-3809b4939201",
      "country": "Finnland",
      "city": "sstate",
      "houseNumber": "55",
      "postalCode": "11122",
      "streetName": "sstreett",
      "street1": "ss1",
      "street2": "ss2",
      "street3": "ss3",
      "street4": "ss4",
      "billingAddress": false,
      "shippingAddress": false,
      "countryCode": "SF",
      "debitorNumber": "506030",
      "debitorType": "D",
      "debitorId": "295d2544-5efe-08d5-e053-424c070a5266",
      "associated": true,
      "badDebitorInformation": false,
      "vodafoneUser": true,
      "modified": false,
      "default": false,
      "readOnly": false
    },
    {
      "addressId": "44fe44ad-c0a8-4dba-5239-38090373ab25",
      "country": "Deutschland",
      "city": "bob stadt",
      "houseNumber": "23",
      "postalCode": "12345",
      "streetName": "bob new free org dbtr",
      "street1": "bob new free org",
      "billingAddress": false,
      "shippingAddress": false,
      "countryCode": "D",
      "debitorNumber": "112244",
      "debitorType": "D",
      "debitorId": "295e9464-0523-141b-e053-404c070a691b",
      "associated": true,
      "badDebitorInformation": false,
      "vodafoneUser": true,
      "modified": false,
      "default": false,
      "readOnly": false
    },
    {
      "addressId": "3bc3ac1a-c0a8-4dba-5239-380901252c00",
      "country": "Irland",
      "city": "Unit 8",
      "houseNumber": "1",
      "postalCode": "78989789",
      "streetName": "level",
      "street1": "grainne",
      "street2": "hackett",
      "street3": "synchronoss technologies",
      "billingAddress": false,
      "shippingAddress": false,
      "countryCode": "IRL",
      "debitorNumber": "130116",
      "debitorType": "T",
      "debitorId": "295f88f5-4ba9-53ca-e053-424c070a95e9",
      "associated": true,
      "badDebitorInformation": false,
      "vodafoneUser": true,
      "modified": false,
      "default": false,
      "readOnly": false
    },
    {
      "country": "Deutschland",
      "billingAddress": false,
      "shippingAddress": false,
      "debitorNumber": "081024",
      "debitorType": "T",
      "debitorId": "295f88f5-4bae-53ca-e053-424c070a95e9",
      "associated": true,
      "badDebitorInformation": false,
      "vodafoneUser": true,
      "modified": false,
      "default": false,
      "readOnly": false
    },
    {
      "addressId": "3bcc6772-c0a8-4dba-5239-380942f620f9",
      "country": "Deutschland",
      "city": "city",
      "houseNumber": "54435345",
      "postalCode": "45456",
      "streetName": "street",
      "street1": "new techfund debitor",
      "billingAddress": false,
      "shippingAddress": false,
      "countryCode": "D",
      "debitorNumber": "160113",
      "debitorType": "T",
      "debitorId": "295fa553-175c-0c9b-e053-404c070a3662",
      "associated": true,
      "badDebitorInformation": false,
      "vodafoneUser": true,
      "modified": false,
      "default": false,
      "readOnly": false
    },
    {
      "country": "Deutschland",
      "billingAddress": false,
      "shippingAddress": false,
      "debitorNumber": "160114",
      "debitorType": "T",
      "debitorId": "294adee3-c040-1870-e053-424c070a300f",
      "associated": true,
      "badDebitorInformation": false,
      "vodafoneUser": true,
      "modified": false,
      "default": false,
      "readOnly": false
    },
    {
      "addressId": "401d79eb-c0a8-4dba-5239-380994f12729",
      "country": "Deutschland",
      "city": "TF New Town",
      "houseNumber": "54654654",
      "postalCode": "54654654",
      "streetName": "TF New Street",
      "street1": "TF New 1",
      "street2": "TF New 2",
      "street3": "TF New 3",
      "street4": "TF New 4",
      "billingAddress": false,
      "shippingAddress": false,
      "countryCode": "D",
      "debitorNumber": "850602",
      "debitorType": "T",
      "debitorId": "294bb642-c5cf-4ed5-e053-424c070a70a4",
      "associated": true,
      "badDebitorInformation": false,
      "vodafoneUser": true,
      "modified": false,
      "default": false,
      "readOnly": false
    },
    {
      "country": "Deutschland",
      "billingAddress": false,
      "shippingAddress": false,
      "debitorNumber": "160115",
      "debitorType": "T",
      "debitorId": "29627854-af08-43c3-e053-404c070a02e0",
      "associated": true,
      "badDebitorInformation": false,
      "vodafoneUser": true,
      "modified": false,
      "default": false,
      "readOnly": false
    },
    {
      "addressId": "3fa5df11-c0a8-4dba-5239-3809cca6f04c",
      "country": "Portugal",
      "city": "New TF Debitor Town",
      "houseNumber": "5465465",
      "postalCode": "852825",
      "streetName": "New TF Debitor Street",
      "street1": "New TF Debitor",
      "street2": "New TF Debitor 2",
      "street3": "New TF Debitor 3",
      "street4": "New TF Debitor 4",
      "billingAddress": false,
      "shippingAddress": false,
      "countryCode": "P",
      "debitorNumber": "875595",
      "debitorType": "T",
      "debitorId": "294a97be-31c8-3f28-e053-424c070a8a46",
      "associated": true,
      "badDebitorInformation": false,
      "vodafoneUser": true,
      "modified": false,
      "default": false,
      "readOnly": false
    },
    {
      "addressId": "41085274-c0a8-4dba-5239-380949d1383c",
      "country": "Deutschland",
      "poBox": "579687651",
      "city": "Standard Debitor Town",
      "postalCode": "3215465",
      "street1": "Standard Debitor 1",
      "street2": "Standard Debitor 2",
      "street3": "Standard Debitor 3",
      "street4": "Standard Debitor 4",
      "billingAddress": false,
      "shippingAddress": false,
      "countryCode": "D",
      "debitorNumber": "881100",
      "debitorType": "D",
      "debitorId": "294f299f-2842-0133-e053-424c070a55c9",
      "associated": true,
      "badDebitorInformation": false,
      "vodafoneUser": true,
      "modified": false,
      "default": false,
      "readOnly": false
    },
    {
      "country": "Deutschland",
      "billingAddress": false,
      "shippingAddress": false,
      "debitorNumber": "881112",
      "debitorType": "T",
      "debitorId": "2a2a3ef1-6795-52a3-e053-424c070a9924",
      "associated": true,
      "badDebitorInformation": false,
      "vodafoneUser": true,
      "modified": false,
      "default": false,
      "readOnly": false
    },
    {
      "country": "Deutschland",
      "billingAddress": false,
      "shippingAddress": false,
      "debitorNumber": "362514",
      "debitorType": "T",
      "debitorId": "2a50f8de-3df6-2603-e053-404c070a6175",
      "associated": true,
      "badDebitorInformation": false,
      "vodafoneUser": true,
      "modified": false,
      "default": false,
      "readOnly": false
    },
    {
      "country": "Deutschland",
      "billingAddress": false,
      "shippingAddress": false,
      "debitorNumber": "0102161",
      "debitorType": "D",
      "debitorId": "2ab655fa-e422-6e93-e053-404c070a9835",
      "associated": true,
      "badDebitorInformation": false,
      "vodafoneUser": true,
      "modified": false,
      "default": false,
      "readOnly": false
    },
    {
      "country": "Deutschland",
      "billingAddress": false,
      "shippingAddress": false,
      "debitorNumber": "889977",
      "debitorType": "T",
      "debitorId": "2af0d277-3f22-0f45-e053-404c070a20bb",
      "associated": true,
      "badDebitorInformation": false,
      "vodafoneUser": true,
      "modified": false,
      "default": false,
      "readOnly": false
    },
    {
      "country": "Deutschland",
      "billingAddress": false,
      "shippingAddress": false,
      "debitorNumber": "255885",
      "debitorType": "T",
      "debitorId": "2af0e985-549d-21bb-e053-404c070a3ef5",
      "associated": true,
      "badDebitorInformation": false,
      "vodafoneUser": true,
      "modified": false,
      "default": false,
      "readOnly": false
    },
    {
      "country": "Deutschland",
      "billingAddress": false,
      "shippingAddress": false,
      "debitorNumber": "220416",
      "debitorType": "D",
      "debitorId": "3113dd53-0034-096d-e053-404c070a0330",
      "associated": true,
      "badDebitorInformation": false,
      "vodafoneUser": true,
      "modified": false,
      "default": false,
      "readOnly": false
    },
    {
      "addressId": "2b05112a-c0a8-4da8-20ad-8b5d8cb44133",
      "country": "Deutschland",
      "city": "Berlin",
      "houseNumber": "456465",
      "postalCode": "5443543",
      "streetName": "strret",
      "street1": "techfund debitor",
      "street2": "same as cpd no.",
      "billingAddress": false,
      "shippingAddress": false,
      "countryCode": "D",
      "debitorNumber": "070616",
      "debitorType": "T",
      "debitorId": "2b051129-c0a8-4da8-20ad-8b5d43f7b684",
      "associated": true,
      "badDebitorInformation": false,
      "vodafoneUser": true,
      "modified": false,
      "default": false,
      "readOnly": false
    },
    {
      "country": "Deutschland",
      "billingAddress": false,
      "shippingAddress": false,
      "debitorNumber": "160422",
      "debitorType": "D",
      "debitorId": "3114eaba-617d-11e7-e053-404c070ae132",
      "associated": true,
      "badDebitorInformation": false,
      "vodafoneUser": true,
      "modified": false,
      "default": false,
      "readOnly": false
    },
    {
      "addressId": "916254c0-c0a8-4da8-7973-28fe5a6a165b",
      "country": "Deutschland",
      "city": "dsfvvvfffdfv",
      "houseNumber": "scvdvvfdf",
      "postalCode": "2342342332",
      "streetName": "23434324324",
      "street1": "sdffffffff",
      "street2": "dsffffffffffff",
      "street3": "sfffffffffffffffffffffff",
      "street4": "dsfffffffffffffffffff",
      "billingAddress": false,
      "shippingAddress": false,
      "countryCode": "D",
      "debitorNumber": "312141",
      "debitorType": "D",
      "debitorId": "36408ac5-be60-67a8-e053-404c070ac82f",
      "associated": true,
      "badDebitorInformation": false,
      "vodafoneUser": true,
      "modified": false,
      "default": false,
      "readOnly": false
    },
    {
      "country": "Deutschland",
      "billingAddress": false,
      "shippingAddress": false,
      "debitorNumber": "160607",
      "debitorType": "D",
      "debitorId": "34b1f820-ccfa-1a42-e053-404c070ae628",
      "associated": true,
      "badDebitorInformation": false,
      "vodafoneUser": true,
      "modified": false,
      "default": false,
      "readOnly": false
    },
    {
      "addressId": "913e37f8-c0a8-4da8-7973-28fea7b8f7ab",
      "country": "Deutschland",
      "city": "fsdvvssvdvsdvs",
      "houseNumber": "dvvdfvddv",
      "postalCode": "2342334232",
      "streetName": "43243453453",
      "street1": "evhcjkhvjkef",
      "street2": "dvdvfdfvdvf",
      "street3": "dvfdvvd",
      "street4": "vdfvdvfvfdv",
      "billingAddress": false,
      "shippingAddress": false,
      "countryCode": "D",
      "debitorNumber": "987868",
      "debitorType": "T",
      "debitorId": "3640b7fa-0da1-3730-e053-404c070af7cf",
      "associated": true,
      "badDebitorInformation": false,
      "vodafoneUser": true,
      "modified": false,
      "default": false,
      "readOnly": false
    },
    {
      "addressId": "664b5708-c0a8-4da9-1469-994abba135e7",
      "country": "Irland",
      "city": "Galway",
      "houseNumber": "300b-401a",
      "postalCode": "5545646",
      "streetName": "Straße",
      "street1": "kundenname",
      "street2": "Test Kundenname 2",
      "billingAddress": false,
      "shippingAddress": false,
      "countryCode": "IRL",
      "debitorNumber": "260916",
      "debitorType": "T",
      "debitorId": "3d689644-e223-21e4-e053-404c070af2d2",
      "associated": true,
      "badDebitorInformation": false,
      "vodafoneUser": true,
      "modified": false,
      "default": false,
      "readOnly": false
    },
    {
      "addressId": "65633765-c0a8-4da9-1469-994a5005b100",
      "country": "Deutschland",
      "city": "fdv",
      "houseNumber": "21",
      "postalCode": "12111",
      "streetName": "fgv",
      "street1": "df",
      "street2": "gbfd",
      "street3": "dfb",
      "billingAddress": false,
      "shippingAddress": false,
      "countryCode": "D",
      "debitorNumber": "030498",
      "debitorType": "T",
      "debitorId": "3d64ba4c-b892-2feb-e053-404c070af9d2",
      "associated": true,
      "badDebitorInformation": false,
      "vodafoneUser": true,
      "modified": false,
      "default": false,
      "readOnly": false
    },
    {
      "addressId": "65b288d2-c0a8-4da9-1469-994ac2ab85c3",
      "country": "Deutschland",
      "city": "hgn",
      "houseNumber": "12",
      "postalCode": "56434",
      "streetName": "ghn",
      "street1": "df",
      "street2": "bd",
      "street3": "dfg",
      "billingAddress": false,
      "shippingAddress": false,
      "countryCode": "D",
      "debitorNumber": "789023",
      "debitorType": "T",
      "debitorId": "3d664891-15f0-1cdc-e053-424c070addbf",
      "associated": true,
      "badDebitorInformation": false,
      "vodafoneUser": true,
      "modified": false,
      "default": false,
      "readOnly": false
    },
    {
      "addressId": "65b288d2-c0a8-4da9-1469-994ac2ab85c3",
      "country": "Deutschland",
      "city": "hgn",
      "houseNumber": "12",
      "postalCode": "56434",
      "streetName": "ghn",
      "street1": "df",
      "street2": "bd",
      "street3": "dfg",
      "billingAddress": false,
      "shippingAddress": false,
      "countryCode": "D",
      "debitorNumber": "789023",
      "debitorType": "T",
      "debitorId": "3d664891-15f1-1cdc-e053-424c070addbf",
      "associated": true,
      "badDebitorInformation": false,
      "vodafoneUser": true,
      "modified": false,
      "default": false,
      "readOnly": false
    },
    {
      "addressId": "65b80a7c-c0a8-4da9-1469-994ac73d7124",
      "country": "Deutschland",
      "city": "df",
      "houseNumber": "12",
      "postalCode": "23123",
      "streetName": "dsf",
      "street1": "cvdv",
      "street2": "dfvb",
      "street3": "dfv",
      "billingAddress": false,
      "shippingAddress": false,
      "countryCode": "D",
      "debitorNumber": "097898",
      "debitorType": "T",
      "debitorId": "3d664891-15f2-1cdc-e053-424c070addbf",
      "associated": true,
      "badDebitorInformation": false,
      "vodafoneUser": true,
      "modified": false,
      "default": false,
      "readOnly": false
    },
    {
      "addressId": "d294fe4e-c0a8-4dba-4237-f6048fea0593",
      "country": "Deutschland",
      "city": "Lorch",
      "houseNumber": "128",
      "postalCode": "73547",
      "streetName": "Bülling Straße",
      "billingAddress": false,
      "shippingAddress": false,
      "countryCode": "D",
      "debitorNumber": "234567",
      "debitorType": "D",
      "debitorId": "42f76b0f-581f-3791-e053-424c070ac844",
      "associated": true,
      "badDebitorInformation": false,
      "vodafoneUser": true,
      "modified": false,
      "default": false,
      "readOnly": false
    },
    {
      "addressId": "858b00e0-c0a8-4da8-4c5a-9b3538bbe553",
      "country": "Deutschland",
      "city": "rerwe",
      "houseNumber": "34",
      "postalCode": "22222",
      "streetName": "trtre",
      "street1": "testt",
      "street2": "ttt",
      "billingAddress": false,
      "shippingAddress": false,
      "debitorNumber": "423333",
      "debitorType": "T",
      "debitorId": "4d828dbf-8304-3b5f-e053-404c070a6ba7",
      "associated": true,
      "badDebitorInformation": false,
      "vodafoneUser": true,
      "modified": false,
      "default": false,
      "readOnly": false
    },
    {
      "addressId": "86486ef7-c0a8-4da8-4c5a-9b35a139c504",
      "country": "Deutschland",
      "city": "fdsfsd",
      "houseNumber": "45",
      "postalCode": "43333",
      "streetName": "ttt",
      "street1": "testt",
      "street2": "tt",
      "billingAddress": false,
      "shippingAddress": false,
      "debitorNumber": "432432",
      "debitorType": "T",
      "debitorId": "4d85acfa-c2c3-5a2c-e053-404c070aac95",
      "associated": true,
      "badDebitorInformation": false,
      "vodafoneUser": true,
      "modified": false,
      "default": false,
      "readOnly": false
    },
    {
      "addressId": "66d36603-c0a8-4da8-4d01-c7cf88673c09",
      "country": "Deutschland",
      "city": "fdsf",
      "houseNumber": "44",
      "postalCode": "44444",
      "streetName": "ttt",
      "street1": "test",
      "billingAddress": false,
      "shippingAddress": false,
      "countryCode": "D",
      "debitorNumber": "478910",
      "debitorType": "T",
      "debitorId": "66d36603-c0a8-4da8-4d01-c7cfd6d136a1",
      "associated": true,
      "badDebitorInformation": false,
      "vodafoneUser": true,
      "modified": false,
      "default": false,
      "readOnly": false
    },
    {
      "addressId": "80a39264-c0a8-4da8-7e82-8f0cc450395f",
      "country": "Deutschland",
      "city": "fdsf",
      "houseNumber": "34",
      "postalCode": "32222",
      "streetName": "ttttt",
      "street1": "testt",
      "street2": "tt",
      "billingAddress": false,
      "shippingAddress": false,
      "countryCode": "D",
      "debitorNumber": "145678",
      "debitorType": "T",
      "debitorId": "80a39263-c0a8-4da8-7e82-8f0c441bde6f",
      "associated": true,
      "badDebitorInformation": false,
      "vodafoneUser": true,
      "modified": false,
      "default": false,
      "readOnly": false
    },
    {
      "addressId": "80a910a4-c0a8-4da8-7e82-8f0cb418dcad",
      "country": "Deutschland",
      "city": "fdsfds",
      "houseNumber": "34",
      "postalCode": "33333",
      "streetName": "fdsfd",
      "street1": "ttt",
      "billingAddress": false,
      "shippingAddress": false,
      "countryCode": "D",
      "debitorNumber": "123490",
      "debitorType": "T",
      "debitorId": "80a910a4-c0a8-4da8-7e82-8f0c7c652507",
      "associated": true,
      "badDebitorInformation": false,
      "vodafoneUser": true,
      "modified": false,
      "default": false,
      "readOnly": false
    },
    {
      "addressId": "805de532-c0a8-4da8-4c5a-9b350947fc44",
      "country": "Deutschland",
      "city": "nngh",
      "houseNumber": "56",
      "postalCode": "55555",
      "streetName": "hghgf",
      "street1": "test",
      "street2": "tt",
      "billingAddress": false,
      "shippingAddress": false,
      "debitorNumber": "765766",
      "debitorType": "T",
      "debitorId": "4d6ebad0-e2b7-0a58-e053-424c070a1f46",
      "associated": true,
      "badDebitorInformation": false,
      "vodafoneUser": true,
      "modified": false,
      "default": false,
      "readOnly": false
    },
    {
      "addressId": "80ac9ef9-c0a8-4da8-7e82-8f0c7c8fdbf2",
      "country": "Deutschland",
      "city": "dsasd",
      "houseNumber": "45",
      "postalCode": "12222",
      "streetName": "gfdg",
      "street1": "tet",
      "street2": "tt",
      "street3": "gfdg",
      "street4": "gfdgg",
      "billingAddress": false,
      "shippingAddress": false,
      "countryCode": "D",
      "debitorNumber": "345678",
      "debitorType": "T",
      "debitorId": "80ac9ef9-c0a8-4da8-7e82-8f0c30b371c3",
      "associated": true,
      "badDebitorInformation": false,
      "vodafoneUser": true,
      "modified": false,
      "default": false,
      "readOnly": false
    },
    {
      "addressId": "875f142a-c0a8-4da8-63bb-54945f04a077",
      "country": "Deutschland",
      "city": "kstate",
      "houseNumber": "33",
      "postalCode": "11223",
      "streetName": "kstreet",
      "street1": "k1",
      "street2": "k2",
      "street3": "k3",
      "street4": "k4",
      "billingAddress": false,
      "shippingAddress": false,
      "countryCode": "D",
      "debitorNumber": "754321",
      "debitorType": "D",
      "debitorId": "6cc9c5c5-d33d-7587-e053-424c070a14e7",
      "associated": true,
      "badDebitorInformation": false,
      "vodafoneUser": true,
      "modified": false,
      "default": false,
      "readOnly": false
    },
    {
      "addressId": "e9e0d4f9-c0a8-4da8-6637-4289fe7f5912",
      "country": "Deutschland",
      "city": "stdat",
      "houseNumber": "35",
      "postalCode": "12345",
      "streetName": "street",
      "street1": "test",
      "street2": "35",
      "billingAddress": false,
      "shippingAddress": false,
      "countryCode": "D",
      "debitorNumber": "127890",
      "debitorType": "D",
      "debitorId": "e9e0d4f8-c0a8-4da8-6637-4289fcb54c42",
      "associated": true,
      "badDebitorInformation": false,
      "vodafoneUser": true,
      "modified": false,
      "default": false,
      "readOnly": false
    },
    {
      "addressId": "870cda22-c0a8-4da8-0704-1ef5cf605736",
      "country": "Deutschland",
      "city": "fdg",
      "houseNumber": "12",
      "postalCode": "11111",
      "streetName": "fdsf",
      "street1": "testt",
      "street2": "tt",
      "billingAddress": false,
      "shippingAddress": false,
      "countryCode": "D",
      "debitorNumber": "456789",
      "debitorType": "T",
      "debitorId": "870cda22-c0a8-4da8-0704-1ef58b3251c3",
      "associated": true,
      "badDebitorInformation": false,
      "vodafoneUser": true,
      "modified": false,
      "default": false,
      "readOnly": false
    },
    {
      "addressId": "87581610-c0a8-4da8-37cf-1db8a8073d26",
      "country": "Deutschland",
      "city": "kstate",
      "houseNumber": "22",
      "postalCode": "11223",
      "streetName": "kstreet",
      "street1": "k1",
      "street2": "k2",
      "street3": "k3",
      "street4": "k4",
      "billingAddress": false,
      "shippingAddress": false,
      "countryCode": "D",
      "debitorNumber": "654321",
      "debitorType": "D",
      "debitorId": "6cc9b752-f7cc-74a3-e053-424c070ad1fe",
      "associated": true,
      "badDebitorInformation": false,
      "vodafoneUser": true,
      "modified": false,
      "default": false,
      "readOnly": false
    },
    {
      "addressId": "4356f42a-c0a8-4da8-02cf-6beecb2dfdd7",
      "country": "Dänemark",
      "city": "stateeeeee",
      "houseNumber": "45",
      "postalCode": "33344",
      "streetName": "pvnstreet",
      "street1": "pvn1",
      "street2": "pvn2",
      "street3": "pvn3",
      "street4": "pvn4",
      "billingAddress": false,
      "shippingAddress": false,
      "countryCode": "DK",
      "debitorNumber": "888999",
      "debitorType": "D",
      "debitorId": "67d83e44-466c-40ba-e053-424c070a4549",
      "associated": true,
      "badDebitorInformation": false,
      "vodafoneUser": true,
      "modified": false,
      "default": false,
      "readOnly": false
    },
    {
      "addressId": "4497faf8-c0a8-4dba-5239-3809b4939201",
      "country": "Finnland",
      "city": "sstate",
      "houseNumber": "55",
      "postalCode": "11122",
      "streetName": "sstreett",
      "street1": "ss1",
      "street2": "ss2",
      "street3": "ss3",
      "street4": "ss4",
      "billingAddress": false,
      "shippingAddress": false,
      "countryCode": "SF",
      "debitorNumber": "982345",
      "debitorType": "D",
      "debitorId": "67d95021-e5df-5d21-e053-424c070a33aa",
      "associated": true,
      "badDebitorInformation": false,
      "vodafoneUser": true,
      "modified": false,
      "default": false,
      "readOnly": false
    },
    {
      "addressId": "6635049d-c0a8-4da8-23e3-efbd716f9f43",
      "country": "Bulgarien",
      "city": "ssss",
      "houseNumber": "11",
      "postalCode": "11134",
      "streetName": "ss",
      "street1": "ch1",
      "street2": "ch2",
      "street3": "ch3",
      "street4": "ch4",
      "billingAddress": false,
      "shippingAddress": false,
      "countryCode": "BG",
      "debitorNumber": "998989",
      "debitorType": "T",
      "debitorId": "68605d36-712a-4817-e053-424c070a57b3",
      "associated": true,
      "badDebitorInformation": false,
      "vodafoneUser": true,
      "modified": false,
      "default": false,
      "readOnly": false
    },
    {
      "addressId": "71b6221b-c0a8-4da8-1450-37438d06affa",
      "country": "Bulgarien",
      "city": "DDDDSTATE",
      "houseNumber": "88",
      "postalCode": "66666",
      "streetName": "SST",
      "street1": "KKKK1",
      "street2": "KKKK3",
      "street3": "KKKKK5",
      "street4": "KKK7",
      "billingAddress": false,
      "shippingAddress": false,
      "countryCode": "BG",
      "debitorNumber": "998888",
      "debitorType": "T",
      "debitorId": "688d3646-866c-049d-e053-424c070acd3a",
      "associated": true,
      "badDebitorInformation": false,
      "vodafoneUser": true,
      "modified": false,
      "default": false,
      "readOnly": false
    },
    {
      "addressId": "0c6252f8-c0a8-4da8-20bf-aea5ca11cb02",
      "country": "Deutschland",
      "city": "dsfsdfsdf",
      "houseNumber": "23423",
      "postalCode": "43243",
      "streetName": "dfsdfd",
      "street1": "dfdsfsdf",
      "street2": "sdfsdf",
      "street3": "dsfdsf",
      "street4": "dsfsdf",
      "billingAddress": false,
      "shippingAddress": false,
      "countryCode": "D",
      "debitorNumber": "423454",
      "debitorType": "T",
      "debitorId": "864182b3-7dfe-208d-e053-984c070a0e12",
      "associated": true,
      "badDebitorInformation": false,
      "vodafoneUser": true,
      "modified": false,
      "default": false,
      "readOnly": false
    }
  ],
  "techfundEnabled": false
};