module.exports = {
    "tariffs": [
        {
            "readOnlyVodafoneUser": false,
            "value": "1",
            "text": "VF_MobConn_L_SimOnly_CDG",
            "mandatory": false,
            "disabled": false,
            "length": 0,
            "excluded": 0,
            "displayOrder": 0,
            "subsCount": 28,
            "tariffOption": "PROCLSE60"
        },
        {
            "readOnlyVodafoneUser": false,
            "value": "2",
            "text": "VF Mobile Connect L SIMonly",
            "mandatory": false,
            "disabled": false,
            "length": 0,
            "excluded": 0,
            "displayOrder": 0,
            "subsCount": 26,
            "tariffOption": "PRPXL1Y60"
        },
        {
            "readOnlyVodafoneUser": false,
            "value": "3",
            "text": "Prof Plus XXL 60/1 Sub",
            "mandatory": false,
            "disabled": false,
            "length": 0,
            "excluded": 0,
            "displayOrder": 0,
            "subsCount": 28,
            "tariffOption": "RBD_YL"
        },
        {
            "readOnlyVodafoneUser": false,
            "value": "4",
            "text": "VF SuperFlat Internet 60/1",
            "mandatory": false,
            "disabled": false,
            "length": 0,
            "excluded": 0,
            "displayOrder": 0,
            "subsCount": 26,
            "tariffOption": "PR_MN01"
        },
        {
            "readOnlyVodafoneUser": false,
            "value": "5",
            "text": "BusinessBasic,  10 s (SE-LA)",
            "mandatory": false,
            "disabled": false,
            "length": 0,
            "excluded": 0,
            "displayOrder": 0,
            "subsCount": 26,
            "tariffOption": "RBD_YS"
        },
        {
            "readOnlyVodafoneUser": false,
            "value": "6",
            "text": "Vodafone Zuhause Talk24",
            "mandatory": false,
            "disabled": false,
            "length": 0,
            "excluded": 0,
            "displayOrder": 0,
            "subsCount": 28,
            "tariffOption": "BUCLSE10"
        },
        {
            "readOnlyVodafoneUser": false,
            "value": "8",
            "text": "Mobile ConnectWorld Large Sub",
            "mandatory": false,
            "disabled": false,
            "length": 0,
            "excluded": 0,
            "displayOrder": 0,
            "subsCount": 28,
            "tariffOption": "VF_ZH24F1"
        },
        {
            "readOnlyVodafoneUser": false,
            "value": "9",
            "text": "VF SuperFlat SIM Only",
            "mandatory": false,
            "disabled": false,
            "length": 0,
            "excluded": 0,
            "displayOrder": 0,
            "subsCount": 27,
            "tariffOption": "RBMY60"
        },
        {
            "readOnlyVodafoneUser": false,
            "value": "10",
            "text": "Professional XL 60/1 SIM only",
            "mandatory": false,
            "disabled": false,
            "length": 0,
            "excluded": 0,
            "displayOrder": 0,
            "subsCount": 24,
            "tariffOption": "RBD_NPREM"
        },
        {
            "readOnlyVodafoneUser": false,
            "value": "11",
            "text": "BusinessClass.,  10 s (SE-LA)",
            "mandatory": false,
            "disabled": false,
            "length": 0,
            "excluded": 0,
            "displayOrder": 0,
            "subsCount": 25,
            "tariffOption": "PROVILN60"
        },
        {
            "readOnlyVodafoneUser": false,
            "value": "12",
            "text": "Vodafone Red Business",
            "mandatory": false,
            "disabled": false,
            "length": 0,
            "excluded": 0,
            "displayOrder": 0,
            "subsCount": 54,
            "tariffOption": "MBB3G50N"
        },
        {
            "readOnlyVodafoneUser": false,
            "value": "13",
            "text": "VF Mobile Connect L Sub",
            "mandatory": false,
            "disabled": false,
            "length": 0,
            "excluded": 0,
            "displayOrder": 0,
            "subsCount": 28,
            "tariffOption": "PRPMN60"
        },
        {
            "readOnlyVodafoneUser": false,
            "value": "14",
            "text": "VF Mobile Connect Flat Sub",
            "mandatory": false,
            "disabled": false,
            "length": 0,
            "excluded": 0,
            "displayOrder": 0,
            "subsCount": 27,
            "tariffOption": "BAYERSN01"
        },
        {
            "readOnlyVodafoneUser": false,
            "value": "15",
            "text": "Professional Plus XL 60/1",
            "mandatory": false,
            "disabled": false,
            "length": 0,
            "excluded": 0,
            "displayOrder": 0,
            "subsCount": 26,
            "tariffOption": "PR_XLIN01"
        },
        {
            "readOnlyVodafoneUser": false,
            "value": "16",
            "text": "Mobile ConnectWorld Large SO",
            "mandatory": false,
            "disabled": false,
            "length": 0,
            "excluded": 0,
            "displayOrder": 0,
            "subsCount": 27,
            "tariffOption": "PR_ELY60"
        },
        {
            "readOnlyVodafoneUser": false,
            "value": "17",
            "text": "Professional XL 60/1 Sub",
            "mandatory": false,
            "disabled": false,
            "length": 0,
            "excluded": 0,
            "displayOrder": 0,
            "subsCount": 28,
            "tariffOption": "DAT_NMMLE"
        }
    ]
};