module.exports = {
  "CONFIRM-DESCRIPTION": "Please note that the information about the following day will be updated. We kindly ask you to submit further orders for this customer number (s) only after completion of the update.",
  "ORDER_CONFIRM-DESCRIPTION": "Please note that the information about the following day will be updated. We kindly ask you to submit further orders for this number only after completion of the update.",
  "ORDER_CONSISTS": "Your order consists of the following parts: ",
  "PAGE_TITLE": "Contract extension (VVL)",
  "PROLONG_DEBITOR-CONTINUE_TO_SELECT_SHIPPING": "Continue to shipment",
  "PROLONG_SHIPMENT-CONTINUE_TO_ORDER_REVIEW": "Continue to order review",
  "PROLONGATION-TECHNICAL_ERROR": "<b>Temporary technical fault </b> <p> </p> Due to a system error, the desired website is currently not available. Please try again later. <P> </p> Best regards, Your Vodafone Team",
  "REVIEW-COL_ONE_TIME": "unique",
  "REVIEW-COL_MONTHLY": "Per month",
  "REVIEW-COL_QUANTITY": "amount",
  "REVIEW-COST_TITLE": "Cost overview",
  "REVIEW-COST_TOTAL": "total amount",
  "REVIEW-COST_TOTAL_INC_VAT": "Total amount (incl. VAT)",
  "REVIEW-COST_VAT": "Taxes (19%)",
  "RECEVIED_SUCESS_MSG": "Your order has been received successfully and is in progress.",
  "REVIEW-DEP": "Device Enrollment Program (DEP)",
  "REVIEW-DEP-KUNDEN-ID": "DEP-Customer-ID: ",
  "REVIEW-DEP-LIEFERANT": "DEP-Supplier: ",
  "REVIEW-HARDWARE_PRICE_WITH_MULTI_TARIFF": "The hardware prices vary depending on the tariff",
  "REVIEW-HARDWARE_TITLE": "Hardware",
  "REVIEW-SOC_TITLE": "Tarif options",
  "REVIEW-SUB_TITLE_MSG": "Please check your changes in the last step. If everything is correct, please click on the button \"send order\".",
  "REVIEW-TARIFF_TITLE": "Tariff",
  "REVIEW-TITLE": "Order overview",
  "VVL-DATATABLE-SELECTION_COUNT-ALL": "All results selected",
  "VVL-DATATABLE-SELECTION_COUNT-NONE": "No participant selected",
  "VVL-DATATABLE-SELECTION_COUNT-ONE": "One participant selected",
  "VVL-DATATABLE-SELECTION_COUNT-OTHER": "{{selectCount}} Participants selected"
};
