module.exports = {
  'HARDWARE_CATEGORY': 'Category',
  'HARDWARE_MANUFACTURER': 'Manufacturer',
  'HARDWARE_SELECTION-ARTICLE_NUMBER': 'item number',
  'HARDWARE_SELECTION-AVAILABLE_HARDWARE': 'In stock',
  'HARDWARE_SELECTION-CONTINUE_WITH_CREDIT_VOUCHER': 'I want a hardware credit',
  'HARDWARE_SELECTION-DEP_CUSTOMER_ID':'DEP customer ID',
  'HARDWARE_SELECTION-ELIGIBLE_SUBS': '{{count}} Participants can be selected for this hardware',
  'HARDWARE_SELECTION-ELIGIBLE_SUBSCRIBER': '{{eligibleSubs}} out of {{selectedSubs}} selected participants can take advantage of this',
  'HARDWARE_SELECTION-HARDWARE_SELECTED': 'Selected hardware',
  'HARDWARE_SELECTION-NEXT_BUTTON': 'Continue to the tariff options',
  'HARDWARE_SELECTION-NOT_AVAILABLE_HARDWARE': 'No longer available',
  'HARDWARE_SELECTION-NO_ELIGIBLE_SUBS': 'No participants can be selected for this hardware',
  'HARDWARE_SELECTION-NO_RESPONSE_HARDWARE': 'Not in stock',
  'HARDWARE_SELECTION-NO_SUBS_ELIGIBLE_WARNING': 'no subscribers are eligible',
  'HARDWARE_SELECTION-SELECT_NEW_HARDWARE_MSG2':'Please pay attention on the SIM format of the selected hardware.',
  'HARDWARE_SELECTION-SELECT_NEW_HARDWARE_MSG3':'If necessary, please proceed a SIM card swap into the required SIM format.',
  'HARDWARE_SELECTION-PRODUCT_DETAILS': 'Product Details ...',
  'HARDWARE_SELECTION-PRODUCT_LOOKUP_DETAILS': 'Details',
  'HARDWARE_SELECTION-LOOKUP_DETAILS_TARIF': 'Tariff',
  'HARDWARE_SELECTION-LOOKUP_DETAILS_COUNT': 'Count',
  'HARDWARE_SELECTION-LOOKUP_DETAILS_PRICE': 'Price',
  'HARDWARE_SELECTION-LOOKUP_DETAILS_AVG_PRICE': 'Average Price',
  'HARDWARE_SELECTION-RESULTS_FOUND': '{{count}} Results found',
  'HARDWARE_SELECTION-SELECT_AT_LEAST_ONE_OPTION': 'Please select an option',
  'HARDWARE_SELECTION-SELECT_HARDWARE_ERR_MSG': 'The selected hardware can not be booked by any of the selected participants. Please choose a different hardware.',
  'HARDWARE_SELECTION-SELECT_HARDWARE': 'Choose',
  'HARDWARE_SELECTION-SELECT_WARNING': 'Please select a hardware.',
  'HARDWARE_SELECTION-SELECT_NEW_HARDWARE_MSG': 'Here you can see the hardware available for your master contract. The number of hardwares to order is the number the selected participant. Please select the desired hardware.',
  'HARDWARE_SELECTION-SUB_TITLE_MSG': 'Please select an option',
  'HARDWARE_SELECTION-SELECT_NEW_HARDWARE_INFO': 'Please note that the hardware prices dependent on the tariffs. Since you have selected participants with different rates, the average prices are displayed. Click on \'Details\' to view the detailed price list.',
  'HARDWARE_SELECTION-SUMMARY_CREDIT_VOUCHER': 'Credit',
  'HARDWARE_SELECTION-SUMMARY_DELAYED_SUBSIDY': 'Hardware will be retrieved later',
  'HARDWARE_SELECTION-SUMMARY_TEXT': 'Selected hardware: '
};
