module.exports = {
  'DEBITOR_SELECTION-COLUMN_NAME_ADDRESS': 'Address',
  'DEBITOR_SELECTION-COLUMN_NAME_CUSTOMER_NUMBER': 'customer number',
  'DEBITOR_SELECTION-COLUMN_NAME_DEFAULT': 'Standard',
  'DEBITOR_SELECTION-COLUMN_NAME_FULL_NAME': 'Fullname',
  'DEBITOR_SELECTION-COLUMN_NAME_TYPE': 'Type',
  'HARDWARE_SELECTION-COLUMN_NAME_ARTICLE_NUMBER': 'item number',
  'HARDWARE_SELECTION-COLUMN_NAME_AVAILABILITY': 'Availability',
  'HARDWARE_SELECTION-COLUMN_NAME_CATEGORY': 'Category',
  'HARDWARE_SELECTION-COLUMN_NAME_DEP': 'DEP',
  'HARDWARE_SELECTION-COLUMN_NAME_DESIGNATION': 'designation',
  'HARDWARE_SELECTION-COLUMN_NAME_MANUFACTURE': 'Manufacturer',
  'HARDWARE_SELECTION-COLUMN_NAME_PRICE': 'Price',
  'HEADER_ADDRESS_TYPE': 'Address Type',
  'HEADER_BAN': 'Customer Number',
  'HEADER_BANDWIDTH': 'Bandwidth',
  'HEADER_BANK_ACCOUNT_OWNERSHIP': 'Account Owner',
  'HEADER_BAN_ACCOUNT_NO': 'account number',
  'HEADER_BAN_ACCOUNT_OWNER': 'account owner',
  'HEADER_BAN_ADDRESS': 'Address',
  'HEADER_BAN_ADDRESS_TYPE': 'Rg. Address Type',
  'HEADER_BAN_BANKNAME': 'PBANKNAME',
  'HEADER_BAN_BANK_CODE': 'bank code',
  'HEADER_BAN_BIC': 'BIC',
  'HEADER_BAN_BILLING_ADD': 'Billing address',
  'HEADER_BAN_BILLING_DATE': 'billing date',
  'HEADER_BAN_BILLING_DETAILS': 'Billing Details',
  'HEADER_BAN_BILLING_NAME_ADDRESS': 'Billing Address',
  'HEADER_BAN_BRANCH': 'branch',
  'HEADER_BAN_BRANCH_ID': 'Branch ID',
  'HEADER_BAN_CHANNEL_DESC': 'Sales Channel Desc.',
  'HEADER_BAN_CHANNEL_ID': 'Sales Channel ID',
  'HEADER_BAN_CITY': 'Rg. City',
  'HEADER_BAN_COMPANY_ADDRS': 'Company address',
  'HEADER_BAN_COMPANY_REGISTERED': 'Company registered in',
  'HEADER_BAN_COMPANY_TYPE': 'type of Company',
  'HEADER_BAN_COMP_ID': 'Company ID',
  'HEADER_BAN_CONNECTION_OVER': 'Type of connection overview',
  'HEADER_BAN_CONTACT': 'Contact',
  'HEADER_BAN_CONTACT_PERSON': 'Rg. Contact person',
  'HEADER_BAN_CONTRACT_NAME': 'Framework contract name',
  'HEADER_BAN_COUNTRY_CODE': 'Rg. Country code',
  'HEADER_BAN_CUSTOMER_NUMBER': 'customer number',
  'HEADER_BAN_EMAIL_ADDRS': 'Rg. Email-Address',
  'HEADER_BAN_FAX_NUMBER': 'Rg. Fax number',
  'HEADER_BAN_FIRST_NAME': 'Rg. First name',
  'HEADER_BAN_GEN_AGREE': 'general agreement',
  'HEADER_BAN_GKO_ACC': 'GKO Account',
  'HEADER_BAN_GOING': 'WERE GOING',
  'HEADER_BAN_HOUSE_NO': 'Rg. House no.',
  'HEADER_BAN_HRG_NO': 'HRG-Nr.',
  'HEADER_BAN_INFORMATTION': 'Here you can manage the selected participants uniformly. Uniform means that a value is applied to all selected participants.',
  'HEADER_BAN_KD_ADDRS_TYPE': 'Kd. Address type',
  'HEADER_BAN_KD_CITY': 'Kd. city',
  'HEADER_BAN_KD_CONTACT_PR': 'Kd. Contact Person',
  'HEADER_BAN_KD_COUNTRY_CO': 'Kd. country code',
  'HEADER_BAN_KD_EMAIL_ADD': 'Kd. Email-Adresse',
  'HEADER_BAN_KD_GIVEN_NAME': 'Kd. first given name',
  'HEADER_BAN_KD_HOUSE_NO': 'Kd. House number',
  'HEADER_BAN_KD_LAND': 'Kd. Land',
  'HEADER_BAN_KD_NAME1': 'Kd. Name 1',
  'HEADER_BAN_KD_NAME2': 'Kd. Name 2',
  'HEADER_BAN_KD_NAME3': 'Kd. Name 3',
  'HEADER_BAN_KD_NAME_FORMAT': 'Kd. name format',
  'HEADER_BAN_KD_POST_CODE': 'Kd. Post Code',
  'HEADER_BAN_KD_SALUTION': 'Kd. salutation',
  'HEADER_BAN_KD_STREET': 'Kd. Street',
  'HEADER_BAN_KD_TELE_NO': 'Kd. Telephone number.',
  'HEADER_BAN_KD_TITLE': 'Kd. title',
  'HEADER_BAN_LAND': 'Rg. Land',
  'HEADER_BAN_LEGAL_NAME_ADDRESS': 'Company Address',
  'HEADER_BAN_MANAGE_NO': 'Here you can manage the customer number you have selected',
  'HEADER_BAN_NAME1': 'Rg. Name 1',
  'HEADER_BAN_NAME2': 'Rg. Name 2',
  'HEADER_BAN_NAME3': 'Rg. Name 3',
  'HEADER_BAN_NAME_FORMAT': 'Rg. Name format',
  'HEADER_BAN_NUM_MEMBER': 'Num. Member',
  'HEADER_BAN_PARENT_BAN1': 'Parent BAN 1',
  'HEADER_BAN_PARENT_BAN2': 'Parent BAN 2',
  'HEADER_BAN_PARTY_ID': 'Party ID',
  'HEADER_BAN_PAYMENT': 'Payment',
  'HEADER_BAN_PAYMENT_INFO': 'Payment Information',
  'HEADER_BAN_POSTCODE': 'Rg. Postcode',
  'HEADER_BAN_ROOT_BAN': 'RootBAN',
  'HEADER_BAN_SALES_EMAIL': 'Sales Force Email',
  'HEADER_BAN_SALES_LOC_ID': 'Sales Location ID',
  'HEADER_BAN_SALES_NAME': 'Sales Force Name',
  'HEADER_BAN_SALUTATION': 'Rg. Salutation',
  'HEADER_BAN_SHOP_NAME': 'Shop Name',
  'HEADER_BAN_SORTE_DEST': 'Shortened destination number',
  'HEADER_BAN_SORT_DEST': 'Shortened destination number archive',
  'HEADER_BAN_STATUS': 'BAN-Status',
  'HEADER_BAN_STREET': 'Rg. Street',
  'HEADER_BAN_TELEPHONE_NO': 'Rg. Telephone no.',
  'HEADER_BAN_TITLE': 'Rg. Title',
  'HEADER_BAN_VO_NAME': 'VO Name',
  'HEADER_BASIC_INFO': 'Billing Details',
  'HEADER_BIC': 'BIC',
  'HEADER_BILLING_ADDRESS_TYPE': 'Rg. Address Type',
  'HEADER_BILLING_COUNTRY_NAME': 'Rg. Country',
  'HEADER_BILLING_FIRST_NAME': 'Rg. First Name',
  'HEADER_BILLING_HOUSE_NO': 'Rg. House No.',
  'HEADER_BILLING_NAME_ADDRESS': 'Billing Address',
  'HEADER_BILLING_NAME_FORMAT': 'Rg. Name Format',
  'HEADER_BILLING_SALUTATION': 'Rg. Salutation',
  'HEADER_BILLING_STREET': 'Rg. Street',
  'HEADER_BILLING_TITLE': 'Rg. Title',
  'HEADER_BILL_CITY': 'Rg. City',
  'HEADER_BILL_COUNTRY': 'Rg. Country Code',
  'HEADER_BILL_CYCLE': 'Billing Date',
  'HEADER_BILL_DISTRICT': 'Rg. Contact Person',
  'HEADER_BILL_EMAIL': 'Rg. Email Adress',
  'HEADER_BILL_FAX_NO': 'Rg. Fax Number',
  'HEADER_BILL_LAST_OR_BUSINESS_NAME_1': 'Rg. Name 1',
  'HEADER_BILL_LAST_OR_BUSINESS_NAME_2': 'Rg. Name 2',
  'HEADER_BILL_LAST_OR_BUSINESS_NAME_3': 'Rg. Name 3',
  'HEADER_BILL_PHONE': 'Rg. Telephone Number',
  'HEADER_BILL_ZIP': 'Rg. Postcode',
  'HEADER_BIRTH_DATE': 'Company registered in',
  'HEADER_BPA_ACK_EMAIL_RECEIVED_DATE': 'BPA Confirmation Date',
  'HEADER_CALL_DETAIL_TYPE': 'Type of Connection Overview',
  'HEADER_CARING_VO_ID': 'CARING_VO_ID',
  'HEADER_CITY': 'City',
  'HEADER_COMMIT_END_DATE': 'Poss. End of Contract',
  'HEADER_COMMIT_START_DATE': 'Contract Start',
  'HEADER_COMPANY_NO': 'Company ID',
  'HEADER_COMPANY_NO ': 'Company ID',
  'HEADER_COMPANY_REGISTRATION_NO': 'HRG No.',
  'HEADER_CONDITION_CODE': 'Conditions ID',
  'HEADER_CONTACT': 'Contact',
  'HEADER_CONTACT_EMAIL': 'Contact E-mail',
  'HEADER_CONTRACT_EXTENSION': 'Contract extension possible',
  'HEADER_CONTRACT_NAME': 'Framework Contract Name',
  'HEADER_CONTRACT_TYPE': 'Tariff Type',
  'HEADER_COUNTRY_CODE': 'Country Code',
  'HEADER_COUNTRY_NAME': 'Country',
  'HEADER_CREATED_TS': 'Date of Order',
  'HEADER_CUSTOMER_ACCOUNT_NUMBER': 'Customer Account Number',
  'HEADER_CUSTOMER_MESSAGE': 'Customer Info',
  'HEADER_CUSTOMER_NAME': 'Customer Name',
  'HEADER_CUSTOMER_ORDER_DETAILS': 'Customer Order Detail',
  'HEADER_DBWAN_CREATED_TS': 'Order Date',
  'HEADER_DISTRICT': 'Contact Person',
  'HEADER_ED_CREATED_TS': 'Order Date',
  'HEADER_ED_CUSTOMER_ORDER_DETAILS': 'Customer Order Details',
  'HEADER_ED_ORDER_NUMBER': 'Vodafone Order Number',
  'HEADER_ED_STATUS': 'Status',
  'HEADER_EMAIL_ADDRESS': 'E-Mail',
  'HEADER_EMAIL_SENT_DATE': 'E-Mail Sent Date',
  'HEADER_ERROR_REASON': 'Error',
  'HEADER_FAX_NO': 'Contact Fax',
  'HEADER_FDT_EFFECTIVE_DATE': 'Canceled to',
  'HEADER_FIRST_NAME': 'First Name',
  'HEADER_GKO_ACCOUNT_ID': 'GKO Account',
  'HEADER_GL_COMPANY_TYPE': 'Type of Company',
  'HEADER_HOUSE_NO': 'House Number',
  'HEADER_IBAN': 'IBAN',
  'HEADER_IDENTIFIER_FOR_CUST': 'Internal Code',
  'HEADER_INITIAL_ACTIVATION_DATE': 'Initial Activation',
  'HEADER_INTERNAL_CODE_RESET': 'Reset internal code',
  'HEADER_IS_BPA_ACK_EMAIL_RECEIVED': 'BPA Confirmation',
  'HEADER_IS_EMAIL_SENT': 'Order sent',
  'HEADER_LAST_NAME_1': 'Subscriber Name 1',
  'HEADER_LAST_NAME_2': 'Subscriber Name 2',
  'HEADER_LAST_NAME_3': 'Subscriber Name 3',
  'HEADER_LEGAL_ADDRESS_TYPE': 'Kd. Address Type',
  'HEADER_LEGAL_CITY': 'Kd. City',
  'HEADER_LEGAL_COUNTRY': 'Kd. Country Code',
  'HEADER_LEGAL_COUNTRY_NAME': 'Kd. Country',
  'HEADER_LEGAL_DISTRICT': 'Kd. Contact Person',
  'HEADER_LEGAL_EMAIL': 'Kd. E-Mail Address',
  'HEADER_LEGAL_FIRST_NAME': 'Kd. First Name',
  'HEADER_LEGAL_HOUSE_NO': 'Kd. House Number',
  'HEADER_LEGAL_LAST_OR_BUSINESS_NAME_1': 'Kd. Name 1',
  'HEADER_LEGAL_LAST_OR_BUSINESS_NAME_2': 'Kd. Name 2',
  'HEADER_LEGAL_LAST_OR_BUSINESS_NAME_3': 'Kd. Name 3',
  'HEADER_LEGAL_NAME_ADDRESS': 'Company Address',
  'HEADER_LEGAL_NAME_FORMAT': 'Kd. Name Format',
  'HEADER_LEGAL_PHONE': 'Kd. Phone number.',
  'HEADER_LEGAL_PHONE ': 'Kd. Phone Number.',
  'HEADER_LEGAL_SALUTATION': 'Kd. Salutation',
  'HEADER_LEGAL_STREET': 'Kd. Street',
  'HEADER_LEGAL_TITLE': 'Kd. Title',
  'HEADER_LEGAL_ZIP': 'Kd. Post Code',
  'HEADER_LOCATION_1': 'Location',
  'HEADER_LOCATION_1_AREA': 'First Location area',
  'HEADER_LOCATION_1_BU': 'First Location BU shortcut',
  'HEADER_LOCATION_1_COMPANY_NAME': 'First location: Company name',
  'HEADER_LOCATION_1_NETWORK': 'Network element identifier',
  'HEADER_LOCATION_2': 'Second Location',
  'HEADER_LOCATION_2_AREA': 'Second Location area',
  'HEADER_LOCATION_2_BU': 'Second Location BU shortcut',
  'HEADER_LOCATION_2_COMPANY_NAME': 'Second location: Company name',
  'HEADER_LOCATION_2_NETWORK': 'Customer Order Detail',
  'HEADER_MAIN_HEADER': 'Here you can manage the selected participants uniformly. Uniform means that a value is applied to all selected participants.',
  'HEADER_METHOD_SHORT_DESC': 'Payment',
  'HEADER_NAME': 'Surname',
  'HEADER_NAME_FORMAT': 'Name Format',
  'HEADER_NAME_TITLE': 'Title',
  'HEADER_NEW_PASSWORD': 'New participant password',
  'HEADER_NEXT_SUBSIDY_DATE': 'VVL Date',
  'HEADER_NL_DESC': 'Branch',
  'HEADER_NL_ID': 'Branch ID',
  'HEADER_NUMBER_DIGITS_MASK_CALL_DETAIL': 'Shortened Destination Number',
  'HEADER_NUMBER_OF_DIGITS_MASKED': 'Shortened Destination Number Archive',
  'HEADER_ORDER_NUMBER': 'Barcode',
  'HEADER_ORDER_TYPE': 'Order Type',
  'HEADER_PARENT_BAN1': 'Parent BAN 1',
  'HEADER_PARENT_BAN2': 'Parent BAN 2',
  'HEADER_PARTY_ID': 'Party ID',
  'HEADER_PASSWORD': 'New Subscriber Password',
  'HEADER_PASSWORD_RESET': 'Reset User Password',
  'HEADER_PASSWORD_RESET_IND': 'Reset Password',
  'HEADER_PAYMENT_INFO': 'Payment Information',
  'HEADER_PHONE': 'Contact Phone',
  'HEADER_PO_BOX': 'P.O. Box',
  'HEADER_PRODUCT': 'Product',
  'HEADER_PROJECT_NAME': 'Project name',
  'HEADER_PROLONGATION_ELIGIBILITY': 'Contract Prolongation Possible',
  'HEADER_RDS_ELIGIBILITY': 'Hardware Call Entitled',
  'HEADER_ROOT_BAN': 'RootBAN',
  'HEADER_SALES_FORCE_DESC': 'VO Name',
  'HEADER_SALES_FORCE_EMAIL': 'Salesforce E-Mail',
  'HEADER_SALES_FORCE_NAME_1': 'Salesforce Name',
  'HEADER_SALES_LOCATION_ID': 'Sales Location ID',
  'HEADER_SALES_PRODUCT_NAME': 'Product',
  'HEADER_SALUTATION': 'Salutation',
  'HEADER_SERVICE_LEVEL': 'Service Level',
  'HEADER_SERVICE_NUMBER': 'Service Number',
  'HEADER_SF_TYPE_GROUP_DESC_L5': 'Sales Channel Desc.',
  'HEADER_SF_TYPE_ID': 'Sales Channel ID',
  'HEADER_SHOP_NAME': 'Shop Name',
  'HEADER_ATTACHMENT_INDICATOR': 'Attachments available',
  'HEADER_SIM_SERIAL_NO': 'SIM card number',
  'HEADER_SIM_TYPE': 'SIM card size',
  'HEADER_SINGLE_SELECT_HEADER': 'Here you can manage the participants you have selected',
  'HEADER_SKELETON_CONTRACT_NO': 'Framework Contract',
  'HEADER_SMS_IND': 'Notify subscribers about the change of the subscriber password via SMS',
  'HEADER_SOCS': 'Tariff Options',
  'HEADER_STATE': 'Order Status',
  'HEADER_STATUS': 'Subsriber Status',
  'HEADER_STREET': 'Street',
  'HEADER_SUBSCRIBER_COUNT': 'Num. Subscribers',
  'HEADER_SUBSCRIBER_NO': 'Telephone Number',
  'HEADER_SUBSIDIZED_HANDSET_IND': 'Subv. Tariff',
  'HEADER_SUBS_NAME_ADDRESS': 'Address',
  'HEADER_TARIFF': 'Tariff Group',
  'HEADER_TARIFF_DESCRIPTION': 'Tariff Group Desc.',
  'HEADER_TARIFF_MODEL': 'Tariff model',
  'HEADER_TARIFF_NAME': 'Tariff',
  'HEADER_TARIFF_OPTION': 'Tariff ID',
  'HEADER_TARIFF_OPTION_DESC': 'Tariff Name',
  'HEADER_TARIFF_PRICE': 'Base Price',
  'HEADER_ULTRACARD_COUNT': 'Num. Ultra Cards',
  'HEADER_ULTRACARD_SHORT_DESC_1': 'UltraCard 1 Desc.',
  'HEADER_ULTRACARD_SHORT_DESC_2': 'UltraCard 2 Desc.',
  'HEADER_ULTRACARD_SIM_SERIAL_NO_1': 'SIM No. UltraCard 1',
  'HEADER_ULTRACARD_SIM_SERIAL_NO_2': 'SIM No. UltraCard 2',
  'HEADER_ULTRACARD_SIM_TYPE_1': 'UltraCard 1 SIM Type',
  'HEADER_ULTRACARD_SIM_TYPE_2': 'UltraCard 2 SIM Type',
  'HEADER_USER_NAME': 'Customer',
  'HEADER_VF_REF_ORDER_NUMBER': 'Reference Order Number',
  'HEADER_ZIP': 'Post Code',
  'TARIFF_SELECTION-COLUMN_NAME_PRICE': 'Price',
  'TARIFF_SELECTION-COLUMN_NAME_TARIFF': 'Tariff',
  'SHIPMENT_SELECTION-COLUMN_NAME_ADDRESS':	'Address',
  'SHIPMENT_SELECTION-COLUMN_NAME_DEFAULT':	'default',
  'SHIPMENT_SELECTION-COLUMN_NAME_FULL_NAME':	'Fullname',
  'HEADER_ACT_ULTRACARD_SIM_SERIAL_NO_1':	'1.UltraCard',
  'HEADER_ACT_ULTRACARD_SIM_SERIAL_NO_2':	'2.UltraCard',
  'HEADER_ACT_ULTRACARD_SIM_TYPE_1':	'1.UltraCard',
  'HEADER_ACT_ULTRACARD_SIM_TYPE_2':	'2.UltraCard'

};
