module.exports = {
  "ABORT_OR_STOP": "Abort, stop",
  "CONTACTED_BY_US": "How would you like to be contacted by us?",
  "CONTACT_US_CHOOSE": "Choose",
  "CONTACT_US_HEADER": "Contact",
  "CONTACT_US_LABEL": "true",
  "CONTACT_US_PHONE_NUMBER": "00 49 / 172 12 34",
  "CONTACT_US_SEND_EMAIL": "Send e-mail",
  "CUSTOMER_OR_PHONE_NUMBER": "Customer number / phone number",
  "DESCRIPTION_LIMIT": "(Max 500 characters)",
  "DROP_DOWN-SELECT": "Choose",
  "ENTER_CUST_PHONE_EMPTY_CHECK": "Please enter your customer number / phone number.",
  "ENTER_CUST_PHONE_NUMBER_CHECK": "Please enter only digits",
  "ENTER_PHONE_EMPTY_CHECK": "Please enter a phone number",
  "ENTER_PHONE_NUMBER": "Please enter your phone number",
  "ENTER_PHONE_NUMBER_CHECK": "Bitte geben Sie nur Ziffern ein",
  "EXTENDED_YES": "Yes\\u002A",
  "LANDING_PAGE-SHOP_NO_BANS_INFO_MSG": "Please note that currently no customer numbers and participants are assigned to this shop.",
  "MESSAGE_SEND_SUCCESS": "E-mail sent to customer service representatives.",
  "RADIO_BUTTON_EMAIL": "Email ",
  "RADIO_BUTTON_RECALL": "Recall ",
  "SENDEMAILOPTIONS_AREAOFISSUES_ANDERER_BEREICH": "Other area",
  "SENDEMAILOPTIONS_AREAOFISSUES_BENUTZER_ADMINISTRATION": "User Administration",
  "SENDEMAILOPTIONS_AREAOFISSUES_TEILNEHMER_VERWALTUNG": "Affiliate Management",
  "SEND_MAIL": "Send",
  "SEND_REQUEST_TO_TITLE": "Portal area to which you would like to send a request",
  "SELECTION-EDIT": "Edit",
  "VALIDATION_MSG-EMAIL": "Please enter a valid e-mail address",
  "VALIDATION_MSG-INVALIDBIC": "Invalid BIC",
  "VALIDATION_MSG-INVALIDBKACCOWNERSHIP": "Invalid bankaccountownership",
  "VALIDATION_MSG-INVALIDCHARACTERS": "The field contains invalid characters",
  "VALIDATION_MSG-INVALIDCITY": "Invalid city",
  "VALIDATION_MSG-INVALIDHOUSENUMBER": "Invalid house number.",
  "VALIDATION_MSG-INVALIDIBAN": "Invalid IBAN",
  "VALIDATION_MSG-INVALIDINPUTCHARACTERS": "The input contains invalid characters.",
  "VALIDATION_MSG-INVALIDINTERNALCUSTID": "Please enter a valid internal code.",
  "VALIDATION_MSG-INVALIDVOID": "The VO-ID is a mandatory field with 8 numeric characters.",
  "VALIDATION_MSG-LENGTHMISMATCH": "The total length of fields {{fields [0]}} and {{fields [1]}} must be between {{min}} and {{max}} characters",
  "VALIDATION_MSG-MAX": "The value can not be greater than {{max}}",
  "VALIDATION_MSG-MAXLENGTH": "Please enter a value with a maximum of {{requiredLength}} characters",
  "VALIDATION_MSG-MIN": "The value can not be less than {{min}}",
  "VALIDATION_MSG-MINLENGTH": "Please enter a value with at least {{requiredLength}} characters",
  "VALIDATION_MSG-NONE_SELECTED_ERROR": "<p><b>Sorry, an error has occurred</b></p> <p>No participants were selected.</p>",
  "VALIDATION_MSG-ONLYCHARACTERS": "Only characters are allowed",
  "VALIDATION_MSG-ONLYCHARACTERSANDNUMBERS": "Only characters and numbers are allowed",
  "VALIDATION_MSG-ONLYNUMBERS": "Please use only numbers.",
  "VALIDATION_MSG-PATTERN": "Invalid format",
  "VALIDATION_MSG-PHONE": "phone number is invalid",
  "VALIDATION_MSG-PHONECHECKNUMBER": "Please enter a phone number",
  "VALIDATION_MSG-PHONEEMPTYCHECK": "Bitte geben Sie nur Ziffern ein",
  "VALIDATION_MSG-PHONEORCUSTCHECKNUMBER": "Please enter only digits",
  "VALIDATION_MSG-PHONEORCUSTEMPTYCHECK": "Please enter your customer number / phone number.",
  "VALIDATION_MSG-REQUIRED": "This field is required",
  "VALIDATION_MSG-SANITIZATIONERROR": "Your entry contains invalid characters",
  "VALIDATION_MSG-TRIGGERERROR": "A rate option of type Trigger can not have a trigger rate option.",
  "YOUR_CONCERN": "Your concern",
  "VALIDATION_MSG-INVALIDAREACODE": "Please enter area code beginning with \"0\" and a total of 3-6 characters",
  "VALIDATION_MSG-DUPLICATESERIALNO": "Your entry contains card numbers that have been used several times. Please correct your entry and try again."
};
