module.exports = {
  "ED-SHOP_HEADING":"Create shop",
  "ED-CUSTOMER_NUMBER":"Customer number",
  "ED-CUSTOMER_NAME":"Customer name",
  "ED-SHOP_LABEL":"Setup -> General",
  "ED-CREATE_SHOP":"Create shop",
  "ED-CREATE_SHOP_ERROR": "This name is already taken. Please enter a new name.",
  "ED-SHOP_LIST_TITLE":"Shop search and customize",
  "ED-SHOP_LIST_COL1":"Customer Name",
  "ED-SHOP_LIST_COL2":"Name of the shop",
  "ED-SHOP_LIST_COL3":"Top level customer",
  "ED-SHOP_LIST_COL4":"Customer number",
  "ED-SHOP_LIST_COL5":"Number of customer number",
  "ED-EDIT_SHOP_TITLE":"Customize shop",
  "ED-EDIT_SHOP_CUSTOMER":"Top level customer",
  "ED-EDIT_SHOP_SELECT_MESSAGE1":"Results",
  "ED-EDIT_SHOP_SELECT_MESSAGE2":"Result",
  "ED-EDIT_SHOP_BACK":"Abort",
  "ED-EDIT_SHOP_SAVE":"Continue",
  "EDIT_SHOP_CUSTOMER-NO_BILLING_NOS":"No billing account is available for the following customer numbers:",
  "EDIT_SHOP_PANEL1_SUCCESS":"Setup-> Generally saved successfully",
  "EDIT_SHOP_BILLING-NO_BILLING_NOS_SELECTED":"No billing account was selected for the following customer numbers:",
  "EDIT_SHOP_CUSTOMER_SUCCESS":"Customer numbers saved successfully",
  "EDIT_SHOP_BILLING_SUCCESS":"Billing accounts saved successfully",
  "EDIT_SHOP_SELECT_ALERT":"You have removed the last customer number of the shop",
  "EDIT_SHOP_PRODUCT_SUCCESS":"Products successfully saved",
  "EDIT_SHOP_EMAIL_APPROVAL":"Activate order receipt by e-mail?",
  "EDIT_SHOP_AUTHENTICATION":"2-factor authentication",
  "EDIT_SHOP_SUCCESS":"Shop Saved Successfully."
};